[Package]
Name="levylab_lib_lvtoitx"
Version="3.0.4.9"
Release=""
ID=55afa0abe7eebaa3e4e84627e17c89bd
File Format="vip"
Format Version="2017"
Display Name="LVtoITX"


[Description]
Description="Collection of VIs to write and read Igor Text Files (*.itx), text-based spreadsheet data files (*.dat), and TDMS"
Summary=""
License="BSD-3"
Copyright="Copyright (c) 2020, LevyLab"
Distribution=""
Vendor="LevyLab"
URL=""
Packager="Patrick Irvin"
Demo="FALSE"
Release Notes="[3.0.3]\0D\0A---> beta release! This is a major rewrite; code is still being tested and examples are being written <---\0D\0A- Intensity Graph to ITX now uses inverted Rainbow as the default color scale"
System Package="FALSE"
Sub Package="FALSE"
License Agreement="TRUE"


[LabVIEW]
close labview before install="FALSE"
restart labview after install="FALSE"
skip mass compile after install="FALSE"


[Platform]
Exclusive_LabVIEW_Version="LabVIEW>=16.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="ALL"


[Script VIs]
PreInstall=""
PostInstall=""
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires="jki_lib_state_machine>=2018.0.7.45,levylab_lib_fileutilities>=1.2.5.12,levylab_lib_graph_utilities>=2.1.2.4,levylab_lib_xy_utilities>=1.2.0.12,oglib_appcontrol>=4.1.0.7,oglib_dictionary>=4.0.0.4,oglib_file>=4.0.1.22,oglib_string>=4.1.0.12,oglib_time>=4.0.1.3"
Conflicts=""


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="3"
Sub-Packages=""
Namespaces=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=153
File 0="user.lib/LevyLab/LV to ITX/Tests/Test Files.000000.dat"
File 1="user.lib/LevyLab/LV to ITX/Tests/Test Zip Methods.vi"
File 2="user.lib/LevyLab/LV to ITX/Tests/XY Graph.itx"
File 3="user.lib/LevyLab/LV to ITX/Tests/Unit Tests/Test Data Dictionary API.vi"
File 4="user.lib/LevyLab/LV to ITX/Tests/Unit Tests/Unit Tests.vi"
File 5="user.lib/LevyLab/LV to ITX/Tests/Performance Tests/Duplicate Files.vi"
File 6="user.lib/LevyLab/LV to ITX/Tests/Performance Tests/Performance Tests.vi"
File 7="user.lib/LevyLab/LV to ITX/Tests/Performance Tests/Speed Test Single VI.vi"
File 8="user.lib/LevyLab/LV to ITX/Tests/Performance Tests/Test Read Speed.vi"
File 9="user.lib/LevyLab/LV to ITX/Tests/Performance Tests/Test TDMS Read Speed.vi"
File 10="user.lib/LevyLab/LV to ITX/Tests/Performance Tests/Test Write Speed.vi"
File 11="user.lib/LevyLab/LV to ITX/Tests/Jeremy Examples/FrontPanelRecorder.vit"
File 12="user.lib/LevyLab/LV to ITX/Tests/Jeremy Examples/Jeremy Example.vi"
File 13="user.lib/LevyLab/LV to ITX/Tests/Jeremy Examples/Magic.vi"
File 14="user.lib/LevyLab/LV to ITX/Tests/Jeremy Examples/Read VI Data File.vi"
File 15="user.lib/LevyLab/LV to ITX/Tests/Jeremy Examples/VI Example.vi"
File 16="user.lib/LevyLab/LV to ITX/Tests/Jeremy Examples/Write VI Data File.vi"
File 17="user.lib/LevyLab/LV to ITX/Macros/Conversion.lvclass"
File 18="user.lib/LevyLab/LV to ITX/Macros/Convert Experiment Folder.vi"
File 19="user.lib/LevyLab/LV to ITX/Macros/Support/Dictionary.Add File and Notes.vi"
File 20="user.lib/LevyLab/LV to ITX/Macros/Support/Dictionary.Add Time Values.vi"
File 21="user.lib/LevyLab/LV to ITX/Macros/Support/Dictionary.Compare.vi"
File 22="user.lib/LevyLab/LV to ITX/Macros/Support/Dictionary.Expand Array Size.vi"
File 23="user.lib/LevyLab/LV to ITX/Macros/Support/Dictionary.Remove Empty.vi"
File 24="user.lib/LevyLab/LV to ITX/Macros/Support/Dictionary.Split into DBL and String.vi"
File 25="user.lib/LevyLab/LV to ITX/Macros/Support/Write Experiment to TDMS Conversion Log.vi"
File 26="user.lib/LevyLab/LV to ITX/Macros/ITX/File to TDMS.vi"
File 27="user.lib/LevyLab/LV to ITX/Examples/DAT Example.vi"
File 28="user.lib/LevyLab/LV to ITX/Examples/ITX Example.vi"
File 29="user.lib/LevyLab/LV to ITX/Examples/ITX2 Example.vi"
File 30="user.lib/LevyLab/LV to ITX/Examples/TDMS Read Example.vi"
File 31="user.lib/LevyLab/LV to ITX/Examples/Tree.vi"
File 32="user.lib/LevyLab/LV to ITX/Data.TDMS/Data.TDMS.lvclass"
File 33="user.lib/LevyLab/LV to ITX/Data.TDMS/Private/Read TDMS Comments.vi"
File 34="user.lib/LevyLab/LV to ITX/Data.TDMS/Private/Read TDMS Wave 1D.vi"
File 35="user.lib/LevyLab/LV to ITX/Data.TDMS/Private/Read TDMS Wavenames into Ring.vi"
File 36="user.lib/LevyLab/LV to ITX/Data.TDMS/Private/Read TDMS Wavenames.vi"
File 37="user.lib/LevyLab/LV to ITX/Data.TDMS/Private/Read TDMS XYN.vi"
File 38="user.lib/LevyLab/LV to ITX/Data.TDMS/Private/Read TDMS.vi"
File 39="user.lib/LevyLab/LV to ITX/Data.TDMS/Private/Write TDMS.vi"
File 40="user.lib/LevyLab/LV to ITX/Data.TDMS/Overrides/Close.vi"
File 41="user.lib/LevyLab/LV to ITX/Data.TDMS/Overrides/Open.vi"
File 42="user.lib/LevyLab/LV to ITX/Data.TDMS/Overrides/Read.vi"
File 43="user.lib/LevyLab/LV to ITX/Data.TDMS/Overrides/Write.vi"
File 44="user.lib/LevyLab/LV to ITX/Data.ITX/Data.ITX.lvclass"
File 45="user.lib/LevyLab/LV to ITX/Data.ITX/LV to ITX  Retrieve Equation.vi"
File 46="user.lib/LevyLab/LV to ITX/Data.ITX/LV to ITX  Retrieve.vi"
File 47="user.lib/LevyLab/LV to ITX/Data.ITX/LV to ITX 2D AutoPlot.vi"
File 48="user.lib/LevyLab/LV to ITX/Data.ITX/LV to ITX XY AutoPlot.vi"
File 49="user.lib/LevyLab/LV to ITX/Data.ITX/LV to ITX XY2 AutoPlot.vi"
File 50="user.lib/LevyLab/LV to ITX/Data.ITX/Read ITX.vi"
File 51="user.lib/LevyLab/LV to ITX/Data.ITX/util/1D Dbl to ITX Wave.vi"
File 52="user.lib/LevyLab/LV to ITX/Data.ITX/util/1D Str to ITX Wave.vi"
File 53="user.lib/LevyLab/LV to ITX/Data.ITX/util/2D Commands.vi"
File 54="user.lib/LevyLab/LV to ITX/Data.ITX/util/2D Dbl to ITX Wave.vi"
File 55="user.lib/LevyLab/LV to ITX/Data.ITX/util/2D X&Y Commands.vi"
File 56="user.lib/LevyLab/LV to ITX/Data.ITX/util/Create Folder Index.vi"
File 57="user.lib/LevyLab/LV to ITX/Data.ITX/util/IBW aperture Commands.vi"
File 58="user.lib/LevyLab/LV to ITX/Data.ITX/util/ITX2 Plot Commands.vi"
File 59="user.lib/LevyLab/LV to ITX/Data.ITX/util/Notes to ITX.vi"
File 60="user.lib/LevyLab/LV to ITX/Data.ITX/util/Parse Comments and Commands.vi"
File 61="user.lib/LevyLab/LV to ITX/Data.ITX/util/R+coord Commands.vi"
File 62="user.lib/LevyLab/LV to ITX/Data.ITX/util/Read Folder Index.vi"
File 63="user.lib/LevyLab/LV to ITX/Data.ITX/util/XY from 2D Commands.vi"
File 64="user.lib/LevyLab/LV to ITX/Data.ITX/util/XY Plot Commands W2D.vi"
File 65="user.lib/LevyLab/LV to ITX/Data.ITX/util/XY Plot Commands.vi"
File 66="user.lib/LevyLab/LV to ITX/Data.ITX/Typedefs/Retrieve Data Type.ctl"
File 67="user.lib/LevyLab/LV to ITX/Data.ITX/Typedefs/Retrieve Formula Type.ctl"
File 68="user.lib/LevyLab/LV to ITX/Data.ITX/Typedefs/Retrieve Index.ctl"
File 69="user.lib/LevyLab/LV to ITX/Data.ITX/Typedefs/Retrieve N Results.ctl"
File 70="user.lib/LevyLab/LV to ITX/Data.ITX/private/Check Wavename Length.vi"
File 71="user.lib/LevyLab/LV to ITX/Data.ITX/private/Format Wavename.vi"
File 72="user.lib/LevyLab/LV to ITX/Data.ITX/Overrides/Read.vi"
File 73="user.lib/LevyLab/LV to ITX/Data.ITX/Overrides/Write.vi"
File 74="user.lib/LevyLab/LV to ITX/Data.ITX/Main/Parse ITX String.vi"
File 75="user.lib/LevyLab/LV to ITX/Data.ITX/Main/Write ITX (2D w X&Y).vi"
File 76="user.lib/LevyLab/LV to ITX/Data.ITX/Main/Write ITX (R+coord).vi"
File 77="user.lib/LevyLab/LV to ITX/Data.ITX/Main/Write ITX (XY).vi"
File 78="user.lib/LevyLab/LV to ITX/Data.ITX/Main/Write ITX (XY2).vi"
File 79="user.lib/LevyLab/LV to ITX/Data.ITX/Main/Write ITX.vi"
File 80="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/Format ITX Graph.vi"
File 81="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/ITX Commands.lvclass"
File 82="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/typedefs/grid--enum.ctl"
File 83="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/typedefs/Label--cluster.ctl"
File 84="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/typedefs/Log--cluster.ctl"
File 85="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/typedefs/log--enum.ctl"
File 86="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/typedefs/textbox_anchorcolumn--enum.ctl"
File 87="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/typedefs/textbox_anchorrow--enum.ctl"
File 88="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/private/Commands to ITX.vi"
File 89="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/API/AppendImage.vi"
File 90="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/API/AppendToGraph.vi"
File 91="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/API/ColorScale.vi"
File 92="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/API/Commands to ITX.vi"
File 93="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/API/Generate Command String.vi"
File 94="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/API/Label.vi"
File 95="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/API/Legend.vi"
File 96="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/API/ModifyGraph axThick.vi"
File 97="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/API/ModifyGraph grid.vi"
File 98="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/API/ModifyGraph height.vi"
File 99="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/API/ModifyGraph Log.vi"
File 100="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/API/ModifyGraph mirror.vi"
File 101="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/API/ModifyGraph prescaleExp.vi"
File 102="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/API/ModifyGraph rgb.vi"
File 103="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/API/ModifyGraph width.vi"
File 104="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/API/ModifyImage ctab.vi"
File 105="user.lib/LevyLab/LV to ITX/Data.ITX/ITX Commands/API/Textbox.vi"
File 106="user.lib/LevyLab/LV to ITX/Data.ITX/Graph/Configure XY Graph.vi"
File 107="user.lib/LevyLab/LV to ITX/Data.ITX/Graph/Intensity Graph to Igor Graph.vi"
File 108="user.lib/LevyLab/LV to ITX/Data.ITX/Graph/LV to Igor Graph (UI).vi"
File 109="user.lib/LevyLab/LV to ITX/Data.ITX/Graph/XY Graph to Igor Graph.vi"
File 110="user.lib/LevyLab/LV to ITX/Data.DAT/Data.DAT.lvclass"
File 111="user.lib/LevyLab/LV to ITX/Data.DAT/Read DAT.vi"
File 112="user.lib/LevyLab/LV to ITX/Data.DAT/Write DAT (1D).vi"
File 113="user.lib/LevyLab/LV to ITX/Data.DAT/Write DAT (2D).vi"
File 114="user.lib/LevyLab/LV to ITX/Data.DAT/Write DAT.vi"
File 115="user.lib/LevyLab/LV to ITX/Data.DAT/private/Parse DAT String.vi"
File 116="user.lib/LevyLab/LV to ITX/Data.DAT/Overrides/Read.vi"
File 117="user.lib/LevyLab/LV to ITX/Data.DAT/Overrides/Write.vi"
File 118="user.lib/LevyLab/LV to ITX/Data/Data Read.vi"
File 119="user.lib/LevyLab/LV to ITX/Data/Data Write.vi"
File 120="user.lib/LevyLab/LV to ITX/Data/Data.lvclass"
File 121="user.lib/LevyLab/LV to ITX/Data/Typedefs/Dictionary--cluster.ctl"
File 122="user.lib/LevyLab/LV to ITX/Data/Typedefs/File Type--enum.ctl"
File 123="user.lib/LevyLab/LV to ITX/Data/Typedefs/Operation--enum.ctl"
File 124="user.lib/LevyLab/LV to ITX/Data/Protected/Add Letter.vi"
File 125="user.lib/LevyLab/LV to ITX/Data/Protected/Populate Ring Text [].vi"
File 126="user.lib/LevyLab/LV to ITX/Data/Protected/Replace Period with Underscore.vi"
File 127="user.lib/LevyLab/LV to ITX/Data/Protected/Replace Space with Empty.vi"
File 128="user.lib/LevyLab/LV to ITX/Data/Protected/Variant to DBL Array.vi"
File 129="user.lib/LevyLab/LV to ITX/Data/Protected/Variant to String.vi"
File 130="user.lib/LevyLab/LV to ITX/Data/Private/Format Path and Filename.vi"
File 131="user.lib/LevyLab/LV to ITX/Data/Framework (For Override)/Close.vi"
File 132="user.lib/LevyLab/LV to ITX/Data/Framework (For Override)/Create.vi"
File 133="user.lib/LevyLab/LV to ITX/Data/Framework (For Override)/Open.vi"
File 134="user.lib/LevyLab/LV to ITX/Data/Framework (For Override)/Read.vi"
File 135="user.lib/LevyLab/LV to ITX/Data/Framework (For Override)/Write.vi"
File 136="user.lib/LevyLab/LV to ITX/Data/API/Append to Data (Dictionary).vi"
File 137="user.lib/LevyLab/LV to ITX/Data/API/Read Append Index.vi"
File 138="user.lib/LevyLab/LV to ITX/Data/API/Read Append.vi"
File 139="user.lib/LevyLab/LV to ITX/Data/API/Read Data (Dictionary).vi"
File 140="user.lib/LevyLab/LV to ITX/Data/API/Read Igor Commands.vi"
File 141="user.lib/LevyLab/LV to ITX/Data/API/Read Notes.vi"
File 142="user.lib/LevyLab/LV to ITX/Data/API/Read Operation.vi"
File 143="user.lib/LevyLab/LV to ITX/Data/API/Read Path.vi"
File 144="user.lib/LevyLab/LV to ITX/Data/API/Read Wavenames.vi"
File 145="user.lib/LevyLab/LV to ITX/Data/API/Write Append.vi"
File 146="user.lib/LevyLab/LV to ITX/Data/API/Write Data (Dictionary).vi"
File 147="user.lib/LevyLab/LV to ITX/Data/API/Write Igor Commands.vi"
File 148="user.lib/LevyLab/LV to ITX/Data/API/Write Notes.vi"
File 149="user.lib/LevyLab/LV to ITX/Data/API/Write Path.vi"
File 150="user.lib/LevyLab/LV to ITX/Data/API/XY-Data to Dictionary (Multiple).vi"
File 151="user.lib/LevyLab/LV to ITX/Data/API/XY-Data to Dictionary (single).vi"
File 152="user.lib/LevyLab/LV to ITX/Data/API/XY-Data to Dictionary.vi"


[File Group 1]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="Always"
Num Files=29
File 0="_functions_levylab_lib_lvtoitx_1.mnu"
File 1="_functions_levylab_lib_lvtoitx_10.mnu"
File 2="_functions_levylab_lib_lvtoitx_11.mnu"
File 3="_functions_levylab_lib_lvtoitx_12.mnu"
File 4="_functions_levylab_lib_lvtoitx_13.mnu"
File 5="_functions_levylab_lib_lvtoitx_14.mnu"
File 6="_functions_levylab_lib_lvtoitx_15.mnu"
File 7="_functions_levylab_lib_lvtoitx_16.mnu"
File 8="_functions_levylab_lib_lvtoitx_17.mnu"
File 9="_functions_levylab_lib_lvtoitx_18.mnu"
File 10="_functions_levylab_lib_lvtoitx_19.mnu"
File 11="_functions_levylab_lib_lvtoitx_2.mnu"
File 12="_functions_levylab_lib_lvtoitx_20.mnu"
File 13="_functions_levylab_lib_lvtoitx_21.mnu"
File 14="_functions_levylab_lib_lvtoitx_22.mnu"
File 15="_functions_levylab_lib_lvtoitx_23.mnu"
File 16="_functions_levylab_lib_lvtoitx_24.mnu"
File 17="_functions_levylab_lib_lvtoitx_25.mnu"
File 18="_functions_levylab_lib_lvtoitx_26.mnu"
File 19="_functions_levylab_lib_lvtoitx_27.mnu"
File 20="_functions_levylab_lib_lvtoitx_28.mnu"
File 21="_functions_levylab_lib_lvtoitx_3.mnu"
File 22="_functions_levylab_lib_lvtoitx_4.mnu"
File 23="_functions_levylab_lib_lvtoitx_5.mnu"
File 24="_functions_levylab_lib_lvtoitx_6.mnu"
File 25="_functions_levylab_lib_lvtoitx_7.mnu"
File 26="_functions_levylab_lib_lvtoitx_8.mnu"
File 27="_functions_levylab_lib_lvtoitx_9.mnu"
File 28="functions_levylab_lib_lvtoitx.mnu"


[File Group 2]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="If Newer"
Num Files=1
File 0="dir.mnu"
