[Package]
Name="levylab_lib_lvtoitx"
Version="3.10.0.9"
Release=""
ID=51d697be9034af99d33120d5a3786946
File Format="vip"
Format Version="2017"
Display Name="LV-Data"


[Description]
Description="- Collection of VIs to write and read files in TDMS, Igor Text (*.itx), and text-based spreadsheet data (*.dat) formats.\0D\0A- LV graph to Igor Pro and Igor Pro formatters\0D\0A- Tools are provided for uploading to and downloading from AWS S3"
Summary=""
License="BSD-3"
Copyright="Copyright (c) 2025, LevyLab"
Distribution=""
Vendor="LevyLab"
URL=""
Packager="Patrick Irvin"
Demo="FALSE"
Release Notes="[3.10.0]]\0D\0A- remove tests from package and update package dependencies"
System Package="FALSE"
Sub Package="FALSE"
License Agreement="TRUE"


[LabVIEW]
close labview before install="FALSE"
restart labview after install="FALSE"
skip mass compile after install="FALSE"
install into global environment="FALSE"


[Platform]
Exclusive_LabVIEW_Version="LabVIEW>=19.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="ALL"


[Script VIs]
PreInstall=""
PostInstall=""
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires="i3_external_encryption>=1.0.0.8,jdp_science_lib_common_utilities>=1.4.2.19,jki_lib_json_serialization>=1.1.10.37,jki_lib_serialization>=1.0.1.14,jki_lib_state_machine>=2018.0.7.45,jki_lib_unicode>=1.0.0.7,labview_open_source_lib_epoch_datetime>=1.3.0.8,levylab_lib_control_vi>=1.3.0.11,levylab_lib_fileutilities>=1.2.6.13,levylab_lib_graph_utilities>=2.1.11.4,levylab_lib_xy_utilities>=1.6.0.6,mgi_lib_1d_array>=1.0.2.3,mgi_lib_application_control>=1.1.1.10,mgi_lib_file>=1.1.0.4,mgi_lib_numeric>=1.1.0.2,mgi_lib_string>=1.1.1.5,mgi_lib_timing>=1.1.0.2,mgi_lib_tree>=1.0.4.4,national_instruments_lib_guid_generator>=1.0.2.3,ni_cloud_toolkit_for_aws>=1.1.0.1,oglib_appcontrol>=4.1.0.7,oglib_array>=4.1.1.14,oglib_dictionary>=4.0.0.4,oglib_error>=4.2.0.23,oglib_file>=4.0.1.22,oglib_lvdata>=5.0.0.27,oglib_md5>=4.1.1.10,oglib_numeric>=4.1.0.8,oglib_string>=5.0.0.25,oglib_time>=4.0.1.3,wireflow_ab_lib_wf_progressbar>=1.0.2.56"
Conflicts=""


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="3"
Sub-Packages=""
Namespaces=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=176
File 0="user.lib/LevyLab/LV-Data/Macros/Conversion.lvclass"
File 1="user.lib/LevyLab/LV-Data/Macros/Convert Experiment Folder.vi"
File 2="user.lib/LevyLab/LV-Data/Macros/Support/Dictionary.Add File and Notes.vi"
File 3="user.lib/LevyLab/LV-Data/Macros/Support/Dictionary.Add Time Values.vi"
File 4="user.lib/LevyLab/LV-Data/Macros/Support/Dictionary.Compare.vi"
File 5="user.lib/LevyLab/LV-Data/Macros/Support/Dictionary.Expand Array Size.vi"
File 6="user.lib/LevyLab/LV-Data/Macros/Support/Dictionary.Remove Empty.vi"
File 7="user.lib/LevyLab/LV-Data/Macros/Support/Dictionary.Split into DBL and String.vi"
File 8="user.lib/LevyLab/LV-Data/Macros/Support/Write Experiment to TDMS Conversion Log.vi"
File 9="user.lib/LevyLab/LV-Data/Macros/ITX/File to TDMS.vi"
File 10="user.lib/LevyLab/LV-Data/LV-Data.TDMS/LV-Data.TDMS.lvclass"
File 11="user.lib/LevyLab/LV-Data/LV-Data.TDMS/Private/Index to Group Name.vi"
File 12="user.lib/LevyLab/LV-Data/LV-Data.TDMS/Private/Read TDMS.vi"
File 13="user.lib/LevyLab/LV-Data/LV-Data.TDMS/Private/Write TDMS.vi"
File 14="user.lib/LevyLab/LV-Data/LV-Data.TDMS/Overrides/Close.vi"
File 15="user.lib/LevyLab/LV-Data/LV-Data.TDMS/Overrides/Open.vi"
File 16="user.lib/LevyLab/LV-Data/LV-Data.TDMS/Overrides/Read.vi"
File 17="user.lib/LevyLab/LV-Data/LV-Data.TDMS/Overrides/Write.vi"
File 18="user.lib/LevyLab/LV-Data/LV-Data.TDMS/API/Read TDMS Comments.vi"
File 19="user.lib/LevyLab/LV-Data/LV-Data.TDMS/API/Read TDMS Wave 1D.vi"
File 20="user.lib/LevyLab/LV-Data/LV-Data.TDMS/API/Read TDMS Wavenames into Ring.vi"
File 21="user.lib/LevyLab/LV-Data/LV-Data.TDMS/API/Read TDMS Wavenames.vi"
File 22="user.lib/LevyLab/LV-Data/LV-Data.TDMS/API/Read TDMS XYN.vi"
File 23="user.lib/LevyLab/LV-Data/LV-Data.S3/LV-Data.S3.lvclass"
File 24="user.lib/LevyLab/LV-Data/LV-Data.S3/Tree.vi"
File 25="user.lib/LevyLab/LV-Data/LV-Data.S3/Typedefs/S3 Backup--cluster.ctl"
File 26="user.lib/LevyLab/LV-Data/LV-Data.S3/private/AWS Credentials Dialog.vi"
File 27="user.lib/LevyLab/LV-Data/LV-Data.S3/private/AWS Credentials Path.vi"
File 28="user.lib/LevyLab/LV-Data/LV-Data.S3/private/Handle S3 Error.vi"
File 29="user.lib/LevyLab/LV-Data/LV-Data.S3/private/recursively populate tree ctl.vi"
File 30="user.lib/LevyLab/LV-Data/LV-Data.S3/private/split object path to hierarchy.vi"
File 31="user.lib/LevyLab/LV-Data/LV-Data.S3/API/Download File.vi"
File 32="user.lib/LevyLab/LV-Data/LV-Data.S3/API/List Bucket Contents.vi"
File 33="user.lib/LevyLab/LV-Data/LV-Data.S3/API/Populate Tree Ctl from Bucket.vi"
File 34="user.lib/LevyLab/LV-Data/LV-Data.S3/API/Read AWS Credentials File.vi"
File 35="user.lib/LevyLab/LV-Data/LV-Data.S3/API/Read.vi"
File 36="user.lib/LevyLab/LV-Data/LV-Data.S3/API/Set Bucket.vi"
File 37="user.lib/LevyLab/LV-Data/LV-Data.S3/API/Upload File.vi"
File 38="user.lib/LevyLab/LV-Data/LV-Data.S3/API/Verify File.vi"
File 39="user.lib/LevyLab/LV-Data/LV-Data.S3/API/Write.vi"
File 40="user.lib/LevyLab/LV-Data/LV-Data.ITX/LV to ITX 2D AutoPlot.vi"
File 41="user.lib/LevyLab/LV-Data/LV-Data.ITX/LV to ITX Retrieve Equation.vi"
File 42="user.lib/LevyLab/LV-Data/LV-Data.ITX/LV to ITX Retrieve.vi"
File 43="user.lib/LevyLab/LV-Data/LV-Data.ITX/LV to ITX XY AutoPlot.vi"
File 44="user.lib/LevyLab/LV-Data/LV-Data.ITX/LV to ITX XY2 AutoPlot.vi"
File 45="user.lib/LevyLab/LV-Data/LV-Data.ITX/LV-Data.ITX.lvclass"
File 46="user.lib/LevyLab/LV-Data/LV-Data.ITX/Typedefs/Retrieve Data Type.ctl"
File 47="user.lib/LevyLab/LV-Data/LV-Data.ITX/Typedefs/Retrieve Formula Type.ctl"
File 48="user.lib/LevyLab/LV-Data/LV-Data.ITX/Typedefs/Retrieve Index.ctl"
File 49="user.lib/LevyLab/LV-Data/LV-Data.ITX/Typedefs/Retrieve N Results.ctl"
File 50="user.lib/LevyLab/LV-Data/LV-Data.ITX/Tests/temp/1-array.itx"
File 51="user.lib/LevyLab/LV-Data/LV-Data.ITX/Tests/temp/2-array.itx"
File 52="user.lib/LevyLab/LV-Data/LV-Data.ITX/Tests/temp/3-map.itx"
File 53="user.lib/LevyLab/LV-Data/LV-Data.ITX/Tests/temp/4-dictionary.itx"
File 54="user.lib/LevyLab/LV-Data/LV-Data.ITX/Tests/temp/5-XY.itx"
File 55="user.lib/LevyLab/LV-Data/LV-Data.ITX/Tests/temp/6-XY2.itx"
File 56="user.lib/LevyLab/LV-Data/LV-Data.ITX/private/Assemble ITX string.vim"
File 57="user.lib/LevyLab/LV-Data/LV-Data.ITX/private/Check Wavename Length.vi"
File 58="user.lib/LevyLab/LV-Data/LV-Data.ITX/private/Commands to ITX.vi"
File 59="user.lib/LevyLab/LV-Data/LV-Data.ITX/private/Create Folder Index.vi"
File 60="user.lib/LevyLab/LV-Data/LV-Data.ITX/private/Format Wavename.vi"
File 61="user.lib/LevyLab/LV-Data/LV-Data.ITX/private/ITX.Variant to String.vi"
File 62="user.lib/LevyLab/LV-Data/LV-Data.ITX/private/Notes to ITX.vi"
File 63="user.lib/LevyLab/LV-Data/LV-Data.ITX/private/Parse Comments and Commands.vi"
File 64="user.lib/LevyLab/LV-Data/LV-Data.ITX/private/Parse ITX String.vi"
File 65="user.lib/LevyLab/LV-Data/LV-Data.ITX/private/Read Folder Index.vi"
File 66="user.lib/LevyLab/LV-Data/LV-Data.ITX/private/Variant to ITX Wave.vi"
File 67="user.lib/LevyLab/LV-Data/LV-Data.ITX/Overrides/Read.vi"
File 68="user.lib/LevyLab/LV-Data/LV-Data.ITX/Overrides/Write.vi"
File 69="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/Format ITX Graph.vi"
File 70="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/ITX Commands.lvclass"
File 71="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/typedefs/grid--enum.ctl"
File 72="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/typedefs/Label--cluster.ctl"
File 73="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/typedefs/Log--cluster.ctl"
File 74="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/typedefs/log--enum.ctl"
File 75="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/typedefs/textbox_anchorcolumn--enum.ctl"
File 76="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/typedefs/textbox_anchorrow--enum.ctl"
File 77="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/private/Commands to ITX.vi"
File 78="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/2D Macro.vi"
File 79="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/2D w X&Y Macro.vi"
File 80="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/Append Command.vi"
File 81="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/AppendImage.vi"
File 82="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/AppendToGraph.vi"
File 83="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/Clear Commands.vi"
File 84="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/ColorScale.vi"
File 85="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/Generate Command String.vi"
File 86="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/KillWaves.vi"
File 87="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/Label.vi"
File 88="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/Legend.vi"
File 89="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/ModifyGraph axThick.vi"
File 90="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/ModifyGraph grid.vi"
File 91="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/ModifyGraph height.vi"
File 92="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/ModifyGraph Log.vi"
File 93="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/ModifyGraph mirror.vi"
File 94="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/ModifyGraph prescaleExp.vi"
File 95="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/ModifyGraph rgb.vi"
File 96="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/ModifyGraph width.vi"
File 97="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/ModifyImage ctab.vi"
File 98="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/SetScale.vi"
File 99="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/Textbox.vi"
File 100="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/XY Macro.vi"
File 101="user.lib/LevyLab/LV-Data/LV-Data.ITX/ITX Commands/API/XY2 Macro.vi"
File 102="user.lib/LevyLab/LV-Data/LV-Data.ITX/Graph/Configure XY Graph.vi"
File 103="user.lib/LevyLab/LV-Data/LV-Data.ITX/Graph/Intensity Graph to Igor Graph.vi"
File 104="user.lib/LevyLab/LV-Data/LV-Data.ITX/Graph/LV Graph to Igor UI.vi"
File 105="user.lib/LevyLab/LV-Data/LV-Data.ITX/Graph/LV Graphs to Igor Example.vi"
File 106="user.lib/LevyLab/LV-Data/LV-Data.ITX/Graph/XY Graph to Igor Graph.vi"
File 107="user.lib/LevyLab/LV-Data/LV-Data.ITX/API/Read ITX.vi"
File 108="user.lib/LevyLab/LV-Data/LV-Data.ITX/API/Write ITX.vim"
File 109="user.lib/LevyLab/LV-Data/LV-Data.DAT/LV-Data.DAT.lvclass"
File 110="user.lib/LevyLab/LV-Data/LV-Data.DAT/Read DAT.vi"
File 111="user.lib/LevyLab/LV-Data/LV-Data.DAT/Write DAT (1D).vi"
File 112="user.lib/LevyLab/LV-Data/LV-Data.DAT/Write DAT (2D).vi"
File 113="user.lib/LevyLab/LV-Data/LV-Data.DAT/Write DAT.vi"
File 114="user.lib/LevyLab/LV-Data/LV-Data.DAT/private/Parse DAT String.vi"
File 115="user.lib/LevyLab/LV-Data/LV-Data.DAT/Overrides/Read.vi"
File 116="user.lib/LevyLab/LV-Data/LV-Data.DAT/Overrides/Write.vi"
File 117="user.lib/LevyLab/LV-Data/LV-Data.AWS CLI/LV-Data.AWS CLI.lvclass"
File 118="user.lib/LevyLab/LV-Data/LV-Data.AWS CLI/Typedefs/AWS CLI.Bucket.ctl"
File 119="user.lib/LevyLab/LV-Data/LV-Data.AWS CLI/private/AWS Execute CMD.vi"
File 120="user.lib/LevyLab/LV-Data/LV-Data.AWS CLI/private/AWS Handle Error.vi"
File 121="user.lib/LevyLab/LV-Data/LV-Data.AWS CLI/private/AWS Process Command.vi"
File 122="user.lib/LevyLab/LV-Data/LV-Data.AWS CLI/private/AWS Process Output.vi"
File 123="user.lib/LevyLab/LV-Data/LV-Data.AWS CLI/private/Remove leading and trailing slashes.vi"
File 124="user.lib/LevyLab/LV-Data/LV-Data.AWS CLI/API/S3/AWS S3 ls buckets.vi"
File 125="user.lib/LevyLab/LV-Data/LV-Data.AWS CLI/API/S3/AWS S3 ls.vi"
File 126="user.lib/LevyLab/LV-Data/LV-Data/Data Read.vi"
File 127="user.lib/LevyLab/LV-Data/LV-Data/Data Retrieve GUI.vi"
File 128="user.lib/LevyLab/LV-Data/LV-Data/Data Write.vi"
File 129="user.lib/LevyLab/LV-Data/LV-Data/LV-Data.lvclass"
File 130="user.lib/LevyLab/LV-Data/LV-Data/Typedefs/Dictionary--cluster.ctl"
File 131="user.lib/LevyLab/LV-Data/LV-Data/Typedefs/File Type--enum.ctl"
File 132="user.lib/LevyLab/LV-Data/LV-Data/Typedefs/Map Variant--map.ctl"
File 133="user.lib/LevyLab/LV-Data/LV-Data/Typedefs/Operation--enum.ctl"
File 134="user.lib/LevyLab/LV-Data/LV-Data/Protected/Add Letter.vi"
File 135="user.lib/LevyLab/LV-Data/LV-Data/Protected/Replace Period with Underscore.vi"
File 136="user.lib/LevyLab/LV-Data/LV-Data/Protected/Replace Space with Empty.vi"
File 137="user.lib/LevyLab/LV-Data/LV-Data/Private/Format Path and Filename.vi"
File 138="user.lib/LevyLab/LV-Data/LV-Data/Framework (For Override)/Close.vi"
File 139="user.lib/LevyLab/LV-Data/LV-Data/Framework (For Override)/Create.vi"
File 140="user.lib/LevyLab/LV-Data/LV-Data/Framework (For Override)/Open.vi"
File 141="user.lib/LevyLab/LV-Data/LV-Data/Framework (For Override)/Read.vi"
File 142="user.lib/LevyLab/LV-Data/LV-Data/Framework (For Override)/Write.vi"
File 143="user.lib/LevyLab/LV-Data/LV-Data/API/Append to Data (Dictionary).vi"
File 144="user.lib/LevyLab/LV-Data/LV-Data/API/Convert Dictionary to Map.vim"
File 145="user.lib/LevyLab/LV-Data/LV-Data/API/Get Map Value.vim"
File 146="user.lib/LevyLab/LV-Data/LV-Data/API/Insert Into Map.vim"
File 147="user.lib/LevyLab/LV-Data/LV-Data/API/List Map Keys and Values.vim"
File 148="user.lib/LevyLab/LV-Data/LV-Data/API/Map to Dictionary.vi"
File 149="user.lib/LevyLab/LV-Data/LV-Data/API/Populate Ring Text [].vi"
File 150="user.lib/LevyLab/LV-Data/LV-Data/API/Read Append Index.vi"
File 151="user.lib/LevyLab/LV-Data/LV-Data/API/Read Append.vi"
File 152="user.lib/LevyLab/LV-Data/LV-Data/API/Read Data (Dictionary).vi"
File 153="user.lib/LevyLab/LV-Data/LV-Data/API/Read Igor Commands.vi"
File 154="user.lib/LevyLab/LV-Data/LV-Data/API/Read Notes.vi"
File 155="user.lib/LevyLab/LV-Data/LV-Data/API/Read Operation.vi"
File 156="user.lib/LevyLab/LV-Data/LV-Data/API/Read Path.vi"
File 157="user.lib/LevyLab/LV-Data/LV-Data/API/Read Wavenames.vi"
File 158="user.lib/LevyLab/LV-Data/LV-Data/API/Remove From Map.vim"
File 159="user.lib/LevyLab/LV-Data/LV-Data/API/Variant to DBL Array.vi"
File 160="user.lib/LevyLab/LV-Data/LV-Data/API/Variant to Dictionary.vi"
File 161="user.lib/LevyLab/LV-Data/LV-Data/API/Variant to String.vi"
File 162="user.lib/LevyLab/LV-Data/LV-Data/API/Write Append.vi"
File 163="user.lib/LevyLab/LV-Data/LV-Data/API/Write Data (Dictionary).vi"
File 164="user.lib/LevyLab/LV-Data/LV-Data/API/Write Igor Commands.vi"
File 165="user.lib/LevyLab/LV-Data/LV-Data/API/Write Notes.vi"
File 166="user.lib/LevyLab/LV-Data/LV-Data/API/Write Path.vi"
File 167="user.lib/LevyLab/LV-Data/LV-Data/API/XY-Data to Dictionary (Multiple).vi"
File 168="user.lib/LevyLab/LV-Data/LV-Data/API/XY-Data to Dictionary (single).vi"
File 169="user.lib/LevyLab/LV-Data/LV-Data/API/XY-Data to Dictionary.vi"
File 170="user.lib/LevyLab/LV-Data/LV-Data/API/XY-Data to Map.vim"
File 171="user.lib/LevyLab/LV-Data/Examples/DAT Example.vi"
File 172="user.lib/LevyLab/LV-Data/Examples/ITX Example.vi"
File 173="user.lib/LevyLab/LV-Data/Examples/ITX2 Example.vi"
File 174="user.lib/LevyLab/LV-Data/Examples/TDMS Read Example.vi"
File 175="user.lib/LevyLab/LV-Data/Examples/Tree.vi"


[File Group 1]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="Always"
Num Files=29
File 0="_functions_levylab_lib_lvtoitx_1.mnu"
File 1="_functions_levylab_lib_lvtoitx_10.mnu"
File 2="_functions_levylab_lib_lvtoitx_11.mnu"
File 3="_functions_levylab_lib_lvtoitx_12.mnu"
File 4="_functions_levylab_lib_lvtoitx_13.mnu"
File 5="_functions_levylab_lib_lvtoitx_14.mnu"
File 6="_functions_levylab_lib_lvtoitx_15.mnu"
File 7="_functions_levylab_lib_lvtoitx_16.mnu"
File 8="_functions_levylab_lib_lvtoitx_17.mnu"
File 9="_functions_levylab_lib_lvtoitx_18.mnu"
File 10="_functions_levylab_lib_lvtoitx_19.mnu"
File 11="_functions_levylab_lib_lvtoitx_2.mnu"
File 12="_functions_levylab_lib_lvtoitx_20.mnu"
File 13="_functions_levylab_lib_lvtoitx_21.mnu"
File 14="_functions_levylab_lib_lvtoitx_22.mnu"
File 15="_functions_levylab_lib_lvtoitx_23.mnu"
File 16="_functions_levylab_lib_lvtoitx_24.mnu"
File 17="_functions_levylab_lib_lvtoitx_25.mnu"
File 18="_functions_levylab_lib_lvtoitx_26.mnu"
File 19="_functions_levylab_lib_lvtoitx_27.mnu"
File 20="_functions_levylab_lib_lvtoitx_28.mnu"
File 21="_functions_levylab_lib_lvtoitx_3.mnu"
File 22="_functions_levylab_lib_lvtoitx_4.mnu"
File 23="_functions_levylab_lib_lvtoitx_5.mnu"
File 24="_functions_levylab_lib_lvtoitx_6.mnu"
File 25="_functions_levylab_lib_lvtoitx_7.mnu"
File 26="_functions_levylab_lib_lvtoitx_8.mnu"
File 27="_functions_levylab_lib_lvtoitx_9.mnu"
File 28="functions_levylab_lib_lvtoitx.mnu"


[File Group 2]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="If Newer"
Num Files=1
File 0="dir.mnu"
