[Package]
Name="3t_lib_pythonview"
Version="1.0.1.2"
Release=""
ID=25346565420d3312d7aaef429977c097
File Format="vip"
Format Version="2014"
Display Name="PythonVIEW"


[Description]
Description="PythonVIEW is a software library designed to connect LabVIEW and Python. It enables LabVIEW applications to execute Python scripts but also provides LabVIEW functionality to Python scripts in standard way."
Summary="PythonVIEW is a software library designed to connect LabVIEW and Python. It enables LabVIEW applications to execute Python scripts but also provides LabVIEW functionality to Python scripts in standard way."
License=""
Copyright="Copyright (c) 2017, 3T"
Distribution=""
Vendor="3T"
URL="https://3t.nl/en/pythonview/"
Packager="3T & LevyLab"
Demo="FALSE"
Release Notes="PythonVIEW v1.8\0A\0A- disable check for python installation"
System Package="FALSE"
Sub Package="FALSE"
License Agreement="FALSE"


[LabVIEW]
close labview before install="FALSE"
restart labview after install="FALSE"
skip mass compile after install="FALSE"


[Platform]
Exclusive_LabVIEW_Version="LabVIEW>=16.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="Windows NT"


[Script VIs]
PreInstall=""
PostInstall=""
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires=""
Conflicts=""


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="3"
Sub-Packages=""
Namespaces=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=144
File 0="vi.lib/3T/PythonVIEW/Main.vi"
File 1="vi.lib/3T/PythonVIEW/PythonViewDemo.lvproj"
File 2="vi.lib/3T/PythonVIEW/PythonView/LvLibClass.py"
File 3="vi.lib/3T/PythonVIEW/PythonView/PythonCallEditor.vi"
File 4="vi.lib/3T/PythonVIEW/PythonView/PythonConsole.vi"
File 5="vi.lib/3T/PythonVIEW/PythonView/ScriptLoader.py"
File 6="vi.lib/3T/PythonVIEW/PythonView/TestGlobal.vi"
File 7="vi.lib/3T/PythonVIEW/PythonView/TestScript.py"
File 8="vi.lib/3T/PythonVIEW/PythonView/TestScriptCircle.py"
File 9="vi.lib/3T/PythonVIEW/PythonView/TestScriptCircleFast.py"
File 10="vi.lib/3T/PythonVIEW/PythonView/SubScripts/DrawCircle.py"
File 11="vi.lib/3T/PythonVIEW/PythonView/SubScripts/__pycache__/DrawCircle.cpython-34.pyc"
File 12="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/AtBreakpoint.vi"
File 13="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/AutoNext.vi"
File 14="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/AutoStep.vi"
File 15="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/CallStackElementTypeDef.ctl"
File 16="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/CallStackTypeDef.ctl"
File 17="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/ClearReceiveBuffer.vi"
File 18="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/Connect.vi"
File 19="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/Continue.vi"
File 20="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/Deinit.vi"
File 21="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/Disconnect.vi"
File 22="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/Exit.vi"
File 23="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/GetCallStackFromWhereResultString.vi"
File 24="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/GetCurrentPosFromCallStack.vi"
File 25="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/GetFirstLineFromReceiveBuffer.vi"
File 26="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/GuiElements.ctl"
File 27="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/ImportTestScript.vi"
File 28="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/Init.vi"
File 29="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/InMainScriptDir.vi"
File 30="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/JumpToLineNumber.vi"
File 31="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/LogRpdbData.vi"
File 32="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/MoveToScriptStart.vi"
File 33="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/Next.vi"
File 34="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/PythonErrorReceived.vi"
File 35="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/Read Breakpoints.vi"
File 36="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/Read GuiElements.vi"
File 37="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/Read PythonStatusRef.vi"
File 38="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/RetrieveData.vi"
File 39="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/Return.vi"
File 40="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/Rpdb.lvclass"
File 41="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/SearchInBuffer.vi"
File 42="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/SendData.vi"
File 43="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/Step.vi"
File 44="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/ToggleBreakpoint.vi"
File 45="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/UpdateCallStack.vi"
File 46="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/UpdateScriptGuiPosition.vi"
File 47="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/WaitForData.vi"
File 48="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/WaitForPrompt.vi"
File 49="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/WaitForPythonToFinish.vi"
File 50="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/Where.vi"
File 51="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/Write Breakpoints.vi"
File 52="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/Write GuiElements.vi"
File 53="vi.lib/3T/PythonVIEW/PythonView/Classes/Rpdb/Write PythonStatusRef.vi"
File 54="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/AutoScriptCmdTypeDef.ctl"
File 55="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/AutoScriptStepper.vi"
File 56="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/CalcScriptScrollPos.vi"
File 57="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/ClassOverview.vi"
File 58="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/ClearGuiElements.vi"
File 59="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/ConnectGuiElements.vi"
File 60="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/Deinit.vi"
File 61="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/GetVersionLabel.vi"
File 62="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/GuiElements.ctl"
File 63="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/Init.vi"
File 64="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/InterruptCommand.ctl"
File 65="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/IsScriptRunning.vi"
File 66="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/LoadScript.vi"
File 67="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/PythonView.lvclass"
File 68="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/PythonViewStateTypeDef.ctl"
File 69="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/PythonViewStatus.ctl"
File 70="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/PythonViewUserEventTypeDef.ctl"
File 71="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/Read Breakpoints.vi"
File 72="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/RpdbCustomCommand.vi"
File 73="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/ScriptAbort.vi"
File 74="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/ScriptBuildMenu.vi"
File 75="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/ScriptContinue.vi"
File 76="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/ScriptCtrlStates.ctl"
File 77="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/ScriptCtrlStatus.ctl"
File 78="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/ScriptExecutionStopMode.ctl"
File 79="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/ScriptExit.vi"
File 80="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/ScriptJumpToLineNumber.vi"
File 81="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/ScriptNext.vi"
File 82="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/ScriptPause.vi"
File 83="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/ScriptStep.vi"
File 84="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/SendCmdToAutoScriptStepper.vi"
File 85="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/SetEnableMultipleControls.vi"
File 86="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/SetGuiElementBooleanText.vi"
File 87="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/SetGuiElementScriptBoxToDefault.vi"
File 88="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/SetGuiStateScriptAborted.vi"
File 89="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/SetGuiStateScriptDefault.vi"
File 90="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/SetGuiStateScriptDone.vi"
File 91="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/SetGuiStateScriptLoaded.vi"
File 92="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/SetGuiStateScriptPaused.vi"
File 93="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/SetGuiStateScriptRunning.vi"
File 94="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/ToggleBreakpoint.vi"
File 95="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/UpdateScrollPosition.vi"
File 96="vi.lib/3T/PythonVIEW/PythonView/Classes/PythonVIEW/Write Breakpoints.vi"
File 97="vi.lib/3T/PythonVIEW/PythonView/Classes/Python/CheckForBdbQuit.vi"
File 98="vi.lib/3T/PythonVIEW/PythonView/Classes/Python/Deinit.vi"
File 99="vi.lib/3T/PythonVIEW/PythonView/Classes/Python/ExtractTraceBackInfo.vi"
File 100="vi.lib/3T/PythonVIEW/PythonView/Classes/Python/GetPythonExePath.vi"
File 101="vi.lib/3T/PythonVIEW/PythonView/Classes/Python/GetScriptResults.vi"
File 102="vi.lib/3T/PythonVIEW/PythonView/Classes/Python/Init.vi"
File 103="vi.lib/3T/PythonVIEW/PythonView/Classes/Python/IsPythonActive.vi"
File 104="vi.lib/3T/PythonVIEW/PythonView/Classes/Python/PyhtonStatus.ctl"
File 105="vi.lib/3T/PythonVIEW/PythonView/Classes/Python/Python.lvclass"
File 106="vi.lib/3T/PythonVIEW/PythonView/Classes/Python/Read LauncherPath.vi"
File 107="vi.lib/3T/PythonVIEW/PythonView/Classes/Python/RunScript.vi"
File 108="vi.lib/3T/PythonVIEW/PythonView/Classes/Python/RunScriptThreadLauncher.vi"
File 109="vi.lib/3T/PythonVIEW/PythonView/Classes/Python/ShowError.vi"
File 110="vi.lib/3T/PythonVIEW/PythonView/Classes/Python/TestMethod.vi"
File 111="vi.lib/3T/PythonVIEW/PythonView/Classes/Python/Write LauncherPath.vi"
File 112="vi.lib/3T/PythonVIEW/PythonView/Classes/PyServerEnvironment/ColorStringToColor.vi"
File 113="vi.lib/3T/PythonVIEW/PythonView/Classes/PyServerEnvironment/PyServerEnvironment.lvclass"
File 114="vi.lib/3T/PythonVIEW/PythonView/Classes/PyServerEnvironment/Read Canvas.vi"
File 115="vi.lib/3T/PythonVIEW/PythonView/Classes/PyServerEnvironment/Write Canvas.vi"
File 116="vi.lib/3T/PythonVIEW/PythonView/Classes/PyCmds/PyCmdWait/Execute.vi"
File 117="vi.lib/3T/PythonVIEW/PythonView/Classes/PyCmds/PyCmdWait/ParseParms.vi"
File 118="vi.lib/3T/PythonVIEW/PythonView/Classes/PyCmds/PyCmdWait/PyCmdWait.lvclass"
File 119="vi.lib/3T/PythonVIEW/PythonView/Classes/PyCmds/PyCmdWait/Read Duration(ms).vi"
File 120="vi.lib/3T/PythonVIEW/PythonView/Classes/PyCmds/PyCmdDrawRect/Execute.vi"
File 121="vi.lib/3T/PythonVIEW/PythonView/Classes/PyCmds/PyCmdDrawRect/ParseParms.vi"
File 122="vi.lib/3T/PythonVIEW/PythonView/Classes/PyCmds/PyCmdDrawRect/PyCmdDrawRect.lvclass"
File 123="vi.lib/3T/PythonVIEW/PythonView/Classes/PyCmds/PyCmdDrawLine/Execute.vi"
File 124="vi.lib/3T/PythonVIEW/PythonView/Classes/PyCmds/PyCmdDrawLine/ParseParms.vi"
File 125="vi.lib/3T/PythonVIEW/PythonView/Classes/PyCmds/PyCmdDrawLine/PyCmdDrawLine.lvclass"
File 126="vi.lib/3T/PythonVIEW/PythonView/Classes/PyCmds/PyCmdBase/Execute.vi"
File 127="vi.lib/3T/PythonVIEW/PythonView/Classes/PyCmds/PyCmdBase/ParseParms.vi"
File 128="vi.lib/3T/PythonVIEW/PythonView/Classes/PyCmds/PyCmdBase/PyCmdBase.lvclass"
File 129="vi.lib/3T/PythonVIEW/PythonView/Classes/PyCmds/PyCmdBase/Read Parms.vi"
File 130="vi.lib/3T/PythonVIEW/PythonView/Classes/PyCmds/PyCmdBase/Read PyServerEnvironment.vi"
File 131="vi.lib/3T/PythonVIEW/PythonView/Classes/PyCmds/PyCmdBase/Read TCP Connection.vi"
File 132="vi.lib/3T/PythonVIEW/PythonView/Classes/PyCmds/PyCmdBase/Write Parms.vi"
File 133="vi.lib/3T/PythonVIEW/PythonView/Classes/PyCmds/PyCmdBase/Write PyServerEnvironment.vi"
File 134="vi.lib/3T/PythonVIEW/PythonView/Classes/PyCmds/PyCmdBase/Write TCP Connection.vi"
File 135="vi.lib/3T/PythonVIEW/PythonView/Classes/BreakPointList/AtBreakpoint.vi"
File 136="vi.lib/3T/PythonVIEW/PythonView/Classes/BreakPointList/BreakpointInfo.ctl"
File 137="vi.lib/3T/PythonVIEW/PythonView/Classes/BreakPointList/BreakpointList.lvclass"
File 138="vi.lib/3T/PythonVIEW/PythonView/Classes/BreakPointList/ClearBreakpoints.vi"
File 139="vi.lib/3T/PythonVIEW/PythonView/Classes/BreakPointList/GetAllBreakpointsInFile.vi"
File 140="vi.lib/3T/PythonVIEW/PythonView/Classes/BreakPointList/ToggleBreakpoint.vi"
File 141="vi.lib/3T/PythonVIEW/PythonView/__pycache__/LvLibClass.cpython-34.pyc"
File 142="vi.lib/3T/PythonVIEW/PythonView/__pycache__/TestScriptCircle.cpython-34.pyc"
File 143="vi.lib/3T/PythonVIEW/PythonView/__pycache__/TestScriptCircleFast.cpython-34.pyc"


[File Group 1]
Target Dir="<menus>/Categories"
Replace Mode="Always"
Num Files=13
File 0="_functions_3t_lib_pythonview_1.mnu"
File 1="_functions_3t_lib_pythonview_10.mnu"
File 2="_functions_3t_lib_pythonview_11.mnu"
File 3="_functions_3t_lib_pythonview_12.mnu"
File 4="_functions_3t_lib_pythonview_2.mnu"
File 5="_functions_3t_lib_pythonview_3.mnu"
File 6="_functions_3t_lib_pythonview_4.mnu"
File 7="_functions_3t_lib_pythonview_5.mnu"
File 8="_functions_3t_lib_pythonview_6.mnu"
File 9="_functions_3t_lib_pythonview_7.mnu"
File 10="_functions_3t_lib_pythonview_8.mnu"
File 11="_functions_3t_lib_pythonview_9.mnu"
File 12="functions_3T_lib_PythonVIEW.mnu"


[File Group 2]
Target Dir="<menus>/Controls"
Replace Mode="Always"
Num Files=7
File 0="_controls_3t_lib_pythonview_1.mnu"
File 1="_controls_3t_lib_pythonview_2.mnu"
File 2="_controls_3t_lib_pythonview_3.mnu"
File 3="_controls_3t_lib_pythonview_4.mnu"
File 4="_controls_3t_lib_pythonview_5.mnu"
File 5="_controls_3t_lib_pythonview_6.mnu"
File 6="controls_3T_lib_PythonVIEW.mnu"
