[Package]
Name="levylab_lib_general_afm_lithography"
Version="8.6.0.1"
Release=""
ID=b3cf17450d0470e23658965c41321643
File Format="vip"
Format Version="2017"
Display Name="General AFM Lithography"


[Description]
Description="General AFM Lithography software used by the LevyLab research group at the University of Pittsburgh."
Summary=""
License="BSD-3"
Copyright="Copyright (c) 2020, LevyLab"
Distribution=""
Vendor="LevyLab"
URL=""
Packager="LevyLab"
Demo="FALSE"
Release Notes="- test build\0A- update package dependencies\0A- this build uses Joe's new AFM Driver Manager and Asylum driver"
System Package="FALSE"
Sub Package="FALSE"
License Agreement="TRUE"


[LabVIEW]
close labview before install="FALSE"
restart labview after install="FALSE"
skip mass compile after install="FALSE"


[Platform]
Exclusive_LabVIEW_Version="LabVIEW>=20.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="ALL"


[Script VIs]
PreInstall="<OS Boot Volume Root>\\user\\patrick\\git\\AFM-Lithography\\build support\\Pre-Install Custom Action.vi"
PostInstall=""
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires="jki_lib_state_machine>=2018.0.7.45,jki_statemachineobjects>=1.3.0.56,lava_lib_ui_tools>=1.4.1.74,levylab_lib_asylum_afm_api>=1.0.0.1,levylab_lib_relay_box>=1.1.0.8,mgi_lib_application_control>=1.1.1.10,mgi_lib_cluster>=1.1.0.1,mgi_lib_error_handling>=1.1.1.3,mgi_lib_error_reporter>=1.0.2.5,mgi_lib_file>=1.1.0.4,mgi_lib_picture_&_image>=1.0.2.1,mgi_lib_read_write_anything>=2.1.4.4,mgi_lib_string>=1.1.1.5,oglib_appcontrol>=4.1.0.7,oglib_array>=4.1.1.14,oglib_error>=4.2.0.23,oglib_file>=4.0.1.22,oglib_lvdata>=4.2.0.21,oglib_string>=4.1.0.12,oglib_time>=4.0.1.3,oglib_variantconfig>=4.0.0.5"
Conflicts=""


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="3"
Sub-Packages=""
Namespaces=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=231
File 0="user.lib/Levylab/General AFM Lithography/AFM_Lithography.lvproj"
File 1="user.lib/Levylab/General AFM Lithography/AFM_Lithography.vi"
File 2="user.lib/Levylab/General AFM Lithography/subVIs/Global Variables.vi"
File 3="user.lib/Levylab/General AFM Lithography/subVIs/typedefs/Funnel Properties - cluster.ctl"
File 4="user.lib/Levylab/General AFM Lithography/subVIs/typedefs/Parsed Funnel - Cluster.ctl"
File 5="user.lib/Levylab/General AFM Lithography/subVIs/typedefs/Parsed Path - Cluster.ctl"
File 6="user.lib/Levylab/General AFM Lithography/subVIs/typedefs/Parsed Rect - Cluster.ctl"
File 7="user.lib/Levylab/General AFM Lithography/subVIs/typedefs/Path Properties - cluster.ctl"
File 8="user.lib/Levylab/General AFM Lithography/subVIs/typedefs/Rectangle Properties - cluster.ctl"
File 9="user.lib/Levylab/General AFM Lithography/subVIs/typedefs/Schedule - enum.ctl"
File 10="user.lib/Levylab/General AFM Lithography/subVIs/typedefs/Signal Type - enum.ctl"
File 11="user.lib/Levylab/General AFM Lithography/subVIs/typedefs/Voltage - cluster.ctl"
File 12="user.lib/Levylab/General AFM Lithography/subVIs/typedefs/Schedule Types/Schedule--Constant.ctl"
File 13="user.lib/Levylab/General AFM Lithography/subVIs/typedefs/Schedule Types/Schedule--Formula.ctl"
File 14="user.lib/Levylab/General AFM Lithography/subVIs/typedefs/Schedule Types/Schedule--Function Generator.ctl"
File 15="user.lib/Levylab/General AFM Lithography/subVIs/typedefs/Schedule Types/Schedule--Ramp.ctl"
File 16="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Bezier.vi"
File 17="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Calculate Intersection.vi"
File 18="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Estimated Time Required.vi"
File 19="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Funnel Path Points.vi"
File 20="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/funnels to Commands.vi"
File 21="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Get Rectangle Corners.vi"
File 22="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Interpolate Points (Distance).vi"
File 23="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Interpolate Points (Number).vi"
File 24="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Interpolate Signal (Number).vi"
File 25="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Interpolator_Yuhe.vi"
File 26="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Lithographify.vi"
File 27="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Lithographify_funnel&rec.vi"
File 28="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Lithographify_funnel_rec.vi"
File 29="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Order Patterns.vi"
File 30="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Path Apply Inkscape Ratio.vi"
File 31="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Path Points.vi"
File 32="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Paths to Commands.vi"
File 33="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Rectangle Apply Inkscape Ratio.vi"
File 34="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Rectangles to Commands.vi"
File 35="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Relative Coordinates.vi"
File 36="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Signal Generator.vi"
File 37="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Toolpath.vi"
File 38="user.lib/Levylab/General AFM Lithography/subVIs/toolpath/Transform Point.vi"
File 39="user.lib/Levylab/General AFM Lithography/subVIs/subpanel/Abort If Not Refnum.vi"
File 40="user.lib/Levylab/General AFM Lithography/subVIs/subpanel/CheckVariantAttributes.vi"
File 41="user.lib/Levylab/General AFM Lithography/subVIs/subpanel/Close Subpanel.vi"
File 42="user.lib/Levylab/General AFM Lithography/subVIs/subpanel/Dynamic Generation of Formula for Vtip.vi"
File 43="user.lib/Levylab/General AFM Lithography/subVIs/subpanel/Function Generator - var 2 pulse.vi"
File 44="user.lib/Levylab/General AFM Lithography/subVIs/subpanel/Function Generator--OLD.vi"
File 45="user.lib/Levylab/General AFM Lithography/subVIs/subpanel/Function Generator-Yuhe version.vi"
File 46="user.lib/Levylab/General AFM Lithography/subVIs/subpanel/Function Generator.vi"
File 47="user.lib/Levylab/General AFM Lithography/subVIs/subpanel/Funnel Edit.vi"
File 48="user.lib/Levylab/General AFM Lithography/subVIs/subpanel/Get Selected Pattern.vi"
File 49="user.lib/Levylab/General AFM Lithography/subVIs/subpanel/Load AFM Subpanel.vi"
File 50="user.lib/Levylab/General AFM Lithography/subVIs/subpanel/Path Edit.vi"
File 51="user.lib/Levylab/General AFM Lithography/subVIs/subpanel/Ramp.vi"
File 52="user.lib/Levylab/General AFM Lithography/subVIs/subpanel/Rect Edit.vi"
File 53="user.lib/Levylab/General AFM Lithography/subVIs/subpanel/Set Driver Controls.vi"
File 54="user.lib/Levylab/General AFM Lithography/subVIs/parsing/Check First Character Type.vi"
File 55="user.lib/Levylab/General AFM Lithography/subVIs/parsing/Discard One Character.vi"
File 56="user.lib/Levylab/General AFM Lithography/subVIs/parsing/Extract Fill Stroke From Style.vi"
File 57="user.lib/Levylab/General AFM Lithography/subVIs/parsing/Extract Number From Quotes.vi"
File 58="user.lib/Levylab/General AFM Lithography/subVIs/parsing/Get Matrix from Transform_Tran.vi"
File 59="user.lib/Levylab/General AFM Lithography/subVIs/parsing/Get Path Commands.vi"
File 60="user.lib/Levylab/General AFM Lithography/subVIs/parsing/Get SVG Image Size.vi"
File 61="user.lib/Levylab/General AFM Lithography/subVIs/parsing/Path Is Funnel.vi"
File 62="user.lib/Levylab/General AFM Lithography/subVIs/parsing/Paths Sub-Parser.vi"
File 63="user.lib/Levylab/General AFM Lithography/subVIs/parsing/Rectangle Sub-Parser.vi"
File 64="user.lib/Levylab/General AFM Lithography/subVIs/parsing/Set Inkscape Ratio.vi"
File 65="user.lib/Levylab/General AFM Lithography/subVIs/parsing/SVG Parser.vi"
File 66="user.lib/Levylab/General AFM Lithography/subVIs/parsing/XPath File Sub-Parser.vi"
File 67="user.lib/Levylab/General AFM Lithography/subVIs/parsing/XPath String Sub-Parser.vi"
File 68="user.lib/Levylab/General AFM Lithography/subVIs/parsing/XPath String Sub-Parser_Tran.vi"
File 69="user.lib/Levylab/General AFM Lithography/subVIs/image/Adjust Coordinate.vi"
File 70="user.lib/Levylab/General AFM Lithography/subVIs/image/Background.vi"
File 71="user.lib/Levylab/General AFM Lithography/subVIs/image/Convert IMAQ to LV Image.vi"
File 72="user.lib/Levylab/General AFM Lithography/subVIs/image/Double to RGB Image.vi"
File 73="user.lib/Levylab/General AFM Lithography/subVIs/image/Draw Lines First.vi"
File 74="user.lib/Levylab/General AFM Lithography/subVIs/image/Get Voltage RGB.vi"
File 75="user.lib/Levylab/General AFM Lithography/subVIs/image/Image Generator.vi"
File 76="user.lib/Levylab/General AFM Lithography/subVIs/image/Load IBW File.vi"
File 77="user.lib/Levylab/General AFM Lithography/subVIs/image/SGL Wordswap.vi"
File 78="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Template/AFM_Name_Driver.vit"
File 79="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.Abort.vi"
File 80="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.CloseVIReferences.vi"
File 81="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.CreateAbort.vi"
File 82="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.CreateEvents.vi"
File 83="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.CreatePublicEvents.vi"
File 84="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.CreateWatchdogEvents.vi"
File 85="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.DestroyAbort.vi"
File 86="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.DestroyEvents.vi"
File 87="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.DestroyPublicEvents.vi"
File 88="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.GetPublicEvents.vi"
File 89="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.Initialize.vi"
File 90="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.InitializeDrivers.vi"
File 91="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.InitializeWatchdog.vi"
File 92="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.InsertActiveIntoSubpanel.vi"
File 93="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.KillZombieProcesses.vi"
File 94="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.lvclass"
File 95="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.OnLithographyFinish.vi"
File 96="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.PublicEvents.ctl"
File 97="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.ReadActiveDriver.vi"
File 98="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.SendAbort.vi"
File 99="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.SendBackgroundImage.vi"
File 100="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.SendLithography.vi"
File 101="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.SendRun.vi"
File 102="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.SendStop.vi"
File 103="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.SetActive.vi"
File 104="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.Shutdown.vi"
File 105="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.StopAllDrivers.vi"
File 106="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.StopWatchdog.vi"
File 107="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/AFM_Driver_Manager.Watchdog.vi"
File 108="user.lib/Levylab/General AFM Lithography/subVIs/AFM API/AFM_Driver_Manager/TestAFM_Driver_Manager.vi"
File 109="user.lib/Levylab/General AFM Lithography/Controls/Configuration.ctl"
File 110="user.lib/Levylab/General AFM Lithography/Controls/SmallFlat2.0Enum.ctl"
File 111="user.lib/Levylab/General AFM Lithography/Controls/SmallFlat2.0Numeric.ctl"
File 112="user.lib/Levylab/General AFM Lithography/Controls/SmallFlat2.0Ring.ctl"
File 113="user.lib/Levylab/General AFM Lithography/AFMs/Simulation/Build Graphs.vi"
File 114="user.lib/Levylab/General AFM Lithography/AFMs/Simulation/Simulation Driver.vi"
File 115="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/MFP3D_Lucy Acquired Data.vi"
File 116="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/MFP3D_Lucy Driver.vi"
File 117="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/Tip.wrl"
File 118="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/abortDriver_Feng_MFP3D_Lucy.vi"
File 119="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/Create TDMS_MFP3D_Lucy.vi"
File 120="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/Cypher Lithography 2.0_Feng_MFP3D_Lucy.vi"
File 121="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/cypher read value_MFP3D_Lucy.vi"
File 122="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/Cypher XY LVDT Parameters_MFP3D_Lucy.vi"
File 123="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/Display wave_MFP3D_Lucy.vi"
File 124="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/Driver Variables_MFP3D_Lucy.vi"
File 125="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/GCore_MFP3D_Lucy.vi"
File 126="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/getIgorConversion_MFP3D_Lucy.vi"
File 127="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/GMonitor_Fengv2_MFP3D_Lucy.vi"
File 128="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/igor define command_MFP3D_Lucy.vi"
File 129="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/interpolate nodes_MFP3D_Lucy.vi"
File 130="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/Lithography Legacy Convert_MFP3D_Lucy.vi"
File 131="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/Make wave_MFP3D_Lucy.vi"
File 132="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/move to target point_MFP3D_Lucy.vi"
File 133="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/processContactData_MFP3D_Lucy.vi"
File 134="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/Read Scan Size and Offset_MFP3D_Lucy.vi"
File 135="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/Send Igor Command_MFP3D_Lucy.vi"
File 136="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/Send igor command_no return_MFP3D_Lucy.vi"
File 137="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/Set PIDS loop 0_MFP3D_Lucy.vi"
File 138="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/Set PIDS loop 1_MFP3D_Lucy.vi"
File 139="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/Set value_MFP3D_Lucy.vi"
File 140="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/Stop PIS Loops_MFP3D_Lucy.vi"
File 141="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/Tip touchdown_MFP3D_Lucy.vi"
File 142="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/Tip Withdraw_MFP3D_Lucy.vi"
File 143="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/Votlage wave channel setup_MFP3D_Lucy.vi"
File 144="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/X sensor convert V to meter_MFP3D_Lucy.vi"
File 145="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D_Lucy/subVIs/Y sensor convert V to meter_MFP3D_Lucy.vi"
File 146="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/MFP3D Driver.vi"
File 147="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/abortDriver_Feng_MFP3D.vi"
File 148="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/Create TDMS_MFP3D.vi"
File 149="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/Cypher Lithography 2.0_Feng_MFP3D.vi"
File 150="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/cypher read value_MFP3D.vi"
File 151="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/Cypher XY LVDT Parameters_MFP3D.vi"
File 152="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/Display wave_MFP3D.vi"
File 153="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/Driver Variables_MFP3D.vi"
File 154="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/GCore_MFP3D.vi"
File 155="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/getIgorConversion_MFP3D.vi"
File 156="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/GMonitor_Fengv2_MFP3D.vi"
File 157="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/igor define command_MFP3D.vi"
File 158="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/interpolate nodes_MFP3D.vi"
File 159="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/Lithography Legacy Convert_MFP3D.vi"
File 160="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/Make wave_MFP3D.vi"
File 161="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/move to target point_MFP3D.vi"
File 162="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/processContactData_MFP3D.vi"
File 163="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/Read Scan Size and Offset_MFP3D.vi"
File 164="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/Send Igor Command_MFP3D.vi"
File 165="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/Send igor command_no return_MFP3D.vi"
File 166="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/Set PIDS loop 0_MFP3D.vi"
File 167="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/Set PIDS loop 1_MFP3D.vi"
File 168="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/Set value_MFP3D.vi"
File 169="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/Stop PIS Loops_MFP3D.vi"
File 170="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/Tip touchdown_MFP3D.vi"
File 171="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/Tip Withdraw_MFP3D.vi"
File 172="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/Votlage wave channel setup_MFP3D.vi"
File 173="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/X sensor convert V to meter_MFP3D.vi"
File 174="user.lib/Levylab/General AFM Lithography/AFMs/MFP3D/subVIs/Y sensor convert V to meter_MFP3D.vi"
File 175="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/Cypher Driver.vi"
File 176="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/abortDriver_Feng_Cypher.vi"
File 177="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/Create TDMS_Cypher.vi"
File 178="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/Cypher Lithography 2.0_Feng_Cypher.vi"
File 179="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/cypher read value_Cypher.vi"
File 180="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/Cypher XY LVDT Parameters_Cypher.vi"
File 181="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/Display wave_Cypher.vi"
File 182="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/Driver Variables_Cypher.vi"
File 183="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/GCore_Cypher.vi"
File 184="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/getIgorConversion_Cypher.vi"
File 185="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/GMonitor_Fengv2_Cypher.vi"
File 186="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/igor define command_Cypher.vi"
File 187="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/interpolate nodes_Cypher.vi"
File 188="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/Lithography Legacy Convert_Cypher.vi"
File 189="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/Make wave_Cypher.vi"
File 190="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/move to target point_Cypher.vi"
File 191="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/processContactData_Cypher.vi"
File 192="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/Read Scan Size and Offset_Cypher.vi"
File 193="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/Send Igor Command_Cypher.vi"
File 194="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/Send igor command_no return_Cypher.vi"
File 195="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/Set PIDS loop 0_Cypher.vi"
File 196="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/Set PIDS loop 1_Cypher.vi"
File 197="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/Set value_Cypher.vi"
File 198="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/Stop PIS Loops_Cypher.vi"
File 199="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/Tip touchdown_Cypher.vi"
File 200="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/Tip Withdraw_Cypher.vi"
File 201="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/Votlage wave channel setup_Cypher.vi"
File 202="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/X sensor convert V to meter_Cypher.vi"
File 203="user.lib/Levylab/General AFM Lithography/AFMs/Cypher/subVIs/Y sensor convert V to meter_Cypher.vi"
File 204="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/Asylum_Driver.lvproj"
File 205="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/Asylum_Driver.vi"
File 206="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/Todolist.txt"
File 207="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/TypeDefs/Events.ctl"
File 208="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Asylum_Driver_GetLVDTParameters.vi"
File 209="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Asylum_Driver_GetXYSetPoints.vi"
File 210="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Asylum_Driver_GoToInitialPoint.vi"
File 211="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Asylum_Driver_InitializeLithographyObject.vi"
File 212="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Asylum_Driver_Lithography_Convert_Units.vi"
File 213="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Asylum_Driver_LithographyInitialize.vi"
File 214="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Asylum_Driver_LithographyObjectPoints.vi"
File 215="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Asylum_Driver_LithographyObjects.vi"
File 216="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Asylum_Driver_LowerTip.vi"
File 217="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Asylum_Driver_RaiseTip.vi"
File 218="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Asylum_Driver_StartXYPISLoops.vi"
File 219="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Asylum_Driver_TerminateLithographyObject.vi"
File 220="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Asylum_Driver_XYMetersToVoltage.vi"
File 221="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Asylum_Driver_XYMetersToVoltageArray.vi"
File 222="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Asylum_Driver_XYMetersToVoltagePolymorphic.vi"
File 223="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Asylum_Driver_XYVoltageToMeters.vi"
File 224="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Asylum_Interpolation.vi"
File 225="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Asylum_ReadScanSizeAndOffset.vi"
File 226="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Igor_LoadLargeWaveUsingFile.vi"
File 227="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Igor_LoadWaveFromFile.vi"
File 228="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/subVIs/Igor_SaveWaveToFile.vi"
File 229="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/Legacy/Legacy_Load IBW File.vi"
File 230="user.lib/Levylab/General AFM Lithography/AFMs/Asylum_Driver/Legacy/Legacy_SGL Wordswap.vi"


[File Group 1]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="Always"
Num Files=20
File 0="_functions_levylab_lib_general_afm_lithography_1.mnu"
File 1="_functions_levylab_lib_general_afm_lithography_10.mnu"
File 2="_functions_levylab_lib_general_afm_lithography_11.mnu"
File 3="_functions_levylab_lib_general_afm_lithography_12.mnu"
File 4="_functions_levylab_lib_general_afm_lithography_13.mnu"
File 5="_functions_levylab_lib_general_afm_lithography_14.mnu"
File 6="_functions_levylab_lib_general_afm_lithography_15.mnu"
File 7="_functions_levylab_lib_general_afm_lithography_16.mnu"
File 8="_functions_levylab_lib_general_afm_lithography_17.mnu"
File 9="_functions_levylab_lib_general_afm_lithography_18.mnu"
File 10="_functions_levylab_lib_general_afm_lithography_19.mnu"
File 11="_functions_levylab_lib_general_afm_lithography_2.mnu"
File 12="_functions_levylab_lib_general_afm_lithography_3.mnu"
File 13="_functions_levylab_lib_general_afm_lithography_4.mnu"
File 14="_functions_levylab_lib_general_afm_lithography_5.mnu"
File 15="_functions_levylab_lib_general_afm_lithography_6.mnu"
File 16="_functions_levylab_lib_general_afm_lithography_7.mnu"
File 17="_functions_levylab_lib_general_afm_lithography_8.mnu"
File 18="_functions_levylab_lib_general_afm_lithography_9.mnu"
File 19="functions_levylab_lib_general_afm_lithography.mnu"


[File Group 2]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="If Newer"
Num Files=1
File 0="dir.mnu"
