[Package]
Name="levylab_lib_xy_utilities"
Version="1.5.2.2"
Release=""
ID=25172ec50be06314ab6f005c2ec9e718
File Format="vip"
Format Version="2017"
Display Name="XY Utilities"


[Description]
Description="Utilities for working with XY-data type (Cluster of 1D X and Y arrays).\0D\0A\0D\0ASupported methods:\0D\0A- <b>Arithmetic</b>: Add, Subtract, Multiply, Divide, Square, Log\0D\0A- <b>Array</b>: Sort, Reverse, Decimate, Decimate Array, Subset, Swap X and Y, Get X and Y, Append, Restrict X Range, Remove Outliers\0D\0A- <b>Signal Processing</b>: Derivative, Average, Moving Average, Interpolate, Interpolate Parameter, Resample, FFT Spectrum, FFT Power Spectrum, Symmetrize\0D\0A- <b>Filters</b>: Zero Phase Low Pass, Savitsky-Golay, \0D\0A- <b>Conversion</b>: Waveform to XY, XY to Waveform, 2D to XY, XY to 2D"
Summary=""
License="BSD-3"
Copyright="Copyright (c) 2022, LevyLab"
Distribution=""
Vendor="LevyLab"
URL=""
Packager="Patrick Irvin"
Demo="FALSE"
Release Notes="New Methods\0D\0A- 2D to YX.vi\0D\0A\0D\0ABug Fixes\0D\0A- Subset would not be inclusive of the final point\0A- Subset slider method would not correctly caclulate the range\0A- Interpolate would not interpolate the final point correctly if X_max == X_high\0A"
System Package="FALSE"
Sub Package="FALSE"
License Agreement="TRUE"


[LabVIEW]
close labview before install="FALSE"
restart labview after install="FALSE"
skip mass compile after install="FALSE"


[Platform]
Exclusive_LabVIEW_Version="LabVIEW>=19.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="ALL"


[Script VIs]
PreInstall=""
PostInstall=""
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires="levylab_lib_control_vi>=1.3.0.11,mgi_lib_1d_array>=1.0.2.3,oglib_array>=4.1.1.14,oglib_string>=5.0.0.25"
Conflicts=""


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="3"
Sub-Packages=""
Namespaces=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=130
File 0="user.lib/LevyLab/XY Utilities/2D to XY.vi"
File 1="user.lib/LevyLab/XY Utilities/2D to YX.vi"
File 2="user.lib/LevyLab/XY Utilities/Add.vi"
File 3="user.lib/LevyLab/XY Utilities/Append.vi"
File 4="user.lib/LevyLab/XY Utilities/Average.vi"
File 5="user.lib/LevyLab/XY Utilities/Decimate Array.vi"
File 6="user.lib/LevyLab/XY Utilities/Decimate.vi"
File 7="user.lib/LevyLab/XY Utilities/Derivative.vi"
File 8="user.lib/LevyLab/XY Utilities/Difference Quotient.vi"
File 9="user.lib/LevyLab/XY Utilities/Divide.vi"
File 10="user.lib/LevyLab/XY Utilities/FFT Power Spectrum.vi"
File 11="user.lib/LevyLab/XY Utilities/FFT Spectrum.vi"
File 12="user.lib/LevyLab/XY Utilities/Flatten.vi"
File 13="user.lib/LevyLab/XY Utilities/Get X and Y.vi"
File 14="user.lib/LevyLab/XY Utilities/Initialize.vi"
File 15="user.lib/LevyLab/XY Utilities/Interpolate Parameter.vi"
File 16="user.lib/LevyLab/XY Utilities/Interpolate Y.vi"
File 17="user.lib/LevyLab/XY Utilities/Interpolate.vi"
File 18="user.lib/LevyLab/XY Utilities/Linear Fit.vi"
File 19="user.lib/LevyLab/XY Utilities/Log.vi"
File 20="user.lib/LevyLab/XY Utilities/Moving Average.vi"
File 21="user.lib/LevyLab/XY Utilities/Multiply.vi"
File 22="user.lib/LevyLab/XY Utilities/Peak Detector.vi"
File 23="user.lib/LevyLab/XY Utilities/Remove Outliers.vi"
File 24="user.lib/LevyLab/XY Utilities/Resample.vi"
File 25="user.lib/LevyLab/XY Utilities/Restrict X Range.vi"
File 26="user.lib/LevyLab/XY Utilities/Reverse.vi"
File 27="user.lib/LevyLab/XY Utilities/Savitsky Golay Filter.vi"
File 28="user.lib/LevyLab/XY Utilities/Savitsky Golay Weighted Filter.vi"
File 29="user.lib/LevyLab/XY Utilities/Shift Zero.vi"
File 30="user.lib/LevyLab/XY Utilities/Sort.vi"
File 31="user.lib/LevyLab/XY Utilities/Square.vi"
File 32="user.lib/LevyLab/XY Utilities/Subset.vi"
File 33="user.lib/LevyLab/XY Utilities/Subtract.vi"
File 34="user.lib/LevyLab/XY Utilities/Swap X and Y.vi"
File 35="user.lib/LevyLab/XY Utilities/Symmetrize.vi"
File 36="user.lib/LevyLab/XY Utilities/Test Dataset.vi"
File 37="user.lib/LevyLab/XY Utilities/Waveform to XY.vi"
File 38="user.lib/LevyLab/XY Utilities/XY to 2D.vi"
File 39="user.lib/LevyLab/XY Utilities/XY to Waveform.vi"
File 40="user.lib/LevyLab/XY Utilities/xy_utilities.lvlib"
File 41="user.lib/LevyLab/XY Utilities/Zero Phase Lowpass Filter.vi"
File 42="user.lib/LevyLab/XY Utilities/Utilities/Change Execution.vi"
File 43="user.lib/LevyLab/XY Utilities/Typedefs/Interpolation Configuration--cluster.ctl"
File 44="user.lib/LevyLab/XY Utilities/templates/Template-XY-data (multiple).vit"
File 45="user.lib/LevyLab/XY Utilities/templates/Template-XY-data (single).vit"
File 46="user.lib/LevyLab/XY Utilities/subVIs/Add float (multiple).vi"
File 47="user.lib/LevyLab/XY Utilities/subVIs/Add float (single).vi"
File 48="user.lib/LevyLab/XY Utilities/subVIs/Add XY (multiple).vi"
File 49="user.lib/LevyLab/XY Utilities/subVIs/Add XY (single).vi"
File 50="user.lib/LevyLab/XY Utilities/subVIs/Append (double array).vi"
File 51="user.lib/LevyLab/XY Utilities/subVIs/Append (double scaler).vi"
File 52="user.lib/LevyLab/XY Utilities/subVIs/Append (multiple).vi"
File 53="user.lib/LevyLab/XY Utilities/subVIs/Append (single).vi"
File 54="user.lib/LevyLab/XY Utilities/subVIs/Decimate (multiple).vi"
File 55="user.lib/LevyLab/XY Utilities/subVIs/Decimate (single).vi"
File 56="user.lib/LevyLab/XY Utilities/subVIs/Derivative (multiple).vi"
File 57="user.lib/LevyLab/XY Utilities/subVIs/Derivative (single).vi"
File 58="user.lib/LevyLab/XY Utilities/subVIs/Difference Quotient (multiple).vi"
File 59="user.lib/LevyLab/XY Utilities/subVIs/Difference Quotient (single).vi"
File 60="user.lib/LevyLab/XY Utilities/subVIs/Divide float (multiple).vi"
File 61="user.lib/LevyLab/XY Utilities/subVIs/Divide float (single).vi"
File 62="user.lib/LevyLab/XY Utilities/subVIs/Divide XY (multiple).vi"
File 63="user.lib/LevyLab/XY Utilities/subVIs/Divide XY (single).vi"
File 64="user.lib/LevyLab/XY Utilities/subVIs/FFT (multiple).vi"
File 65="user.lib/LevyLab/XY Utilities/subVIs/FFT (single).vi"
File 66="user.lib/LevyLab/XY Utilities/subVIs/Get X and Y (multiple).vi"
File 67="user.lib/LevyLab/XY Utilities/subVIs/Get X and Y (single).vi"
File 68="user.lib/LevyLab/XY Utilities/subVIs/Interpolate (multiple).vi"
File 69="user.lib/LevyLab/XY Utilities/subVIs/Interpolate (single).vi"
File 70="user.lib/LevyLab/XY Utilities/subVIs/Interpolate Y (multiple).vi"
File 71="user.lib/LevyLab/XY Utilities/subVIs/Interpolate Y (single).vi"
File 72="user.lib/LevyLab/XY Utilities/subVIs/Linear Fit (multiple).vi"
File 73="user.lib/LevyLab/XY Utilities/subVIs/Linear Fit (single).vi"
File 74="user.lib/LevyLab/XY Utilities/subVIs/Linear Fit CI (single)(unused).vi"
File 75="user.lib/LevyLab/XY Utilities/subVIs/Log (multiple).vi"
File 76="user.lib/LevyLab/XY Utilities/subVIs/Log (single).vi"
File 77="user.lib/LevyLab/XY Utilities/subVIs/Modified Sinc Filter (single).vi"
File 78="user.lib/LevyLab/XY Utilities/subVIs/Moving Average (multiple).vi"
File 79="user.lib/LevyLab/XY Utilities/subVIs/Moving Average (single).vi"
File 80="user.lib/LevyLab/XY Utilities/subVIs/Multiply float (multiple).vi"
File 81="user.lib/LevyLab/XY Utilities/subVIs/Multiply float (single).vi"
File 82="user.lib/LevyLab/XY Utilities/subVIs/Multiply XY (multiple).vi"
File 83="user.lib/LevyLab/XY Utilities/subVIs/Multiply XY (single).vi"
File 84="user.lib/LevyLab/XY Utilities/subVIs/Peak Detector (multiple).vi"
File 85="user.lib/LevyLab/XY Utilities/subVIs/Peak Detector (single).vi"
File 86="user.lib/LevyLab/XY Utilities/subVIs/PS (multiple).vi"
File 87="user.lib/LevyLab/XY Utilities/subVIs/PS (single).vi"
File 88="user.lib/LevyLab/XY Utilities/subVIs/Remove Outliers (multiple).vi"
File 89="user.lib/LevyLab/XY Utilities/subVIs/Remove Outliers (single).vi"
File 90="user.lib/LevyLab/XY Utilities/subVIs/Resample (multiple).vi"
File 91="user.lib/LevyLab/XY Utilities/subVIs/Resample (single).vi"
File 92="user.lib/LevyLab/XY Utilities/subVIs/Restrict X Range (multiple).vi"
File 93="user.lib/LevyLab/XY Utilities/subVIs/Restrict X Range (single).vi"
File 94="user.lib/LevyLab/XY Utilities/subVIs/Reverse (multiple).vi"
File 95="user.lib/LevyLab/XY Utilities/subVIs/Reverse (single).vi"
File 96="user.lib/LevyLab/XY Utilities/subVIs/Savitsky Golay Filter (multiple).vi"
File 97="user.lib/LevyLab/XY Utilities/subVIs/Savitsky Golay Filter (single).vi"
File 98="user.lib/LevyLab/XY Utilities/subVIs/Savitsky Golay Weighted Filter (multiple).vi"
File 99="user.lib/LevyLab/XY Utilities/subVIs/Savitsky Golay Weighted Filter (single).vi"
File 100="user.lib/LevyLab/XY Utilities/subVIs/Shift Zero (multiple).vi"
File 101="user.lib/LevyLab/XY Utilities/subVIs/Shift Zero (single).vi"
File 102="user.lib/LevyLab/XY Utilities/subVIs/Sort (multiple).vi"
File 103="user.lib/LevyLab/XY Utilities/subVIs/Sort (single).vi"
File 104="user.lib/LevyLab/XY Utilities/subVIs/Square (multiple).vi"
File 105="user.lib/LevyLab/XY Utilities/subVIs/Square (single).vi"
File 106="user.lib/LevyLab/XY Utilities/subVIs/Subset (multiple).vi"
File 107="user.lib/LevyLab/XY Utilities/subVIs/Subset (single).vi"
File 108="user.lib/LevyLab/XY Utilities/subVIs/Subtract float (multiple).vi"
File 109="user.lib/LevyLab/XY Utilities/subVIs/Subtract float (single).vi"
File 110="user.lib/LevyLab/XY Utilities/subVIs/Subtract XY (multiple).vi"
File 111="user.lib/LevyLab/XY Utilities/subVIs/Subtract XY (single).vi"
File 112="user.lib/LevyLab/XY Utilities/subVIs/Swap X and Y (multiple).vi"
File 113="user.lib/LevyLab/XY Utilities/subVIs/Swap X and Y (single).vi"
File 114="user.lib/LevyLab/XY Utilities/subVIs/Symmetrize (multiple).vi"
File 115="user.lib/LevyLab/XY Utilities/subVIs/Symmetrize (single).vi"
File 116="user.lib/LevyLab/XY Utilities/subVIs/Waveform to XY (multiple).vi"
File 117="user.lib/LevyLab/XY Utilities/subVIs/Waveform to XY (single).vi"
File 118="user.lib/LevyLab/XY Utilities/subVIs/XY to Waveform (multiple).vi"
File 119="user.lib/LevyLab/XY Utilities/subVIs/XY to Waveform (single).vi"
File 120="user.lib/LevyLab/XY Utilities/subVIs/Zero Phase Lowpass Filter (multiple).vi"
File 121="user.lib/LevyLab/XY Utilities/subVIs/Zero Phase Lowpass Filter (single).vi"
File 122="user.lib/LevyLab/XY Utilities/Private/DQ subVI.vi"
File 123="user.lib/LevyLab/XY Utilities/Private/Get X Array dx.vi"
File 124="user.lib/LevyLab/XY Utilities/Private/Hann Windows.vi"
File 125="user.lib/LevyLab/XY Utilities/Private/X Array Index to Range.vi"
File 126="user.lib/LevyLab/XY Utilities/Private/X Array Range to Index.vi"
File 127="user.lib/LevyLab/XY Utilities/Private/X Units.vi"
File 128="user.lib/LevyLab/XY Utilities/examples/Tree.vi"
File 129="user.lib/LevyLab/XY Utilities/examples/XY State Machine Example.vi"


[File Group 1]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="Always"
Num Files=2
File 0="_functions_levylab_lib_xy_utilities_1.mnu"
File 1="functions_LevyLab_lib_XY_Utilities.mnu"


[File Group 2]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="If Newer"
Num Files=1
File 0="dir.mnu"
