[Package]
Name="levylab_lib_xy_utilities"
Version="1.6.0.6"
Release=""
ID=92384fc51be468faf31f1cd6a20bcfd8
File Format="vip"
Format Version="2017"
Display Name="XY Utilities"


[Description]
Description="Utilities for working with XY-data type (Cluster of 1D X and Y arrays).\0D\0A\0D\0ASupported methods:\0D\0A- <b>Arithmetic</b>: Add, Subtract, Multiply, Divide, Square, Log\0D\0A- <b>Array</b>: Sort, Reverse, Decimate, Decimate Array, Subset, Swap X and Y, Get X and Y, Append, Restrict X Range, Remove Outliers\0D\0A- <b>Signal Processing</b>: Derivative, Average, Moving Average, Interpolate, Interpolate Parameter, Resample, FFT Spectrum, FFT Power Spectrum, Symmetrize\0D\0A- <b>Filters</b>: Zero Phase Low Pass, Savitsky-Golay, \0D\0A- <b>Conversion</b>: Waveform to XY, XY to Waveform, 2D to XY, XY to 2D"
Summary="Utilities for working with XY data in LabVIEW"
License="BSD-3"
Copyright="Copyright (c) 2025, PRIrvin"
Distribution=""
Vendor="PRIrvin"
URL="https://github.com/PRIrvin"
Packager="Patrick Irvin"
Demo="FALSE"
Release Notes="- Issue #37: Symmetrize.vi should use sorted x data to calculate +/- x properly.\0A- New methods: Negate, Reciprocal, Split, Square Root"
System Package="FALSE"
Sub Package="FALSE"
License Agreement="TRUE"


[LabVIEW]
close labview before install="FALSE"
restart labview after install="FALSE"
skip mass compile after install="FALSE"
install into global environment="FALSE"


[Platform]
Exclusive_LabVIEW_Version="LabVIEW>=19.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="ALL"


[Script VIs]
PreInstall=""
PostInstall=""
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires="jki_lib_state_machine>=2018.0.7.45,mgi_lib_1d_array>=1.0.2.3,oglib_array>=4.1.1.14,oglib_string>=5.0.0.25"
Conflicts=""


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="2"
Sub-Packages=""
Namespaces=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=142
File 0="vi.lib/PRIrvin/XY Utilities/2D to XY.vi"
File 1="vi.lib/PRIrvin/XY Utilities/2D to YX.vi"
File 2="vi.lib/PRIrvin/XY Utilities/Add.vi"
File 3="vi.lib/PRIrvin/XY Utilities/Append.vi"
File 4="vi.lib/PRIrvin/XY Utilities/Average.vi"
File 5="vi.lib/PRIrvin/XY Utilities/Decimate Array.vi"
File 6="vi.lib/PRIrvin/XY Utilities/Decimate.vi"
File 7="vi.lib/PRIrvin/XY Utilities/Derivative.vi"
File 8="vi.lib/PRIrvin/XY Utilities/Difference Quotient.vi"
File 9="vi.lib/PRIrvin/XY Utilities/Divide.vi"
File 10="vi.lib/PRIrvin/XY Utilities/FFT Power Spectrum.vi"
File 11="vi.lib/PRIrvin/XY Utilities/FFT Spectrum.vi"
File 12="vi.lib/PRIrvin/XY Utilities/Flatten.vi"
File 13="vi.lib/PRIrvin/XY Utilities/Get X and Y.vi"
File 14="vi.lib/PRIrvin/XY Utilities/Initialize.vi"
File 15="vi.lib/PRIrvin/XY Utilities/Interpolate Parameter.vi"
File 16="vi.lib/PRIrvin/XY Utilities/Interpolate Y.vi"
File 17="vi.lib/PRIrvin/XY Utilities/Interpolate.vi"
File 18="vi.lib/PRIrvin/XY Utilities/Linear Fit.vi"
File 19="vi.lib/PRIrvin/XY Utilities/Log.vi"
File 20="vi.lib/PRIrvin/XY Utilities/Moving Average.vi"
File 21="vi.lib/PRIrvin/XY Utilities/Multiply.vi"
File 22="vi.lib/PRIrvin/XY Utilities/Negate.vi"
File 23="vi.lib/PRIrvin/XY Utilities/Peak Detector.vi"
File 24="vi.lib/PRIrvin/XY Utilities/Reciprocal.vi"
File 25="vi.lib/PRIrvin/XY Utilities/Remove Outliers.vi"
File 26="vi.lib/PRIrvin/XY Utilities/Resample.vi"
File 27="vi.lib/PRIrvin/XY Utilities/Restrict X Range.vi"
File 28="vi.lib/PRIrvin/XY Utilities/Reverse.vi"
File 29="vi.lib/PRIrvin/XY Utilities/Savitsky Golay Filter.vi"
File 30="vi.lib/PRIrvin/XY Utilities/Savitsky Golay Weighted Filter.vi"
File 31="vi.lib/PRIrvin/XY Utilities/Shift Zero.vi"
File 32="vi.lib/PRIrvin/XY Utilities/Sort.vi"
File 33="vi.lib/PRIrvin/XY Utilities/Split.vi"
File 34="vi.lib/PRIrvin/XY Utilities/Square Root.vi"
File 35="vi.lib/PRIrvin/XY Utilities/Square.vi"
File 36="vi.lib/PRIrvin/XY Utilities/Subset.vi"
File 37="vi.lib/PRIrvin/XY Utilities/Subtract.vi"
File 38="vi.lib/PRIrvin/XY Utilities/Swap X and Y.vi"
File 39="vi.lib/PRIrvin/XY Utilities/Symmetrize.vi"
File 40="vi.lib/PRIrvin/XY Utilities/Test Dataset.vi"
File 41="vi.lib/PRIrvin/XY Utilities/Waveform to XY.vi"
File 42="vi.lib/PRIrvin/XY Utilities/XY to 2D.vi"
File 43="vi.lib/PRIrvin/XY Utilities/XY to Waveform.vi"
File 44="vi.lib/PRIrvin/XY Utilities/xy_utilities.lvlib"
File 45="vi.lib/PRIrvin/XY Utilities/Zero Phase Lowpass Filter.vi"
File 46="vi.lib/PRIrvin/XY Utilities/Utilities/Change Execution.vi"
File 47="vi.lib/PRIrvin/XY Utilities/Typedefs/Interpolation Configuration--cluster.ctl"
File 48="vi.lib/PRIrvin/XY Utilities/templates/Template-XY-data (multiple).vit"
File 49="vi.lib/PRIrvin/XY Utilities/templates/Template-XY-data (single).vit"
File 50="vi.lib/PRIrvin/XY Utilities/subVIs/Add float (multiple).vi"
File 51="vi.lib/PRIrvin/XY Utilities/subVIs/Add float (single).vi"
File 52="vi.lib/PRIrvin/XY Utilities/subVIs/Add XY (multiple).vi"
File 53="vi.lib/PRIrvin/XY Utilities/subVIs/Add XY (single).vi"
File 54="vi.lib/PRIrvin/XY Utilities/subVIs/Append (double array).vi"
File 55="vi.lib/PRIrvin/XY Utilities/subVIs/Append (double scaler).vi"
File 56="vi.lib/PRIrvin/XY Utilities/subVIs/Append (multiple).vi"
File 57="vi.lib/PRIrvin/XY Utilities/subVIs/Append (single).vi"
File 58="vi.lib/PRIrvin/XY Utilities/subVIs/Decimate (multiple).vi"
File 59="vi.lib/PRIrvin/XY Utilities/subVIs/Decimate (single).vi"
File 60="vi.lib/PRIrvin/XY Utilities/subVIs/Derivative (multiple).vi"
File 61="vi.lib/PRIrvin/XY Utilities/subVIs/Derivative (single).vi"
File 62="vi.lib/PRIrvin/XY Utilities/subVIs/Difference Quotient (multiple).vi"
File 63="vi.lib/PRIrvin/XY Utilities/subVIs/Difference Quotient (single).vi"
File 64="vi.lib/PRIrvin/XY Utilities/subVIs/Divide float (multiple).vi"
File 65="vi.lib/PRIrvin/XY Utilities/subVIs/Divide float (single).vi"
File 66="vi.lib/PRIrvin/XY Utilities/subVIs/Divide XY (multiple).vi"
File 67="vi.lib/PRIrvin/XY Utilities/subVIs/Divide XY (single).vi"
File 68="vi.lib/PRIrvin/XY Utilities/subVIs/FFT (multiple).vi"
File 69="vi.lib/PRIrvin/XY Utilities/subVIs/FFT (single).vi"
File 70="vi.lib/PRIrvin/XY Utilities/subVIs/Get X and Y (multiple).vi"
File 71="vi.lib/PRIrvin/XY Utilities/subVIs/Get X and Y (single).vi"
File 72="vi.lib/PRIrvin/XY Utilities/subVIs/Interpolate (multiple).vi"
File 73="vi.lib/PRIrvin/XY Utilities/subVIs/Interpolate (single).vi"
File 74="vi.lib/PRIrvin/XY Utilities/subVIs/Interpolate Y (multiple).vi"
File 75="vi.lib/PRIrvin/XY Utilities/subVIs/Interpolate Y (single).vi"
File 76="vi.lib/PRIrvin/XY Utilities/subVIs/Linear Fit (multiple).vi"
File 77="vi.lib/PRIrvin/XY Utilities/subVIs/Linear Fit (single).vi"
File 78="vi.lib/PRIrvin/XY Utilities/subVIs/Linear Fit CI (single)(unused).vi"
File 79="vi.lib/PRIrvin/XY Utilities/subVIs/Log (multiple).vi"
File 80="vi.lib/PRIrvin/XY Utilities/subVIs/Log (single).vi"
File 81="vi.lib/PRIrvin/XY Utilities/subVIs/Modified Sinc Filter (single).vi"
File 82="vi.lib/PRIrvin/XY Utilities/subVIs/Moving Average (multiple).vi"
File 83="vi.lib/PRIrvin/XY Utilities/subVIs/Moving Average (single).vi"
File 84="vi.lib/PRIrvin/XY Utilities/subVIs/Multiply float (multiple).vi"
File 85="vi.lib/PRIrvin/XY Utilities/subVIs/Multiply float (single).vi"
File 86="vi.lib/PRIrvin/XY Utilities/subVIs/Multiply XY (multiple).vi"
File 87="vi.lib/PRIrvin/XY Utilities/subVIs/Multiply XY (single).vi"
File 88="vi.lib/PRIrvin/XY Utilities/subVIs/Negate (multiple).vi"
File 89="vi.lib/PRIrvin/XY Utilities/subVIs/Negate (single).vi"
File 90="vi.lib/PRIrvin/XY Utilities/subVIs/Peak Detector (multiple).vi"
File 91="vi.lib/PRIrvin/XY Utilities/subVIs/Peak Detector (single).vi"
File 92="vi.lib/PRIrvin/XY Utilities/subVIs/PS (multiple).vi"
File 93="vi.lib/PRIrvin/XY Utilities/subVIs/PS (single).vi"
File 94="vi.lib/PRIrvin/XY Utilities/subVIs/Reciprocal (multiple).vi"
File 95="vi.lib/PRIrvin/XY Utilities/subVIs/Reciprocal (single).vi"
File 96="vi.lib/PRIrvin/XY Utilities/subVIs/Remove Outliers (multiple).vi"
File 97="vi.lib/PRIrvin/XY Utilities/subVIs/Remove Outliers (single).vi"
File 98="vi.lib/PRIrvin/XY Utilities/subVIs/Resample (multiple).vi"
File 99="vi.lib/PRIrvin/XY Utilities/subVIs/Resample (single).vi"
File 100="vi.lib/PRIrvin/XY Utilities/subVIs/Restrict X Range (multiple).vi"
File 101="vi.lib/PRIrvin/XY Utilities/subVIs/Restrict X Range (single).vi"
File 102="vi.lib/PRIrvin/XY Utilities/subVIs/Reverse (multiple).vi"
File 103="vi.lib/PRIrvin/XY Utilities/subVIs/Reverse (single).vi"
File 104="vi.lib/PRIrvin/XY Utilities/subVIs/Savitsky Golay Filter (multiple).vi"
File 105="vi.lib/PRIrvin/XY Utilities/subVIs/Savitsky Golay Filter (single).vi"
File 106="vi.lib/PRIrvin/XY Utilities/subVIs/Savitsky Golay Weighted Filter (multiple).vi"
File 107="vi.lib/PRIrvin/XY Utilities/subVIs/Savitsky Golay Weighted Filter (single).vi"
File 108="vi.lib/PRIrvin/XY Utilities/subVIs/Shift Zero (multiple).vi"
File 109="vi.lib/PRIrvin/XY Utilities/subVIs/Shift Zero (single).vi"
File 110="vi.lib/PRIrvin/XY Utilities/subVIs/Sort (multiple).vi"
File 111="vi.lib/PRIrvin/XY Utilities/subVIs/Sort (single).vi"
File 112="vi.lib/PRIrvin/XY Utilities/subVIs/Split (multiple).vi"
File 113="vi.lib/PRIrvin/XY Utilities/subVIs/Split (single).vi"
File 114="vi.lib/PRIrvin/XY Utilities/subVIs/Square (multiple).vi"
File 115="vi.lib/PRIrvin/XY Utilities/subVIs/Square (single).vi"
File 116="vi.lib/PRIrvin/XY Utilities/subVIs/Square Root (multiple).vi"
File 117="vi.lib/PRIrvin/XY Utilities/subVIs/Square Root (single).vi"
File 118="vi.lib/PRIrvin/XY Utilities/subVIs/Subset (multiple).vi"
File 119="vi.lib/PRIrvin/XY Utilities/subVIs/Subset (single).vi"
File 120="vi.lib/PRIrvin/XY Utilities/subVIs/Subtract float (multiple).vi"
File 121="vi.lib/PRIrvin/XY Utilities/subVIs/Subtract float (single).vi"
File 122="vi.lib/PRIrvin/XY Utilities/subVIs/Subtract XY (multiple).vi"
File 123="vi.lib/PRIrvin/XY Utilities/subVIs/Subtract XY (single).vi"
File 124="vi.lib/PRIrvin/XY Utilities/subVIs/Swap X and Y (multiple).vi"
File 125="vi.lib/PRIrvin/XY Utilities/subVIs/Swap X and Y (single).vi"
File 126="vi.lib/PRIrvin/XY Utilities/subVIs/Symmetrize (multiple).vi"
File 127="vi.lib/PRIrvin/XY Utilities/subVIs/Symmetrize (single).vi"
File 128="vi.lib/PRIrvin/XY Utilities/subVIs/Waveform to XY (multiple).vi"
File 129="vi.lib/PRIrvin/XY Utilities/subVIs/Waveform to XY (single).vi"
File 130="vi.lib/PRIrvin/XY Utilities/subVIs/XY to Waveform (multiple).vi"
File 131="vi.lib/PRIrvin/XY Utilities/subVIs/XY to Waveform (single).vi"
File 132="vi.lib/PRIrvin/XY Utilities/subVIs/Zero Phase Lowpass Filter (multiple).vi"
File 133="vi.lib/PRIrvin/XY Utilities/subVIs/Zero Phase Lowpass Filter (single).vi"
File 134="vi.lib/PRIrvin/XY Utilities/Private/DQ subVI.vi"
File 135="vi.lib/PRIrvin/XY Utilities/Private/Get X Array dx.vi"
File 136="vi.lib/PRIrvin/XY Utilities/Private/Hann Windows.vi"
File 137="vi.lib/PRIrvin/XY Utilities/Private/X Array Index to Range.vi"
File 138="vi.lib/PRIrvin/XY Utilities/Private/X Array Range to Index.vi"
File 139="vi.lib/PRIrvin/XY Utilities/Private/X Units.vi"
File 140="vi.lib/PRIrvin/XY Utilities/examples/Tree.vi"
File 141="vi.lib/PRIrvin/XY Utilities/examples/XY State Machine Example.vi"


[File Group 1]
Target Dir="<vi.lib>/addons/prirvin"
Replace Mode="Always"
Num Files=2
File 0="_functions_levylab_lib_xy_utilities_1.mnu"
File 1="functions_LevyLab_lib_XY_Utilities.mnu"
