[Package]
Name="levylab_lib_instrument_type"
Version="1.1.1.8"
Release=""
ID=f2815ebd27ba7abc4e4a023df412c26d
File Format="vip"
Format Version="2017"
Display Name="Instrument Type"


[Description]
Description="Instrument Framework Interfaces / Instrument Types"
Summary=""
License=""
Copyright="Copyright (c) 2025, LevyLab"
Distribution=""
Vendor="LevyLab"
URL=""
Packager="Patrick Irvin"
Demo="FALSE"
Release Notes="[1.1.1]\0A-  #165 adjust package dependencies"
System Package="FALSE"
Sub Package="FALSE"
License Agreement="FALSE"


[LabVIEW]
close labview before install="FALSE"
restart labview after install="FALSE"
skip mass compile after install="FALSE"
install into global environment="FALSE"


[Platform]
Exclusive_LabVIEW_Version="LabVIEW>=19.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="ALL"


[Script VIs]
PreInstall=""
PostInstall=""
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires="levylab_lib_levylab_instruments>=1.15.2.37"
Conflicts="levylab_lib_levylab_instruments>=2.0.0.25"


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="3"
Sub-Packages=""
Namespaces=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=180
File 0="user.lib/LevyLab/Instrument Framework/Instrument Types/VSource/Instrument.VSource.lvclass"
File 1="user.lib/LevyLab/Instrument Framework/Instrument Types/VSource/API/Get Bias Voltage.vi"
File 2="user.lib/LevyLab/Instrument Framework/Instrument Types/VSource/API/getBiasVoltage.vi"
File 3="user.lib/LevyLab/Instrument Framework/Instrument Types/VSource/API/Set Bias Voltage.vi"
File 4="user.lib/LevyLab/Instrument Framework/Instrument Types/VSource/API/setBiasVoltage.vi"
File 5="user.lib/LevyLab/Instrument Framework/Instrument Types/VNA/getData.vi"
File 6="user.lib/LevyLab/Instrument Framework/Instrument Types/VNA/Instrument.VNA.lvclass"
File 7="user.lib/LevyLab/Instrument Framework/Instrument Types/VNA/setAverage.vi"
File 8="user.lib/LevyLab/Instrument Framework/Instrument Types/VNA/setFormat.vi"
File 9="user.lib/LevyLab/Instrument Framework/Instrument Types/VNA/setMeasurement.vi"
File 10="user.lib/LevyLab/Instrument Framework/Instrument Types/VNA/setPower.vi"
File 11="user.lib/LevyLab/Instrument Framework/Instrument Types/VNA/setSweep.vi"
File 12="user.lib/LevyLab/Instrument Framework/Instrument Types/VNA/Typedefs/Conversion--enum.ctl"
File 13="user.lib/LevyLab/Instrument Framework/Instrument Types/VNA/Typedefs/Format--enum.ctl"
File 14="user.lib/LevyLab/Instrument Framework/Instrument Types/VNA/Typedefs/Measurement--enum.ctl"
File 15="user.lib/LevyLab/Instrument Framework/Instrument Types/VNA/Typedefs/setAverage--cluster.ctl"
File 16="user.lib/LevyLab/Instrument Framework/Instrument Types/VNA/Typedefs/setMeasurement--cluster.ctl"
File 17="user.lib/LevyLab/Instrument Framework/Instrument Types/VNA/Typedefs/setPower--cluster.ctl"
File 18="user.lib/LevyLab/Instrument Framework/Instrument Types/VNA/Typedefs/setSweep--cluster.ctl"
File 19="user.lib/LevyLab/Instrument Framework/Instrument Types/VNA/Typedefs/Sweep Type--enum.ctl"
File 20="user.lib/LevyLab/Instrument Framework/Instrument Types/VNA/Typedefs/VNA.Commands--Enum.ctl"
File 21="user.lib/LevyLab/Instrument Framework/Instrument Types/Test/Cryostat.Test.lvclass"
File 22="user.lib/LevyLab/Instrument Framework/Instrument Types/Strain/Get SMO HELP.vi"
File 23="user.lib/LevyLab/Instrument Framework/Instrument Types/Strain/Get SMO Public API.vi"
File 24="user.lib/LevyLab/Instrument Framework/Instrument Types/Strain/Get Strain.vi"
File 25="user.lib/LevyLab/Instrument Framework/Instrument Types/Strain/getStrain.vi"
File 26="user.lib/LevyLab/Instrument Framework/Instrument Types/Strain/Instrument.Strain.lvclass"
File 27="user.lib/LevyLab/Instrument Framework/Instrument Types/Strain/Set Strain.vi"
File 28="user.lib/LevyLab/Instrument Framework/Instrument Types/Strain/setStrain.vi"
File 29="user.lib/LevyLab/Instrument Framework/Instrument Types/Strain/Typedefs/setStrain--cluster.ctl"
File 30="user.lib/LevyLab/Instrument Framework/Instrument Types/Strain/Typedefs/Strain.Commands--Enum.ctl"
File 31="user.lib/LevyLab/Instrument Framework/Instrument Types/SignalGenerator/Instrument.SignalGenerator.lvclass"
File 32="user.lib/LevyLab/Instrument Framework/Instrument Types/SignalGenerator/setFrequency.vi"
File 33="user.lib/LevyLab/Instrument Framework/Instrument Types/SignalGenerator/setFunction.vi"
File 34="user.lib/LevyLab/Instrument Framework/Instrument Types/SignalGenerator/setLevel.vi"
File 35="user.lib/LevyLab/Instrument Framework/Instrument Types/SignalGenerator/setOffset.vi"
File 36="user.lib/LevyLab/Instrument Framework/Instrument Types/SignalGenerator/setPhase.vi"
File 37="user.lib/LevyLab/Instrument Framework/Instrument Types/SignalGenerator/setPower.vi"
File 38="user.lib/LevyLab/Instrument Framework/Instrument Types/SignalGenerator/Typedefs/setFloatParameter--enum.ctl"
File 39="user.lib/LevyLab/Instrument Framework/Instrument Types/SignalGenerator/Typedefs/setStringParameter--enum.ctl"
File 40="user.lib/LevyLab/Instrument Framework/Instrument Types/SignalGenerator/Typedefs/SignalGenerator.Commands--Enum.ctl"
File 41="user.lib/LevyLab/Instrument Framework/Instrument Types/SCPI/Instrument.SCPI.lvclass"
File 42="user.lib/LevyLab/Instrument Framework/Instrument Types/SCPI/SCPI.Receive.vi"
File 43="user.lib/LevyLab/Instrument Framework/Instrument Types/SCPI/SCPI.Send.vi"
File 44="user.lib/LevyLab/Instrument Framework/Instrument Types/SCPI/Typedefs/SCPI.Commands--Enum.ctl"
File 45="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Instrument.LockinAPI.lvclass"
File 46="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Typedefs/LockinAPI.AO_Amp--cluster.ctl"
File 47="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Typedefs/LockinAPI.AO_DC--cluster.ctl"
File 48="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Typedefs/LockinAPI.AO_f--cluster.ctl"
File 49="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Typedefs/LockinAPI.AO_function--cluster.ctl"
File 50="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Typedefs/LockinAPI.AO_phi--cluster.ctl"
File 51="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Typedefs/LockinAPI.AUX--cluster.ctl"
File 52="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Typedefs/LockinAPI.Commands--Enum.ctl"
File 53="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Typedefs/LockinAPI.getState.states--enum.ctl"
File 54="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Typedefs/LockinAPI.OffsetMode--Enum.ctl"
File 55="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Typedefs/LockinAPI.REF_f--cluster.ctl"
File 56="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Typedefs/LockinAPI.REF_phi--cluster.ctl"
File 57="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Typedefs/LockinAPI.REF_RollOff--cluster.ctl"
File 58="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Typedefs/LockinAPI.REF_TC--cluster.ctl"
File 59="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Typedefs/LockinAPI.Sampling.FsMode--enum.ctl"
File 60="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Typedefs/LockinAPI.Sampling.Sampling--Cluster.ctl"
File 61="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Typedefs/LockinAPI.setState.states--Enum.ctl"
File 62="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Typedefs/LockinAPI.SweepChannel--Cluster.ctl"
File 63="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Typedefs/LockinAPI.SweepData--Cluster.ctl"
File 64="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Typedefs/LockinAPI.SweepTable--cluster.ctl"
File 65="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/Private/Retry Timeout.vi"
File 66="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/getAIwfm.vi"
File 67="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/getAOwfm.vi"
File 68="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/getInputGain.vi"
File 69="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/getOutputGain.vi"
File 70="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/getResults.vi"
File 71="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/getSampling.vi"
File 72="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/getSamplingFsMode.vi"
File 73="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/getSweepData.vi"
File 74="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/getSweepResults.vi"
File 75="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/getSweepWaveforms.vi"
File 76="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/setInputGain.vi"
File 77="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/setOffsetMode.vi"
File 78="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/setOutputGain.vi"
File 79="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/setSampling.vi"
File 80="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/setSamplingFsMode.vi"
File 81="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/setSweepTable.vi"
File 82="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/setSweepTime.vi"
File 83="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/State/getStatus.vi"
File 84="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/State/resetDAQ.vi"
File 85="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/State/setState.vi"
File 86="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/State/startDAQ.vi"
File 87="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/State/startSweep.vi"
File 88="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/State/stopDAQ.vi"
File 89="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/State/stopSweep.vi"
File 90="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/REF/setREF_f.vi"
File 91="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/REF/setREF_phi.vi"
File 92="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/REF/setREF_RollOff.vi"
File 93="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/REF/setREF_TC.vi"
File 94="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/Macros/startSweepAndWait.vi"
File 95="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/Macros/waitNewResults.vi"
File 96="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/Macros/waitNewWaveforms.vi"
File 97="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/Macros/waitStatusCreated.vi"
File 98="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/Macros/waitStatusIdle.vi"
File 99="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/Macros/waitStatusStarted.vi"
File 100="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/Macros/waitStatusStopped.vi"
File 101="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/Macros/waitStatusSweepingStarted.vi"
File 102="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/Macros/waitStatusSweepingStopped.vi"
File 103="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/AO/setAO_Amp.vi"
File 104="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/AO/setAO_DC.vi"
File 105="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/AO/setAO_f.vi"
File 106="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/AO/setAO_function.vi"
File 107="user.lib/LevyLab/Instrument Framework/Instrument Types/Lockin/API/AO/setAO_phi.vi"
File 108="user.lib/LevyLab/Instrument Framework/Instrument Types/Delay Line/Get Delay.vi"
File 109="user.lib/LevyLab/Instrument Framework/Instrument Types/Delay Line/getDelay.vi"
File 110="user.lib/LevyLab/Instrument Framework/Instrument Types/Delay Line/Instrument.DelayLine.lvclass"
File 111="user.lib/LevyLab/Instrument Framework/Instrument Types/Delay Line/Set Delay.vi"
File 112="user.lib/LevyLab/Instrument Framework/Instrument Types/Delay Line/setDelay.vi"
File 113="user.lib/LevyLab/Instrument Framework/Instrument Types/Delay Line/Typedefs/DelayLine.Commands--Enum.ctl"
File 114="user.lib/LevyLab/Instrument Framework/Instrument Types/Delay Line/Typedefs/DelayLine.getDelay--cluster.ctl"
File 115="user.lib/LevyLab/Instrument Framework/Instrument Types/Delay Line/Typedefs/DelayLine.setDelay--cluster.ctl"
File 116="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Cryostat JSON.vi"
File 117="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Get Angle.vi"
File 118="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Get Chamber.vi"
File 119="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Get Heater.vi"
File 120="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Get Helium Level.vi"
File 121="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Get Magnet.vi"
File 122="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Get Nitrogen Level.vi"
File 123="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Get Pressure.vi"
File 124="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Get SMO HELP.vi"
File 125="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Get SMO Public API.vi"
File 126="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Get Temperature.vi"
File 127="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/getAngle.vi"
File 128="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/getChamber.vi"
File 129="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/getHeater.vi"
File 130="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/getLHeLevel.vi"
File 131="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/getLN2Level.vi"
File 132="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/getMagnet.vi"
File 133="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/getMagnetVector.vi"
File 134="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/getPressure.vi"
File 135="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/getTemperature.vi"
File 136="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Instrument.Cryostat.lvclass"
File 137="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Set Angle.vi"
File 138="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Set Chamber.vi"
File 139="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Set Heater.vi"
File 140="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Set Magnet.vi"
File 141="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Set Temperature.vi"
File 142="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/setAngle.vi"
File 143="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/setChamber.vi"
File 144="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/setHeater.vi"
File 145="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/setMagnet.vi"
File 146="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/setMagnetVector.vi"
File 147="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/setTemperature.vi"
File 148="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Wait for Magnet Setpoint.vi"
File 149="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Wait for Temperature Setpoint.vi"
File 150="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/waitForMagnet.vi"
File 151="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/waitForTemperature.vi"
File 152="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Typedefs/Cryostat.commands--enum.ctl"
File 153="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Typedefs/getAngle--cluster.ctl"
File 154="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Typedefs/getHeater--cluster.ctl"
File 155="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Typedefs/getMagnet--cluster.ctl"
File 156="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Typedefs/getMagnetVector--cluster.ctl"
File 157="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Typedefs/getPressure--cluster.ctl"
File 158="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Typedefs/getTemperature--cluster.ctl"
File 159="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Typedefs/Magnet Axis--Enum.ctl"
File 160="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Typedefs/Magnet Mode--Enum.ctl"
File 161="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Typedefs/Rotator Axis--Enum.ctl"
File 162="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Typedefs/setAngle--cluster.ctl"
File 163="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Typedefs/setChamber--cluster.ctl"
File 164="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Typedefs/setHeater--cluster.ctl"
File 165="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Typedefs/setMagnet--cluster.ctl"
File 166="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Typedefs/setMagnetVector--cluster.ctl"
File 167="user.lib/LevyLab/Instrument Framework/Instrument Types/Cryostat/Typedefs/setTemperature--cluster.ctl"
File 168="user.lib/LevyLab/Instrument Framework/Instrument Types/CBridge/Get Capacitance.vi"
File 169="user.lib/LevyLab/Instrument Framework/Instrument Types/CBridge/getCapacitance.vi"
File 170="user.lib/LevyLab/Instrument Framework/Instrument Types/CBridge/Instrument.CBridge.lvclass"
File 171="user.lib/LevyLab/Instrument Framework/Instrument Types/CBridge/Typedefs/CBridge.Commands--Enum.ctl"
File 172="user.lib/LevyLab/Instrument Framework/Instrument Types/Amplifier/Amplifier.Commands--Enum.ctl"
File 173="user.lib/LevyLab/Instrument Framework/Instrument Types/Amplifier/Get SMO HELP.vi"
File 174="user.lib/LevyLab/Instrument Framework/Instrument Types/Amplifier/Get SMO Public API.vi"
File 175="user.lib/LevyLab/Instrument Framework/Instrument Types/Amplifier/getAllChannels.vi"
File 176="user.lib/LevyLab/Instrument Framework/Instrument Types/Amplifier/getChannel.vi"
File 177="user.lib/LevyLab/Instrument Framework/Instrument Types/Amplifier/Instrument.Amplifier.lvclass"
File 178="user.lib/LevyLab/Instrument Framework/Instrument Types/Amplifier/setAllChannels.vi"
File 179="user.lib/LevyLab/Instrument Framework/Instrument Types/Amplifier/setChannel.vi"


[File Group 1]
Target Dir="<menus>/Categories/LevyLab/_functions_Levylab_lib_Levylab_Instruments"
Replace Mode="Always"
Num Files=17
File 0="_functions_levylab_lib_instrument_type_1.mnu"
File 1="_functions_levylab_lib_instrument_type_10.mnu"
File 2="_functions_levylab_lib_instrument_type_11.mnu"
File 3="_functions_levylab_lib_instrument_type_12.mnu"
File 4="_functions_levylab_lib_instrument_type_13.mnu"
File 5="_functions_levylab_lib_instrument_type_14.mnu"
File 6="_functions_levylab_lib_instrument_type_15.mnu"
File 7="_functions_levylab_lib_instrument_type_16.mnu"
File 8="_functions_levylab_lib_instrument_type_2.mnu"
File 9="_functions_levylab_lib_instrument_type_3.mnu"
File 10="_functions_levylab_lib_instrument_type_4.mnu"
File 11="_functions_levylab_lib_instrument_type_5.mnu"
File 12="_functions_levylab_lib_instrument_type_6.mnu"
File 13="_functions_levylab_lib_instrument_type_7.mnu"
File 14="_functions_levylab_lib_instrument_type_8.mnu"
File 15="_functions_levylab_lib_instrument_type_9.mnu"
File 16="functions_LevyLab_lib_Instrument_Type.mnu"


[File Group 2]
Target Dir="<menus>/Controls"
Replace Mode="Always"
Num Files=18
File 0="_controls_levylab_lib_instrument_type_1.mnu"
File 1="_controls_levylab_lib_instrument_type_10.mnu"
File 2="_controls_levylab_lib_instrument_type_11.mnu"
File 3="_controls_levylab_lib_instrument_type_12.mnu"
File 4="_controls_levylab_lib_instrument_type_13.mnu"
File 5="_controls_levylab_lib_instrument_type_14.mnu"
File 6="_controls_levylab_lib_instrument_type_15.mnu"
File 7="_controls_levylab_lib_instrument_type_16.mnu"
File 8="_controls_levylab_lib_instrument_type_17.mnu"
File 9="_controls_levylab_lib_instrument_type_2.mnu"
File 10="_controls_levylab_lib_instrument_type_3.mnu"
File 11="_controls_levylab_lib_instrument_type_4.mnu"
File 12="_controls_levylab_lib_instrument_type_5.mnu"
File 13="_controls_levylab_lib_instrument_type_6.mnu"
File 14="_controls_levylab_lib_instrument_type_7.mnu"
File 15="_controls_levylab_lib_instrument_type_8.mnu"
File 16="_controls_levylab_lib_instrument_type_9.mnu"
File 17="controls_LevyLab_lib_Instrument_Type.mnu"
