[Package]
Name="levylab_lib_build_support"
Version="1.11.3.54"
Release=""
ID=2b5e1db1721aec85ea84f171544927f4
File Format="vip"
Format Version="2017"
Display Name="Build Support"


[Description]
Description=" VIs and scripts to help automate package and application builds"
Summary=""
License="BSD-3"
Copyright="Copyright (c) 2026, Levylab"
Distribution=""
Vendor="Levylab"
URL=""
Packager="Patrick Irvin"
Demo="FALSE"
Release Notes="[1.11.3]\0D\0A1. Fixed: the 1.11.2 package shipped VIPM.lvlib with six unresolved merge-conflict markers, leaving the library unloadable. It is clean again, and the duplicate VI entries behind the bad merge are gone.\0D\0A\0D\0A2. build.bat can now build a repo that ships more than one product. Give each product its own <name>.cfg in "build support\\" and name it on the command line: build.bat "<repo root>" release build-support. ".cfg" is appended if you leave it off, build.cfg stays the default when no name is given, and naming a config that does not exist lists the ones that do.\0D\0A\0D\0A3. New TAG_PREFIX config key, prepended to the git tag and the GitHub release name, so two products released from one repo no longer collide in a single tag space. Empty by default, which keeps the bare version tag every single-product repo already uses. Avoid a '/' in the prefix for a product that ships the SelfUpdate class: SelfUpdate rebuilds the tag from the last path component of the releases/latest redirect and re-requests releases/tag/<that>, so a slash makes the round-trip 404.\0D\0A\0D\0A4. build.bat takes an optional release/test argument that overrides the config's DO_RELEASE for a single run - "release" runs the git release, "test" builds without touching git. It and the config name are arguments 2 and 3 and may be given in either order.\0D\0A\0D\0A5. The release tag is now pushed as refs/tags/<tag>, so a prefixed tag containing a slash cannot be read as a branch name.\0D\0A\0D\0A6. Fixed a double build-number bump, and moved the bump ahead of the release. The script's own bump now runs only when BUILD_VIP=false; when the package itself is built the bump is left to VIPM's vipBuild rather than being applied twice. Both bumps now happen before the git release, so the release commit carries the bumped vipb instead of leaving it dirty for a manual follow-up commit. The tag and the built artifact keep the version as built.\0D\0A\0D\0A7. Build documentation updated throughout: the config-key table covers TAG_PREFIX, the build steps describe the new arguments, and there is a new section on repos that ship more than one product.\0D\0A\0D\0A8. Fixed: the GitHub release now carries the .vip. The vipb writes the package to its Library_Output_Folder (builds\\Package), but the release step only collected assets from builds\\latest, so no release ever had a .vip attached - and a package-only product, which builds no installer, would have been released with no assets at all. The built package is now staged into builds\\latest and the script says which file it staged, or warns if it found none.\0D\0A\0D\0A9. Fixed: build.bat can now release the repo it lives in. The release step checks out other branches, which rewrote the running script; cmd.exe reads a batch file by byte offset, so execution resumed mid-line and ran unrelated fragments - in one case compiling an Inno installer for a package-only product. When the script detects it is inside the repo being built it now re-runs from a copy in TEMP. Only the build-support repo hits this; the installed copy in %LOCALAPPDATA% was never affected.\0D\0A\0D\0A10. Fixed: every build printed "The filename, directory name, or volume label syntax is incorrect" while archiving the previous release. The guard was "if exist builds\\latest\\*.*", which is true even for an empty directory because the wildcard matches the . and .. entries, so move ran with nothing to move and failed. The guard is now a for wildcard, which matches real files only. Archiving itself always worked when there was something to archive; the message was noise."
System Package="FALSE"
Sub Package="FALSE"
License Agreement="TRUE"


[LabVIEW]
close labview before install="FALSE"
restart labview after install="FALSE"
skip mass compile after install="FALSE"
install into global environment="FALSE"


[Platform]
Exclusive_LabVIEW_Version="LabVIEW>=19.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="ALL"


[Script VIs]
PreInstall=""
PostInstall="<OS User Documents>\\GitHub\\levylabpitt\\build-support\\build support\\Post-Install Custom Action.vi"
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires="levylab_lib_progress_bar>=1.0.0.1,wiresmith_technology_lib_g_cli>=3.0.1.98,wiresmith_technology_lib_g_cli_labview_builder>=0.2.0.9,wiresmith_technology_lib_g_cli_vi_package_manager_tools>=0.2.1.15,Levylab_lib_Build_Support_system=1.11.3.54"
Conflicts=""


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="3"
Sub-Packages="levylab_lib_build_support_system-1.11.3.54"
Namespaces=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=177
File 0="vi.lib/G CLI Tools/g-cli.noVIPM.lvlib"
File 1="vi.lib/G CLI Tools/noVIPM_IncrementBuild.vi"
File 2="vi.lib/G CLI Tools/noVIPM_PostBuild.vi"
File 3="user.lib/Levylab/Build Support/VIPM/Append to Change Log.vi"
File 4="user.lib/Levylab/Build Support/VIPM/Clear Change Log.vi"
File 5="user.lib/Levylab/Build Support/VIPM/Format Build Spec Summary.vi"
File 6="user.lib/Levylab/Build Support/VIPM/Increment Version Build.vi"
File 7="user.lib/Levylab/Build Support/VIPM/Increment Version Major.vi"
File 8="user.lib/Levylab/Build Support/VIPM/Increment Version Minor.vi"
File 9="user.lib/Levylab/Build Support/VIPM/Increment Version Patch.vi"
File 10="user.lib/Levylab/Build Support/VIPM/LabVIEW_Version to LV_VERS and LV_BIT.vi"
File 11="user.lib/Levylab/Build Support/VIPM/Read Library_Name from VIPB.vi"
File 12="user.lib/Levylab/Build Support/VIPM/Read Library_Output_Folder from VIPB.vi"
File 13="user.lib/Levylab/Build Support/VIPM/Read Library_Source_Folder from VIPB.vi"
File 14="user.lib/Levylab/Build Support/VIPM/Read Library_Version from VIPB.vi"
File 15="user.lib/Levylab/Build Support/VIPM/Read Node from VIPB.vi"
File 16="user.lib/Levylab/Build Support/VIPM/Read Package_LabVIEW_Version from VIPB.vi"
File 17="user.lib/Levylab/Build Support/VIPM/Read Post Build VI from VIPB.vi"
File 18="user.lib/Levylab/Build Support/VIPM/Read Product_Name from VIPB.vi"
File 19="user.lib/Levylab/Build Support/VIPM/Read Targets from VIPM Settings.vi"
File 20="user.lib/Levylab/Build Support/VIPM/VIPB to VIPM variant.vi"
File 21="user.lib/Levylab/Build Support/VIPM/VIPM.lvlib"
File 22="user.lib/Levylab/Build Support/VIPM/Write Library_Version to VIPB.vi"
File 23="user.lib/Levylab/Build Support/VIPM/Write Node to VIPB.vi"
File 24="user.lib/Levylab/Build Support/VI Templates/Post-Build Custom Action.vit"
File 25="user.lib/Levylab/Build Support/VI Templates/Post-Install Custom Action.vit"
File 26="user.lib/Levylab/Build Support/VI Templates/Pre-Build Custom Action.vit"
File 27="user.lib/Levylab/Build Support/SelfUpdate/SelfUpdate.lvclass"
File 28="user.lib/Levylab/Build Support/SelfUpdate/private/Default Repo.vi"
File 29="user.lib/Levylab/Build Support/SelfUpdate/private/Default User.vi"
File 30="user.lib/Levylab/Build Support/SelfUpdate/private/Update Dialog.vi"
File 31="user.lib/Levylab/Build Support/SelfUpdate/example/Self Update Example.vi"
File 32="user.lib/Levylab/Build Support/SelfUpdate/API/Dialog.vi"
File 33="user.lib/Levylab/Build Support/SelfUpdate/API/Download and Run Installer.vi"
File 34="user.lib/Levylab/Build Support/SelfUpdate/API/Get Latest Release Version.vi"
File 35="user.lib/Levylab/Build Support/SelfUpdate/API/Get Path to Latest Installer.vi"
File 36="user.lib/Levylab/Build Support/SelfUpdate/API/Set User and Repository.vi"
File 37="user.lib/Levylab/Build Support/ProjectItem/ProjectItem.lvclass"
File 38="user.lib/Levylab/Build Support/ProjectItem/Typedefs/ClassData--Cluster.ctl"
File 39="user.lib/Levylab/Build Support/ProjectItem/Protected/Close.vi"
File 40="user.lib/Levylab/Build Support/ProjectItem/Protected/Delete Empty Folders.vi"
File 41="user.lib/Levylab/Build Support/ProjectItem/Protected/Initialize.vi"
File 42="user.lib/Levylab/Build Support/ProjectItem/Protected/List Classes.vi"
File 43="user.lib/Levylab/Build Support/ProjectItem/Protected/List Project.vi"
File 44="user.lib/Levylab/Build Support/ProjectItem/Protected/List Typedefs.vi"
File 45="user.lib/Levylab/Build Support/ProjectItem/Protected/List VIs.vi"
File 46="user.lib/Levylab/Build Support/ProjectItem/Protected/Rename Classes.vi"
File 47="user.lib/Levylab/Build Support/ProjectItem/Protected/Rename Constants.vi"
File 48="user.lib/Levylab/Build Support/ProjectItem/Protected/Rename Controls.vi"
File 49="user.lib/Levylab/Build Support/ProjectItem/Protected/Rename GObjects.vi"
File 50="user.lib/Levylab/Build Support/ProjectItem/Protected/Rename Project.vi"
File 51="user.lib/Levylab/Build Support/ProjectItem/Protected/Rename Typedefs.vi"
File 52="user.lib/Levylab/Build Support/ProjectItem/Protected/Rename VIs.vi"
File 53="user.lib/Levylab/Build Support/ProjectItem/Protected/Save All.vi"
File 54="user.lib/Levylab/Build Support/ProjectItem/Protected/Update Class Icon.vi"
File 55="user.lib/Levylab/Build Support/ProjectItem/Protected/Update Class Wire Appearance.vi"
File 56="user.lib/Levylab/Build Support/ProjectItem/Protected/Update Icon Preview.vi"
File 57="user.lib/Levylab/Build Support/ProjectItem/Protected/Write Icon Data.vi"
File 58="user.lib/Levylab/Build Support/ProjectItem/Protected/Write Wire Color Data.vi"
File 59="user.lib/Levylab/Build Support/ProjectItem/Private/Delete File and Folder.vi"
File 60="user.lib/Levylab/Build Support/ProjectItem/Private/Escape Brackets.vi"
File 61="user.lib/Levylab/Build Support/ProjectItem/Private/Is UI.vi"
File 62="user.lib/Levylab/Build Support/ProjectItem/Private/Update Label.vi"
File 63="user.lib/Levylab/Build Support/ProjectItem/Private/Update Path.vi"
File 64="user.lib/Levylab/Build Support/ProjectItem/API/Choose Build Spec.vi"
File 65="user.lib/Levylab/Build Support/ProjectItem/API/Instrument Name and Icon UI.vi"
File 66="user.lib/Levylab/Build Support/ProjectItem/API/List Project Build Specifications.vi"
File 67="user.lib/Levylab/Build Support/ProjectItem/API/Rename items.vi"
File 68="user.lib/Levylab/Build Support/Private/7zSD.sfx"
File 69="user.lib/Levylab/Build Support/PreBuildSupport/rename to VIPT.vi"
File 70="user.lib/Levylab/Build Support/PreBuildSupport/VIPT to rename.vi"
File 71="user.lib/Levylab/Build Support/PreBuildSupport/subVI/Find File By Name.vi"
File 72="user.lib/Levylab/Build Support/PostBuildSupport/PostBuildSupport.lvclass"
File 73="user.lib/Levylab/Build Support/PostBuildSupport/Test/Test 7z.bat.vi"
File 74="user.lib/Levylab/Build Support/PostBuildSupport/Private/Auto Build Script.vi"
File 75="user.lib/Levylab/Build Support/PostBuildSupport/Private/Build Application G-CLI.vi"
File 76="user.lib/Levylab/Build Support/PostBuildSupport/Private/Build Application with API.vi"
File 77="user.lib/Levylab/Build Support/PostBuildSupport/Private/Build Application.vi"
File 78="user.lib/Levylab/Build Support/PostBuildSupport/Private/Build Installer G-CLI.vi"
File 79="user.lib/Levylab/Build Support/PostBuildSupport/Private/Build Installer with API.vi"
File 80="user.lib/Levylab/Build Support/PostBuildSupport/Private/Build Installer.vi"
File 81="user.lib/Levylab/Build Support/PostBuildSupport/Private/Build VIPB G-CLI.vi"
File 82="user.lib/Levylab/Build Support/PostBuildSupport/Private/CMD Build Bat.vi"
File 83="user.lib/Levylab/Build Support/PostBuildSupport/Private/CMD tasklist.vi"
File 84="user.lib/Levylab/Build Support/PostBuildSupport/Private/Copy 7zSD.SFX.vi"
File 85="user.lib/Levylab/Build Support/PostBuildSupport/Private/Copy Package.vi"
File 86="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create 7z config.vi"
File 87="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create 7z.bat Script.vi"
File 88="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create CLI Script quitLabVIEW.vi"
File 89="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create Folders.vi"
File 90="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create G-CLI Script ClearCache.vi"
File 91="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create G-CLI Script lvBuild Applicationion.vi"
File 92="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create G-CLI Script lvBuild Installer.vi"
File 93="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create G-CLI Script vipBuild.vi"
File 94="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create G-CLI Script VIPCApply.vi"
File 95="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create G-CLI Script VIPInstall.vi"
File 96="user.lib/Levylab/Build Support/PostBuildSupport/Private/Execute 7z bat.vi"
File 97="user.lib/Levylab/Build Support/PostBuildSupport/Private/Get Installed 7z.vi"
File 98="user.lib/Levylab/Build Support/PostBuildSupport/Private/Open Project.vi"
File 99="user.lib/Levylab/Build Support/PostBuildSupport/Private/Update Build Version.vi"
File 100="user.lib/Levylab/Build Support/PostBuildSupport/Private/Version String to Build Spec Version.vi"
File 101="user.lib/Levylab/Build Support/PostBuildSupport/Private/Write 7z config.vi"
File 102="user.lib/Levylab/Build Support/PostBuildSupport/Private/Write 7z.bat.vi"
File 103="user.lib/Levylab/Build Support/PostBuildSupport/API/Post Build Script (auto build).vi"
File 104="user.lib/Levylab/Build Support/PostBuildSupport/API/Post Build Script (G-CLI build).vi"
File 105="user.lib/Levylab/Build Support/PostBuildSupport/API/Post Build Script (manual build).vi"
File 106="user.lib/Levylab/Build Support/Git/Git.lvclass"
File 107="user.lib/Levylab/Build Support/Git/Typedefs/Branches.git-flow--combo.ctl"
File 108="user.lib/Levylab/Build Support/Git/Typedefs/Commands.gh--combo.ctl"
File 109="user.lib/Levylab/Build Support/Git/Typedefs/Commands.git--combo.ctl"
File 110="user.lib/Levylab/Build Support/Git/Typedefs/Commands.git-flow--combo.ctl"
File 111="user.lib/Levylab/Build Support/Git/Sandbox/Git Examine Config.vi"
File 112="user.lib/Levylab/Build Support/Git/Sandbox/Git sandbox.vi"
File 113="user.lib/Levylab/Build Support/Git/Sandbox/Test Git Macro.vi"
File 114="user.lib/Levylab/Build Support/Git/Sandbox/Test Git.vi"
File 115="user.lib/Levylab/Build Support/Git/Sandbox/Untitled 4.vi"
File 116="user.lib/Levylab/Build Support/Git/private/CLI.gh.vi"
File 117="user.lib/Levylab/Build Support/Git/private/CLI.git-flow.vi"
File 118="user.lib/Levylab/Build Support/Git/private/CLI.git.vi"
File 119="user.lib/Levylab/Build Support/Git/private/Delete Empty Lines.vi"
File 120="user.lib/Levylab/Build Support/Git/private/Error Handler.vi"
File 121="user.lib/Levylab/Build Support/Git/private/Find Most Recent File.vi"
File 122="user.lib/Levylab/Build Support/Git/private/Parse Branch Return.vi"
File 123="user.lib/Levylab/Build Support/Git/private/Verify Git.vi"
File 124="user.lib/Levylab/Build Support/Git/private/Verify Repository Path.vi"
File 125="user.lib/Levylab/Build Support/Git/private/Walk Down to Latest Build.vi"
File 126="user.lib/Levylab/Build Support/Git/API/gh-cli Auth Login.vi"
File 127="user.lib/Levylab/Build Support/Git/API/gh-cli Issue List.vi"
File 128="user.lib/Levylab/Build Support/Git/API/gh-cli Release Create.vi"
File 129="user.lib/Levylab/Build Support/Git/API/gh-cli Release List.vi"
File 130="user.lib/Levylab/Build Support/Git/API/gh-cli Release Upload.vi"
File 131="user.lib/Levylab/Build Support/Git/API/gh-cli Release View.vi"
File 132="user.lib/Levylab/Build Support/Git/API/gh-cli Version.vi"
File 133="user.lib/Levylab/Build Support/Git/API/Git Branch.vi"
File 134="user.lib/Levylab/Build Support/Git/API/Git Commit.vi"
File 135="user.lib/Levylab/Build Support/Git/API/Git Config.vi"
File 136="user.lib/Levylab/Build Support/Git/API/Git Flow Config.vi"
File 137="user.lib/Levylab/Build Support/Git/API/Git Flow Delete.vi"
File 138="user.lib/Levylab/Build Support/Git/API/Git Flow Finish.vi"
File 139="user.lib/Levylab/Build Support/Git/API/Git Flow Publish.vi"
File 140="user.lib/Levylab/Build Support/Git/API/Git Flow Rebase.vi"
File 141="user.lib/Levylab/Build Support/Git/API/Git Flow Start Bugfix.vi"
File 142="user.lib/Levylab/Build Support/Git/API/Git Flow Start Feature.vi"
File 143="user.lib/Levylab/Build Support/Git/API/Git Flow Start Hotfix.vi"
File 144="user.lib/Levylab/Build Support/Git/API/Git Flow Start Release.vi"
File 145="user.lib/Levylab/Build Support/Git/API/Git Flow Start Support.vi"
File 146="user.lib/Levylab/Build Support/Git/API/Git Flow Version.vi"
File 147="user.lib/Levylab/Build Support/Git/API/Git Status.vi"
File 148="user.lib/Levylab/Build Support/Git/API/Macro Add.vi"
File 149="user.lib/Levylab/Build Support/Git/API/Macro Commit.vi"
File 150="user.lib/Levylab/Build Support/Git/API/Macro Finish Release.vi"
File 151="user.lib/Levylab/Build Support/Git/API/Macro Init.vi"
File 152="user.lib/Levylab/Build Support/Git/API/Macro Push and Push Tags.vi"
File 153="user.lib/Levylab/Build Support/Git/API/Macro Start Release.vi"
File 154="user.lib/Levylab/Build Support/Git/API/Walk Up to Repository.vi"
File 155="user.lib/Levylab/Build Support/Git/API/Write Repository Path.vi"
File 156="user.lib/Levylab/Build Support/Git/API/Write Simulate.vi"
File 157="user.lib/Levylab/Build Support/config/instrument-framework-lvproj.txt"
File 158="user.lib/Levylab/Build Support/config/instrument-vipb--lockin.txt"
File 159="user.lib/Levylab/Build Support/config/instrument-vipb.txt"
File 160="user.lib/Levylab/Build Support/config/instruments-lvproj.txt"
File 161="user.lib/Levylab/Build Support/config/transport-framework-lvproj.txt"
File 162="user.lib/Levylab/Build Support/CLI/.NET Terminal.vi"
File 163="user.lib/Levylab/Build Support/CLI/Status.vi"
File 164="user.lib/Levylab/Build Support/CLI/Tests/Test .NET Terminal.vi"
File 165="user.lib/Levylab/Build Support/Build/Build.lvlib"
File 166="user.lib/Levylab/Build Support/Build/Create build_all.bat.vi"
File 167="user.lib/Levylab/Build Support/Build/Edit Text File.vi"
File 168="user.lib/Levylab/Build Support/Build/Extension to Mode.vi"
File 169="user.lib/Levylab/Build Support/Build/File List Window 2.vi"
File 170="user.lib/Levylab/Build Support/Build/File List Window.vi"
File 171="user.lib/Levylab/Build Support/Build/Initialize Repository.vi"
File 172="user.lib/Levylab/Build Support/Build/Patrick Builder.vi"
File 173="user.lib/Levylab/Build Support/Build/Publish Packages to Package Repository.vi"
File 174="user.lib/Levylab/Build Support/Build/Typedefs/Build Spec Type--combo.ctl"
File 175="user.lib/Levylab/Build Support/Build/Typedefs/Build Spec--cluster.ctl"
File 176="user.lib/Levylab/Build Support/Build/Typedefs/Build Type--enum.ctl"


[File Group 1]
Target Dir="<menus>/Categories/Levylab"
Replace Mode="Always"
Num Files=17
File 0="_functions_levylab_lib_build_support_1.mnu"
File 1="_functions_levylab_lib_build_support_10.mnu"
File 2="_functions_levylab_lib_build_support_11.mnu"
File 3="_functions_levylab_lib_build_support_12.mnu"
File 4="_functions_levylab_lib_build_support_13.mnu"
File 5="_functions_levylab_lib_build_support_14.mnu"
File 6="_functions_levylab_lib_build_support_15.mnu"
File 7="_functions_levylab_lib_build_support_16.mnu"
File 8="_functions_levylab_lib_build_support_2.mnu"
File 9="_functions_levylab_lib_build_support_3.mnu"
File 10="_functions_levylab_lib_build_support_4.mnu"
File 11="_functions_levylab_lib_build_support_5.mnu"
File 12="_functions_levylab_lib_build_support_6.mnu"
File 13="_functions_levylab_lib_build_support_7.mnu"
File 14="_functions_levylab_lib_build_support_8.mnu"
File 15="_functions_levylab_lib_build_support_9.mnu"
File 16="functions_Levylab_lib_Build_Support.mnu"


[File Group 2]
Target Dir="<menus>/Categories/Levylab"
Replace Mode="If Newer"
Num Files=1
File 0="dir.mnu"
