[Package]
Name="levylab_lib_build_support"
Version="1.8.2.30"
Release=""
ID=46a03fbbf9361a2a9f08fb05c18d3690
File Format="vip"
Format Version="2017"
Display Name="Build Support"


[Description]
Description="Miscellaneous VIs help build applications and packages"
Summary=""
License="BSD-3"
Copyright="Copyright (c) 2026, Levylab"
Distribution=""
Vendor="Levylab"
URL=""
Packager="Patrick Irvin"
Demo="FALSE"
Release Notes="[1.8.2]\0Aupdate template to better handle git branches"
System Package="FALSE"
Sub Package="FALSE"
License Agreement="TRUE"


[LabVIEW]
close labview before install="FALSE"
restart labview after install="FALSE"
skip mass compile after install="FALSE"
install into global environment="FALSE"


[Platform]
Exclusive_LabVIEW_Version="LabVIEW>=19.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="ALL"


[Script VIs]
PreInstall=""
PostInstall=""
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires="jki_lib_vipm_api>=2020.0.3.80,wiresmith_technology_lib_g_cli>=3.0.1.98,levylab_lib_progress_bar>=1.0.0.1,Levylab_lib_Build_Support_system=1.8.2.30"
Conflicts=""


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="3"
Sub-Packages="levylab_lib_build_support_system-1.8.2.30"
Namespaces=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=169
File 0="user.lib/Levylab/Build Support/VIPM/Append to Change Log.vi"
File 1="user.lib/Levylab/Build Support/VIPM/Clear Change Log.vi"
File 2="user.lib/Levylab/Build Support/VIPM/Create build_vip.bat.vi"
File 3="user.lib/Levylab/Build Support/VIPM/Format Build Spec Summary.vi"
File 4="user.lib/Levylab/Build Support/VIPM/Increment Version Minor.vi"
File 5="user.lib/Levylab/Build Support/VIPM/Increment Version Patch.vi"
File 6="user.lib/Levylab/Build Support/VIPM/LabVIEW_Version to LV_VERS and LV_BIT.vi"
File 7="user.lib/Levylab/Build Support/VIPM/Read Package_LabVIEW_Version from VIPB.vi"
File 8="user.lib/Levylab/Build Support/VIPM/Read Targets from VIPM Settings.vi"
File 9="user.lib/Levylab/Build Support/VIPM/VIPM.lvlib"
File 10="user.lib/Levylab/Build Support/VI Templates/Post-Build Custom Action.vit"
File 11="user.lib/Levylab/Build Support/VI Templates/Post-Install Custom Action.vit"
File 12="user.lib/Levylab/Build Support/VI Templates/Pre-Build Custom Action.vit"
File 13="user.lib/Levylab/Build Support/SelfUpdate/SelfUpdate.lvclass"
File 14="user.lib/Levylab/Build Support/SelfUpdate/private/Default Repo.vi"
File 15="user.lib/Levylab/Build Support/SelfUpdate/private/Default User.vi"
File 16="user.lib/Levylab/Build Support/SelfUpdate/private/Update Dialog.vi"
File 17="user.lib/Levylab/Build Support/SelfUpdate/example/Self Update Example.vi"
File 18="user.lib/Levylab/Build Support/SelfUpdate/API/Dialog.vi"
File 19="user.lib/Levylab/Build Support/SelfUpdate/API/Download and Run Installer.vi"
File 20="user.lib/Levylab/Build Support/SelfUpdate/API/Get Latest Release Version.vi"
File 21="user.lib/Levylab/Build Support/SelfUpdate/API/Get Path to Latest Installer.vi"
File 22="user.lib/Levylab/Build Support/SelfUpdate/API/Set User and Repository.vi"
File 23="user.lib/Levylab/Build Support/ProjectItem/ProjectItem.lvclass"
File 24="user.lib/Levylab/Build Support/ProjectItem/Typedefs/ClassData--Cluster.ctl"
File 25="user.lib/Levylab/Build Support/ProjectItem/Protected/Close.vi"
File 26="user.lib/Levylab/Build Support/ProjectItem/Protected/Delete Empty Folders.vi"
File 27="user.lib/Levylab/Build Support/ProjectItem/Protected/Initialize.vi"
File 28="user.lib/Levylab/Build Support/ProjectItem/Protected/List Classes.vi"
File 29="user.lib/Levylab/Build Support/ProjectItem/Protected/List Project.vi"
File 30="user.lib/Levylab/Build Support/ProjectItem/Protected/List Typedefs.vi"
File 31="user.lib/Levylab/Build Support/ProjectItem/Protected/List VIs.vi"
File 32="user.lib/Levylab/Build Support/ProjectItem/Protected/Rename Classes.vi"
File 33="user.lib/Levylab/Build Support/ProjectItem/Protected/Rename Constants.vi"
File 34="user.lib/Levylab/Build Support/ProjectItem/Protected/Rename Controls.vi"
File 35="user.lib/Levylab/Build Support/ProjectItem/Protected/Rename GObjects.vi"
File 36="user.lib/Levylab/Build Support/ProjectItem/Protected/Rename Project.vi"
File 37="user.lib/Levylab/Build Support/ProjectItem/Protected/Rename Typedefs.vi"
File 38="user.lib/Levylab/Build Support/ProjectItem/Protected/Rename VIs.vi"
File 39="user.lib/Levylab/Build Support/ProjectItem/Protected/Save All.vi"
File 40="user.lib/Levylab/Build Support/ProjectItem/Protected/Update Class Icon.vi"
File 41="user.lib/Levylab/Build Support/ProjectItem/Protected/Update Class Wire Appearance.vi"
File 42="user.lib/Levylab/Build Support/ProjectItem/Protected/Update Icon Preview.vi"
File 43="user.lib/Levylab/Build Support/ProjectItem/Protected/Write Icon Data.vi"
File 44="user.lib/Levylab/Build Support/ProjectItem/Protected/Write Wire Color Data.vi"
File 45="user.lib/Levylab/Build Support/ProjectItem/Private/Delete File and Folder.vi"
File 46="user.lib/Levylab/Build Support/ProjectItem/Private/Escape Brackets.vi"
File 47="user.lib/Levylab/Build Support/ProjectItem/Private/Is UI.vi"
File 48="user.lib/Levylab/Build Support/ProjectItem/Private/Update Label.vi"
File 49="user.lib/Levylab/Build Support/ProjectItem/Private/Update Path.vi"
File 50="user.lib/Levylab/Build Support/ProjectItem/API/Choose Build Spec.vi"
File 51="user.lib/Levylab/Build Support/ProjectItem/API/Instrument Name and Icon UI.vi"
File 52="user.lib/Levylab/Build Support/ProjectItem/API/List Project Build Specifications.vi"
File 53="user.lib/Levylab/Build Support/ProjectItem/API/Rename items.vi"
File 54="user.lib/Levylab/Build Support/PreBuildSupport/rename to VIPT.vi"
File 55="user.lib/Levylab/Build Support/PreBuildSupport/VIPT to rename.vi"
File 56="user.lib/Levylab/Build Support/PreBuildSupport/subVI/Find File By Name.vi"
File 57="user.lib/Levylab/Build Support/PostBuildSupport/PostBuildSupport.lvclass"
File 58="user.lib/Levylab/Build Support/PostBuildSupport/Test/Test 7z.bat.vi"
File 59="user.lib/Levylab/Build Support/PostBuildSupport/Private/7zSD.sfx"
File 60="user.lib/Levylab/Build Support/PostBuildSupport/Private/Auto Build Script.vi"
File 61="user.lib/Levylab/Build Support/PostBuildSupport/Private/Build Application G-CLI.vi"
File 62="user.lib/Levylab/Build Support/PostBuildSupport/Private/Build Application with API.vi"
File 63="user.lib/Levylab/Build Support/PostBuildSupport/Private/Build Application.vi"
File 64="user.lib/Levylab/Build Support/PostBuildSupport/Private/Build Installer G-CLI.vi"
File 65="user.lib/Levylab/Build Support/PostBuildSupport/Private/Build Installer with API.vi"
File 66="user.lib/Levylab/Build Support/PostBuildSupport/Private/Build Installer.vi"
File 67="user.lib/Levylab/Build Support/PostBuildSupport/Private/Build VIPB G-CLI.vi"
File 68="user.lib/Levylab/Build Support/PostBuildSupport/Private/CMD Build Bat.vi"
File 69="user.lib/Levylab/Build Support/PostBuildSupport/Private/CMD tasklist.vi"
File 70="user.lib/Levylab/Build Support/PostBuildSupport/Private/Copy 7zSD.SFX.vi"
File 71="user.lib/Levylab/Build Support/PostBuildSupport/Private/Copy Package.vi"
File 72="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create 7z config.vi"
File 73="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create 7z.bat Script.vi"
File 74="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create CLI Script quitLabVIEW.vi"
File 75="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create Folders.vi"
File 76="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create G-CLI Script ClearCache.vi"
File 77="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create G-CLI Script lvBuild Applicationion.vi"
File 78="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create G-CLI Script lvBuild Installer.vi"
File 79="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create G-CLI Script vipBuild.vi"
File 80="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create G-CLI Script VIPCApply.vi"
File 81="user.lib/Levylab/Build Support/PostBuildSupport/Private/Create G-CLI Script VIPInstall.vi"
File 82="user.lib/Levylab/Build Support/PostBuildSupport/Private/Execute 7z bat.vi"
File 83="user.lib/Levylab/Build Support/PostBuildSupport/Private/Get Installed 7z.vi"
File 84="user.lib/Levylab/Build Support/PostBuildSupport/Private/Open Project.vi"
File 85="user.lib/Levylab/Build Support/PostBuildSupport/Private/Update Build Version.vi"
File 86="user.lib/Levylab/Build Support/PostBuildSupport/Private/Version String to Build Spec Version.vi"
File 87="user.lib/Levylab/Build Support/PostBuildSupport/Private/Write 7z config.vi"
File 88="user.lib/Levylab/Build Support/PostBuildSupport/Private/Write 7z.bat.vi"
File 89="user.lib/Levylab/Build Support/PostBuildSupport/API/Post Build Script (auto build).vi"
File 90="user.lib/Levylab/Build Support/PostBuildSupport/API/Post Build Script (G-CLI build).vi"
File 91="user.lib/Levylab/Build Support/PostBuildSupport/API/Post Build Script (manual build).vi"
File 92="user.lib/Levylab/Build Support/Git/Git.lvclass"
File 93="user.lib/Levylab/Build Support/Git/Typedefs/Branches.git-flow--combo.ctl"
File 94="user.lib/Levylab/Build Support/Git/Typedefs/Commands.gh--combo.ctl"
File 95="user.lib/Levylab/Build Support/Git/Typedefs/Commands.git--combo.ctl"
File 96="user.lib/Levylab/Build Support/Git/Typedefs/Commands.git-flow--combo.ctl"
File 97="user.lib/Levylab/Build Support/Git/Sandbox/Git Examine Config.vi"
File 98="user.lib/Levylab/Build Support/Git/Sandbox/Git sandbox.vi"
File 99="user.lib/Levylab/Build Support/Git/Sandbox/Test Git Macro.vi"
File 100="user.lib/Levylab/Build Support/Git/Sandbox/Test Git.vi"
File 101="user.lib/Levylab/Build Support/Git/Sandbox/Untitled 4.vi"
File 102="user.lib/Levylab/Build Support/Git/private/CLI.gh.vi"
File 103="user.lib/Levylab/Build Support/Git/private/CLI.git-flow.vi"
File 104="user.lib/Levylab/Build Support/Git/private/CLI.git.vi"
File 105="user.lib/Levylab/Build Support/Git/private/Delete Empty Lines.vi"
File 106="user.lib/Levylab/Build Support/Git/private/Error Handler.vi"
File 107="user.lib/Levylab/Build Support/Git/private/Find Most Recent File.vi"
File 108="user.lib/Levylab/Build Support/Git/private/Parse Branch Return.vi"
File 109="user.lib/Levylab/Build Support/Git/private/Verify Git.vi"
File 110="user.lib/Levylab/Build Support/Git/private/Verify Repository Path.vi"
File 111="user.lib/Levylab/Build Support/Git/private/Walk Down to Latest Build.vi"
File 112="user.lib/Levylab/Build Support/Git/private/Walk Up to Repository.vi"
File 113="user.lib/Levylab/Build Support/Git/API/gh-cli Auth Login.vi"
File 114="user.lib/Levylab/Build Support/Git/API/gh-cli Issue List.vi"
File 115="user.lib/Levylab/Build Support/Git/API/gh-cli Release Create.vi"
File 116="user.lib/Levylab/Build Support/Git/API/gh-cli Release List.vi"
File 117="user.lib/Levylab/Build Support/Git/API/gh-cli Release Upload.vi"
File 118="user.lib/Levylab/Build Support/Git/API/gh-cli Release View.vi"
File 119="user.lib/Levylab/Build Support/Git/API/gh-cli Version.vi"
File 120="user.lib/Levylab/Build Support/Git/API/Git Branch.vi"
File 121="user.lib/Levylab/Build Support/Git/API/Git Commit.vi"
File 122="user.lib/Levylab/Build Support/Git/API/Git Config.vi"
File 123="user.lib/Levylab/Build Support/Git/API/Git Flow Config.vi"
File 124="user.lib/Levylab/Build Support/Git/API/Git Flow Delete.vi"
File 125="user.lib/Levylab/Build Support/Git/API/Git Flow Finish.vi"
File 126="user.lib/Levylab/Build Support/Git/API/Git Flow Publish.vi"
File 127="user.lib/Levylab/Build Support/Git/API/Git Flow Rebase.vi"
File 128="user.lib/Levylab/Build Support/Git/API/Git Flow Start Bugfix.vi"
File 129="user.lib/Levylab/Build Support/Git/API/Git Flow Start Feature.vi"
File 130="user.lib/Levylab/Build Support/Git/API/Git Flow Start Hotfix.vi"
File 131="user.lib/Levylab/Build Support/Git/API/Git Flow Start Release.vi"
File 132="user.lib/Levylab/Build Support/Git/API/Git Flow Start Support.vi"
File 133="user.lib/Levylab/Build Support/Git/API/Git Flow Version.vi"
File 134="user.lib/Levylab/Build Support/Git/API/Git Status.vi"
File 135="user.lib/Levylab/Build Support/Git/API/Macro Add.vi"
File 136="user.lib/Levylab/Build Support/Git/API/Macro Commit.vi"
File 137="user.lib/Levylab/Build Support/Git/API/Macro Finish Release.vi"
File 138="user.lib/Levylab/Build Support/Git/API/Macro Init.vi"
File 139="user.lib/Levylab/Build Support/Git/API/Macro Push and Push Tags.vi"
File 140="user.lib/Levylab/Build Support/Git/API/Macro Start Release.vi"
File 141="user.lib/Levylab/Build Support/Git/API/Write Repository Path.vi"
File 142="user.lib/Levylab/Build Support/Git/API/Write Simulate.vi"
File 143="user.lib/Levylab/Build Support/CLI/.NET Terminal.vi"
File 144="user.lib/Levylab/Build Support/CLI/Status.vi"
File 145="user.lib/Levylab/Build Support/CLI/Tests/Test .NET Terminal.vi"
File 146="user.lib/Levylab/Build Support/Build Templates/Build Application and Installer.vi"
File 147="user.lib/Levylab/Build Support/Build Templates/buildWithGCLI.vi"
File 148="user.lib/Levylab/Build Support/Build Templates/Manual Build SM.vi"
File 149="user.lib/Levylab/Build Support/Build Templates/Manual Build.vi"
File 150="user.lib/Levylab/Build Support/Build/Build.lvlib"
File 151="user.lib/Levylab/Build Support/Build/CLI_build.bat"
File 152="user.lib/Levylab/Build Support/Build/Create build_all.bat.vi"
File 153="user.lib/Levylab/Build Support/Build/Extension to Mode.vi"
File 154="user.lib/Levylab/Build Support/Build/File List Window.vi"
File 155="user.lib/Levylab/Build Support/Build/Patrick Builder.vi"
File 156="user.lib/Levylab/Build Support/Build/Publish Packages to Package Repositoryvi.vi"
File 157="user.lib/Levylab/Build Support/Build/Typedefs/Build Spec Type--combo.ctl"
File 158="user.lib/Levylab/Build Support/Build/Typedefs/Build Spec--cluster.ctl"
File 159="user.lib/Levylab/Build Support/Build/Typedefs/Build Type--enum.ctl"
File 160="user.lib/Levylab/Build Support/Build/config/instrument-framework-lvproj.txt"
File 161="user.lib/Levylab/Build Support/Build/config/instrument-vipb--lockin.txt"
File 162="user.lib/Levylab/Build Support/Build/config/instrument-vipb.txt"
File 163="user.lib/Levylab/Build Support/Build/config/instruments-lvproj.txt"
File 164="user.lib/Levylab/Build Support/Build/config/transport-framework-lvproj.txt"
File 165="user.lib/Levylab/_Build Support_internal_deps/066FE7A400D914C7F921F08481BF06BBCONSTANT - VIP API Version.vi"
File 166="user.lib/Levylab/_Build Support_internal_deps/066FE7A400D914C7F921F08481BF06BBGet VIP Builder Config.vi"
File 167="user.lib/Levylab/_Build Support_internal_deps/066FE7A400D914C7F921F08481BF06BBUpdate VIPB Version.vi"
File 168="user.lib/Levylab/_Build Support_internal_deps/066FE7A400D914C7F921F08481BF06BBVIPBuild.vi"


[File Group 1]
Target Dir="<menus>/Categories/Levylab"
Replace Mode="Always"
Num Files=18
File 0="_functions_levylab_lib_build_support_1.mnu"
File 1="_functions_levylab_lib_build_support_10.mnu"
File 2="_functions_levylab_lib_build_support_11.mnu"
File 3="_functions_levylab_lib_build_support_12.mnu"
File 4="_functions_levylab_lib_build_support_13.mnu"
File 5="_functions_levylab_lib_build_support_14.mnu"
File 6="_functions_levylab_lib_build_support_15.mnu"
File 7="_functions_levylab_lib_build_support_16.mnu"
File 8="_functions_levylab_lib_build_support_17.mnu"
File 9="_functions_levylab_lib_build_support_2.mnu"
File 10="_functions_levylab_lib_build_support_3.mnu"
File 11="_functions_levylab_lib_build_support_4.mnu"
File 12="_functions_levylab_lib_build_support_5.mnu"
File 13="_functions_levylab_lib_build_support_6.mnu"
File 14="_functions_levylab_lib_build_support_7.mnu"
File 15="_functions_levylab_lib_build_support_8.mnu"
File 16="_functions_levylab_lib_build_support_9.mnu"
File 17="functions_Levylab_lib_Build_Support.mnu"


[File Group 2]
Target Dir="<menus>/Categories/Levylab"
Replace Mode="If Newer"
Num Files=1
File 0="dir.mnu"
