[Package]
Name="levylab_lib_asylum_afm_api"
Version="1.0.1.1"
Release=""
ID=d4a025fe62b6b2375f1122516846c02d
File Format="vip"
Format Version="2017"
Display Name="Asylum AFM API"


[Description]
Description="This is a LabVIEW wrapper meant to facilitate the use of the text based Asylum Instruments ActiveX API. These are the lowest level commands. Please note that these commands may be out of date. This package will need to be updated as time goes on and new functionality is needed."
Summary="A LabVIEW wrapper for the text based Asylum Instruments ActiveX API."
License="BSD-3"
Copyright="Copyright (c) 2023, Levylab"
Distribution=""
Vendor="Levylab"
URL="https://github.com/levylabpitt/Asylum-API"
Packager="Joe Albro, Patrick Irvin"
Demo="FALSE"
Release Notes="[1.0.1.1]\0D\0A- Igor-specific functions are now stored in the Igor-API package dependency (Issues #5, #8, #9)\0D\0A  - note that some of these functions have new names (e.g. Asylum_OpenRefnum.vi --> Igor_OpenRefnum.vi)\0D\0A- EnsureStringFormat icon updated (Issue #7)\0D\0A- package install location and palette location now consistent with other LevyLab-related packages"
System Package="FALSE"
Sub Package="FALSE"
License Agreement="TRUE"


[LabVIEW]
close labview before install="FALSE"
restart labview after install="FALSE"
skip mass compile after install="FALSE"
install into global environment="FALSE"


[Platform]
Exclusive_LabVIEW_Version="LabVIEW>=19.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="ALL"


[Script VIs]
PreInstall=""
PostInstall=""
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires="jki_lib_caraya>=1.3.0.137,labview_open_source_lib_epoch_datetime>=1.1.0.5,oglib_array>=4.1.1.14,oglib_error>=4.2.0.23,oglib_file>=4.0.1.22,oglib_lvdata>=5.0.0.27,oglib_string>=5.0.0.25,levylab_lib_igor_api>=1.0.0.1"
Conflicts=""


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="3"
Sub-Packages=""
Namespaces=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=97
File 0="user.lib/Levylab/Asylum AFM API/Asylum_API.lvproj"
File 1="user.lib/Levylab/Asylum AFM API/Waves/Asylum_SetInWave.vi"
File 2="user.lib/Levylab/Asylum AFM API/Waves/Asylum_SetInWavePair.vi"
File 3="user.lib/Levylab/Asylum AFM API/Waves/Asylum_SetOutWave.vi"
File 4="user.lib/Levylab/Asylum AFM API/Waves/Asylum_SetOutWavePair.vi"
File 5="user.lib/Levylab/Asylum AFM API/Waves/Asylum_SetSTFC.vi"
File 6="user.lib/Levylab/Asylum AFM API/Waves/Asylum_StopInWaveBank.vi"
File 7="user.lib/Levylab/Asylum AFM API/Waves/Asylum_StopOutWaveBank.vi"
File 8="user.lib/Levylab/Asylum AFM API/Waves/Asylum_StopSTFC.vi"
File 9="user.lib/Levylab/Asylum AFM API/Tests/Tests/RunTests.vi"
File 10="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestAsylumMethods.vi"
File 11="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestBuildPISLoop.vi"
File 12="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestCaptureImage.vi"
File 13="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestControllerReset.vi"
File 14="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestDate.vi"
File 15="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestGeneralSyntax.vi"
File 16="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestGetDevices.vi"
File 17="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestGetGroupLabels.vi"
File 18="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestGetGroupRanges.vi"
File 19="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestGetLabel.vi"
File 20="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestGetRange.vi"
File 21="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestNoParameterFunctions.vi"
File 22="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestReadGroup.vi"
File 23="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestReadString.vi"
File 24="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestReadValue.vi"
File 25="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestScanForDevices.vi"
File 26="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestSetInWave.vi"
File 27="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestSetInWavePair.vi"
File 28="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestSetOutWave.vi"
File 29="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestSetOutWavePair.vi"
File 30="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestShowVideovi.vi"
File 31="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestSoftReset.vi"
File 32="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestStop.vi"
File 33="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestStopInWaveBank.vi"
File 34="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestStopOutWaveBank.vi"
File 35="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestStopPISLoop.vi"
File 36="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestStopSTFC.vi"
File 37="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestStopThermal.vi"
File 38="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestusTimer.vi"
File 39="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestWriteGroup.vi"
File 40="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestWriteString.vi"
File 41="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestWriteValue.vi"
File 42="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestXopVersion.vi"
File 43="user.lib/Levylab/Asylum AFM API/Read Write Values/Asylum_GetLabel.vi"
File 44="user.lib/Levylab/Asylum AFM API/Read Write Values/Asylum_GetRange.vi"
File 45="user.lib/Levylab/Asylum AFM API/Read Write Values/Asylum_ReadString.vi"
File 46="user.lib/Levylab/Asylum AFM API/Read Write Values/Asylum_ReadValue.vi"
File 47="user.lib/Levylab/Asylum AFM API/Read Write Values/Asylum_WriteString.vi"
File 48="user.lib/Levylab/Asylum AFM API/Read Write Values/Asylum_WriteValue.vi"
File 49="user.lib/Levylab/Asylum AFM API/PISLoop/Asylum_SetPISLoop.vi"
File 50="user.lib/Levylab/Asylum AFM API/PISLoop/Asylum_StopPISLoop.vi"
File 51="user.lib/Levylab/Asylum AFM API/Group/Asylum_GetGroupLabels.vi"
File 52="user.lib/Levylab/Asylum AFM API/Group/Asylum_GetGroupRanges.vi"
File 53="user.lib/Levylab/Asylum AFM API/Group/Asylum_ReadGroup.vi"
File 54="user.lib/Levylab/Asylum AFM API/Group/Asylum_WriteGroup.vi"
File 55="user.lib/Levylab/Asylum AFM API/Controller/Asylum_CaptureImage.vi"
File 56="user.lib/Levylab/Asylum AFM API/Controller/Asylum_ControllerReset.vi"
File 57="user.lib/Levylab/Asylum AFM API/Controller/Asylum_Date.vi"
File 58="user.lib/Levylab/Asylum AFM API/Controller/Asylum_GetDevices.vi"
File 59="user.lib/Levylab/Asylum AFM API/Controller/Asylum_ScanForDevices.vi"
File 60="user.lib/Levylab/Asylum AFM API/Controller/Asylum_ShowVideo.vi"
File 61="user.lib/Levylab/Asylum AFM API/Controller/Asylum_SoftReset.vi"
File 62="user.lib/Levylab/Asylum AFM API/Controller/Asylum_Stop.vi"
File 63="user.lib/Levylab/Asylum AFM API/Controller/Asylum_StopThermal.vi"
File 64="user.lib/Levylab/Asylum AFM API/Controller/Asylum_uSTimer.vi"
File 65="user.lib/Levylab/Asylum AFM API/Controller/Asylum_XOPVersion.vi"
File 66="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_CaptureImage.vi"
File 67="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_ControllerReset.vi"
File 68="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_Date.vi"
File 69="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_GetDevices.vi"
File 70="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_GetGroupLabels.vi"
File 71="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_GetGroupRanges.vi"
File 72="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_GetLabel.vi"
File 73="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_GetRange.vi"
File 74="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_ReadGroup.vi"
File 75="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_ReadString.vi"
File 76="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_ReadValue.vi"
File 77="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_ScanForDevices.vi"
File 78="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SetInWave.vi"
File 79="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SetInWavePair.vi"
File 80="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SetOutWave.vi"
File 81="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SetOutWavePair.vi"
File 82="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SetPISLoop.vi"
File 83="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SetSTFC.vi"
File 84="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_ShowVideo.vi"
File 85="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SoftReset.vi"
File 86="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_Stop.vi"
File 87="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_StopInWaveBank.vi"
File 88="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_StopOutWaveBank.vi"
File 89="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_StopPISLoop.vi"
File 90="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_StopSTFC.vi"
File 91="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_StopThermal.vi"
File 92="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_usTimer.vi"
File 93="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_WriteGroup.vi"
File 94="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_WriteString.vi"
File 95="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_WriteValue.vi"
File 96="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_XopVersion.vi"


[File Group 1]
Target Dir="<menus>/Categories/Levylab"
Replace Mode="Always"
Num Files=10
File 0="_functions_levylab_lib_asylum_afm_api_1.mnu"
File 1="_functions_levylab_lib_asylum_afm_api_2.mnu"
File 2="_functions_levylab_lib_asylum_afm_api_3.mnu"
File 3="_functions_levylab_lib_asylum_afm_api_4.mnu"
File 4="_functions_levylab_lib_asylum_afm_api_5.mnu"
File 5="_functions_levylab_lib_asylum_afm_api_6.mnu"
File 6="_functions_levylab_lib_asylum_afm_api_7.mnu"
File 7="_functions_levylab_lib_asylum_afm_api_8.mnu"
File 8="_functions_levylab_lib_asylum_afm_api_9.mnu"
File 9="functions_Levylab_lib_Asylum_AFM_API.mnu"


[File Group 2]
Target Dir="<menus>/Categories/Levylab"
Replace Mode="If Newer"
Num Files=1
File 0="dir.mnu"
