[Package]
Name="levylab_lib_asylum_afm_api"
Version="1.0.0.6"
Release=""
ID=40490c412bbef7056896c152980b2fe7
File Format="vip"
Format Version="2017"
Display Name="Asylum AFM API"


[Description]
Description="This is a LabVIEW wrapper meant to facilitate the use of the text based Asylum Instruments ActiveX API. These are the lowest level commands. Please note that these commands may be out of date. This package will need to be updated as time goes on and new functionality is needed."
Summary="A LabVIEW wrapper for the text based Asylum Instruments ActiveX API."
License="BSD-3"
Copyright="Copyright (c) 2023, Levylab"
Distribution=""
Vendor="Levylab"
URL="https://github.com/levylabpitt/Asylum-API"
Packager="Joe Albro, Patrick Irvin"
Demo="FALSE"
Release Notes="[1.0.1.6]\0A- Igor-specific functions are now stored in the Igor-API package dependency (Issues #5, #8, #9)\0A  - note that some of these functions have new names (e.g. Asylum_OpenRefnum.vi --> Igor_OpenRefnum.vi)\0A- EnsureStringFormat icon updated (Issue #7)\0A- package install location and palette location now consistent with other LevyLab-related packages"
System Package="FALSE"
Sub Package="FALSE"
License Agreement="TRUE"


[LabVIEW]
close labview before install="FALSE"
restart labview after install="FALSE"
skip mass compile after install="FALSE"
install into global environment="FALSE"


[Platform]
Exclusive_LabVIEW_Version="LabVIEW>=19.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="ALL"


[Script VIs]
PreInstall=""
PostInstall=""
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires="jki_lib_caraya>=1.3.0.137,labview_open_source_lib_epoch_datetime>=1.1.0.5,oglib_array>=4.1.1.14,oglib_error>=4.2.0.23,oglib_file>=4.0.1.22,oglib_lvdata>=5.0.0.27,oglib_string>=5.0.0.25"
Conflicts=""


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="3"
Sub-Packages=""
Namespaces=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=156
File 0="user.lib/Levylab/Asylum AFM API/Asylum_API.lvproj"
File 1="user.lib/Levylab/Asylum AFM API/Waves/Asylum_SetInWave.vi"
File 2="user.lib/Levylab/Asylum AFM API/Waves/Asylum_SetInWavePair.vi"
File 3="user.lib/Levylab/Asylum AFM API/Waves/Asylum_SetOutWave.vi"
File 4="user.lib/Levylab/Asylum AFM API/Waves/Asylum_SetOutWavePair.vi"
File 5="user.lib/Levylab/Asylum AFM API/Waves/Asylum_SetSTFC.vi"
File 6="user.lib/Levylab/Asylum AFM API/Waves/Asylum_StopInWaveBank.vi"
File 7="user.lib/Levylab/Asylum AFM API/Waves/Asylum_StopOutWaveBank.vi"
File 8="user.lib/Levylab/Asylum AFM API/Waves/Asylum_StopSTFC.vi"
File 9="user.lib/Levylab/Asylum AFM API/Tests/Tests/RunTests.vi"
File 10="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestAsylumMethods.vi"
File 11="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestBuildPISLoop.vi"
File 12="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestCaptureImage.vi"
File 13="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestControllerReset.vi"
File 14="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestDate.vi"
File 15="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestGeneralSyntax.vi"
File 16="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestGetDevices.vi"
File 17="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestGetGroupLabels.vi"
File 18="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestGetGroupRanges.vi"
File 19="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestGetLabel.vi"
File 20="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestGetRange.vi"
File 21="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestNoParameterFunctions.vi"
File 22="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestReadGroup.vi"
File 23="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestReadString.vi"
File 24="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestReadValue.vi"
File 25="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestScanForDevices.vi"
File 26="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestSetInWave.vi"
File 27="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestSetInWavePair.vi"
File 28="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestSetOutWave.vi"
File 29="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestSetOutWavePair.vi"
File 30="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestShowVideovi.vi"
File 31="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestSoftReset.vi"
File 32="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestStop.vi"
File 33="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestStopInWaveBank.vi"
File 34="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestStopOutWaveBank.vi"
File 35="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestStopPISLoop.vi"
File 36="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestStopSTFC.vi"
File 37="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestStopThermal.vi"
File 38="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestusTimer.vi"
File 39="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestWriteGroup.vi"
File 40="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestWriteString.vi"
File 41="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestWriteValue.vi"
File 42="user.lib/Levylab/Asylum AFM API/Tests/Tests/TestXopVersion.vi"
File 43="user.lib/Levylab/Asylum AFM API/Read Write Values/Asylum_GetLabel.vi"
File 44="user.lib/Levylab/Asylum AFM API/Read Write Values/Asylum_GetRange.vi"
File 45="user.lib/Levylab/Asylum AFM API/Read Write Values/Asylum_ReadString.vi"
File 46="user.lib/Levylab/Asylum AFM API/Read Write Values/Asylum_ReadValue.vi"
File 47="user.lib/Levylab/Asylum AFM API/Read Write Values/Asylum_WriteString.vi"
File 48="user.lib/Levylab/Asylum AFM API/Read Write Values/Asylum_WriteValue.vi"
File 49="user.lib/Levylab/Asylum AFM API/PISLoop/Asylum_SetPISLoop.vi"
File 50="user.lib/Levylab/Asylum AFM API/PISLoop/Asylum_StopPISLoop.vi"
File 51="user.lib/Levylab/Asylum AFM API/Group/Asylum_GetGroupLabels.vi"
File 52="user.lib/Levylab/Asylum AFM API/Group/Asylum_GetGroupRanges.vi"
File 53="user.lib/Levylab/Asylum AFM API/Group/Asylum_ReadGroup.vi"
File 54="user.lib/Levylab/Asylum AFM API/Group/Asylum_WriteGroup.vi"
File 55="user.lib/Levylab/Asylum AFM API/Controller/Asylum_CaptureImage.vi"
File 56="user.lib/Levylab/Asylum AFM API/Controller/Asylum_ControllerReset.vi"
File 57="user.lib/Levylab/Asylum AFM API/Controller/Asylum_Date.vi"
File 58="user.lib/Levylab/Asylum AFM API/Controller/Asylum_GetDevices.vi"
File 59="user.lib/Levylab/Asylum AFM API/Controller/Asylum_ScanForDevices.vi"
File 60="user.lib/Levylab/Asylum AFM API/Controller/Asylum_ShowVideo.vi"
File 61="user.lib/Levylab/Asylum AFM API/Controller/Asylum_SoftReset.vi"
File 62="user.lib/Levylab/Asylum AFM API/Controller/Asylum_Stop.vi"
File 63="user.lib/Levylab/Asylum AFM API/Controller/Asylum_StopThermal.vi"
File 64="user.lib/Levylab/Asylum AFM API/Controller/Asylum_uSTimer.vi"
File 65="user.lib/Levylab/Asylum AFM API/Controller/Asylum_XOPVersion.vi"
File 66="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_CaptureImage.vi"
File 67="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_ControllerReset.vi"
File 68="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_Date.vi"
File 69="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_GetDevices.vi"
File 70="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_GetGroupLabels.vi"
File 71="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_GetGroupRanges.vi"
File 72="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_GetLabel.vi"
File 73="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_GetRange.vi"
File 74="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_ReadGroup.vi"
File 75="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_ReadString.vi"
File 76="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_ReadValue.vi"
File 77="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_ScanForDevices.vi"
File 78="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SetInWave.vi"
File 79="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SetInWavePair.vi"
File 80="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SetOutWave.vi"
File 81="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SetOutWavePair.vi"
File 82="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SetPISLoop.vi"
File 83="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SetSTFC.vi"
File 84="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_ShowVideo.vi"
File 85="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SoftReset.vi"
File 86="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_Stop.vi"
File 87="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_StopInWaveBank.vi"
File 88="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_StopOutWaveBank.vi"
File 89="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_StopPISLoop.vi"
File 90="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_StopSTFC.vi"
File 91="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_StopThermal.vi"
File 92="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_usTimer.vi"
File 93="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_WriteGroup.vi"
File 94="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_WriteString.vi"
File 95="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_WriteValue.vi"
File 96="user.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_XopVersion.vi"
File 97="user.lib/Levylab/_Asylum AFM API_internal_deps/F76862F773BC86A2EC4A020FD9F87D8CDebugModeSingleton.vi"
File 98="user.lib/Levylab/_Asylum AFM API_internal_deps/F76862F773BC86A2EC4A020FD9F87D8CIgor_EnsureIgorStringFormat.vi"
File 99="user.lib/Levylab/_Asylum AFM API_internal_deps/F76862F773BC86A2EC4A020FD9F87D8CIgor_NumericArraytoIgorWave.vi"
File 100="user.lib/Levylab/_Asylum AFM API_internal_deps/F76862F773BC86A2EC4A020FD9F87D8CIgor_SendCommand.vi"
File 101="user.lib/Levylab/_Asylum AFM API_internal_deps/F76862F773BC86A2EC4A020FD9F87D8CIgor_StringArraytoIgorWave.vi"
File 102="user.lib/Levylab/_Asylum AFM API_internal_deps/F76862F773BC86A2EC4A020FD9F87D8CTestArraytoWave.vi"
File 103="user.lib/Levylab/_Asylum AFM API_internal_deps/F76862F773BC86A2EC4A020FD9F87D8CTestEnsureIgorStringFormat.vi"
File 104="user.lib/Levylab/_Asylum AFM API_internal_deps/string/string.llb/F76862F773BC86A2EC4A020FD9F87D8CFormat Variant Into String__ogtk.vi"
File 105="user.lib/Levylab/_Asylum AFM API_internal_deps/string/string.llb/F76862F773BC86A2EC4A020FD9F87D8CResolve Timestamp Format__ogtk.vi"
File 106="user.lib/Levylab/_Asylum AFM API_internal_deps/string/string.llb/F76862F773BC86A2EC4A020FD9F87D8CTrim Whitespace (String)__ogtk.vi"
File 107="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CArray Size(s)__ogtk.vi"
File 108="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CArray to Array of VData__ogtk.vi"
File 109="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CCluster to Array of VData__ogtk.vi"
File 110="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CGet Array Element TDEnum__ogtk.vi"
File 111="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CGet Data Name from TD__ogtk.vi"
File 112="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CGet Data Name__ogtk.vi"
File 113="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CGet Element TD from Array TD__ogtk.vi"
File 114="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CGet Header from TD__ogtk.vi"
File 115="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CGet Last PString__ogtk.vi"
File 116="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CGet Physical Units from TD__ogtk.vi"
File 117="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CGet Physical Units__ogtk.vi"
File 118="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CGet PString__ogtk.vi"
File 119="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CGet Refnum Type Enum from Data__ogtk.vi"
File 120="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CGet Refnum Type Enum from TD__ogtk.vi"
File 121="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CGet Strings from Enum TD__ogtk.vi"
File 122="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CGet Strings from Enum__ogtk.vi"
File 123="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CGet TDEnum from Data__ogtk.vi"
File 124="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CGet TDEnum from TD__ogtk.vi"
File 125="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CGet Variant Attributes__ogtk.vi"
File 126="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CGet Waveform Type Enum from Data__ogtk.vi"
File 127="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CGet Waveform Type Enum from TD__ogtk.vi"
File 128="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CParse String with TDs__ogtk.vi"
File 129="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CReshape Array to 1D VArray__ogtk.vi"
File 130="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CSet Data Name__ogtk.vi"
File 131="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CSplit Cluster TD__ogtk.vi"
File 132="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CStrip Units__ogtk.vi"
File 133="user.lib/Levylab/_Asylum AFM API_internal_deps/lvdata/lvdata.llb/F76862F773BC86A2EC4A020FD9F87D8CVariant to Header Info__ogtk.vi"
File 134="user.lib/Levylab/_Asylum AFM API_internal_deps/file/file.llb/F76862F773BC86A2EC4A020FD9F87D8CBuild Path - File Names Array__ogtk.vi"
File 135="user.lib/Levylab/_Asylum AFM API_internal_deps/file/file.llb/F76862F773BC86A2EC4A020FD9F87D8CFile Exists - Array__ogtk.vi"
File 136="user.lib/Levylab/_Asylum AFM API_internal_deps/file/file.llb/F76862F773BC86A2EC4A020FD9F87D8CFile Exists - Scalar__ogtk.vi"
File 137="user.lib/Levylab/_Asylum AFM API_internal_deps/file/file.llb/F76862F773BC86A2EC4A020FD9F87D8CList Directory Recursive__ogtk.vi"
File 138="user.lib/Levylab/_Asylum AFM API_internal_deps/file/file.llb/F76862F773BC86A2EC4A020FD9F87D8CList Directory__ogtk.vi"
File 139="user.lib/Levylab/_Asylum AFM API_internal_deps/file/file.llb/F76862F773BC86A2EC4A020FD9F87D8CStrip Path - Traditional__ogtk.vi"
File 140="user.lib/Levylab/_Asylum AFM API_internal_deps/file/file.llb/F76862F773BC86A2EC4A020FD9F87D8CStrip Path Extension - String__ogtk.vi"
File 141="user.lib/Levylab/_Asylum AFM API_internal_deps/file/file.llb/F76862F773BC86A2EC4A020FD9F87D8CValid Path - Traditional__ogtk.vi"
File 142="user.lib/Levylab/_Asylum AFM API_internal_deps/error/error.llb/F76862F773BC86A2EC4A020FD9F87D8CBuild Error Cluster__ogtk.vi"
File 143="user.lib/Levylab/_Asylum AFM API_internal_deps/array/array.llb/F76862F773BC86A2EC4A020FD9F87D8CDelete Elements from 1D Array (Path)__ogtk.vi"
File 144="user.lib/Levylab/_Asylum AFM API_internal_deps/array/array.llb/F76862F773BC86A2EC4A020FD9F87D8CDelete Elements from 1D Array (String)__ogtk.vi"
File 145="user.lib/Levylab/_Asylum AFM API_internal_deps/array/array.llb/F76862F773BC86A2EC4A020FD9F87D8CEmpty 1D Array (String)__ogtk.vi"
File 146="user.lib/Levylab/_Asylum AFM API_internal_deps/array/array.llb/F76862F773BC86A2EC4A020FD9F87D8CFilter 1D Array (Path)__ogtk.vi"
File 147="user.lib/Levylab/_Asylum AFM API_internal_deps/array/array.llb/F76862F773BC86A2EC4A020FD9F87D8CFilter 1D Array (String)__ogtk.vi"
File 148="user.lib/Levylab/_Asylum AFM API_internal_deps/array/array.llb/F76862F773BC86A2EC4A020FD9F87D8CRemove Duplicates from 1D Array (I32)__ogtk.vi"
File 149="user.lib/Levylab/_Asylum AFM API_internal_deps/array/array.llb/F76862F773BC86A2EC4A020FD9F87D8CRemove Duplicates from 1D Array (Path)__ogtk.vi"
File 150="user.lib/Levylab/_Asylum AFM API_internal_deps/array/array.llb/F76862F773BC86A2EC4A020FD9F87D8CRemove Duplicates from 1D Array (String)__ogtk.vi"
File 151="user.lib/Levylab/_Asylum AFM API_internal_deps/array/array.llb/F76862F773BC86A2EC4A020FD9F87D8CReorder 1D Array2 (Path)__ogtk.vi"
File 152="user.lib/Levylab/_Asylum AFM API_internal_deps/array/array.llb/F76862F773BC86A2EC4A020FD9F87D8CReorder 1D Array2 (String)__ogtk.vi"
File 153="user.lib/Levylab/_Asylum AFM API_internal_deps/array/array.llb/F76862F773BC86A2EC4A020FD9F87D8CSearch 1D Array (Path)__ogtk.vi"
File 154="user.lib/Levylab/_Asylum AFM API_internal_deps/array/array.llb/F76862F773BC86A2EC4A020FD9F87D8CSearch 1D Array (String)__ogtk.vi"
File 155="user.lib/Levylab/_Asylum AFM API_internal_deps/array/array.llb/F76862F773BC86A2EC4A020FD9F87D8CSort 1D Array (I32)__ogtk.vi"


[File Group 1]
Target Dir="<menus>/Categories/Levylab"
Replace Mode="Always"
Num Files=10
File 0="_functions_levylab_lib_asylum_afm_api_1.mnu"
File 1="_functions_levylab_lib_asylum_afm_api_2.mnu"
File 2="_functions_levylab_lib_asylum_afm_api_3.mnu"
File 3="_functions_levylab_lib_asylum_afm_api_4.mnu"
File 4="_functions_levylab_lib_asylum_afm_api_5.mnu"
File 5="_functions_levylab_lib_asylum_afm_api_6.mnu"
File 6="_functions_levylab_lib_asylum_afm_api_7.mnu"
File 7="_functions_levylab_lib_asylum_afm_api_8.mnu"
File 8="_functions_levylab_lib_asylum_afm_api_9.mnu"
File 9="functions_Levylab_lib_Asylum_AFM_API.mnu"


[File Group 2]
Target Dir="<menus>/Categories/Levylab"
Replace Mode="If Newer"
Num Files=1
File 0="dir.mnu"
