[Package]
Name="levylab_lib_asylum_afm_api"
Version="1.0.0.3"
Release=""
ID=bf25e9666c57d25c484c01be09cc235c
File Format="vip"
Format Version="2017"
Display Name="Asylum AFM API"


[Description]
Description="This is a LabVIEW wrapper meant to facilitate the use of the text based Asylum Instruments ActiveX API. These are the lowest level commands. Please note that these commands may be out of date. This package will need to be updated as time goes on and new functionality is needed."
Summary="A LabVIEW wrapper for the text based Asylum Instruments ActiveX API."
License="BSD-3"
Copyright="Copyright (c) 2022, Levylab"
Distribution=""
Vendor="Levylab"
URL="https://github.com/Monkeymerlot/Asylum-API"
Packager="Joseph Albro"
Demo="FALSE"
Release Notes="Fixed formatting for SetPISLoop\0AFixed formatting for Callback String in the SetInWave(Pair)\0ABetter handling of the reference in debug mode (no longer will attempt to open a communication with Igor at all in debug mode)"
System Package="FALSE"
Sub Package="FALSE"
License Agreement="TRUE"


[LabVIEW]
close labview before install="FALSE"
restart labview after install="FALSE"
skip mass compile after install="FALSE"


[Platform]
Exclusive_LabVIEW_Version="LabVIEW>=20.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="ALL"


[Script VIs]
PreInstall=""
PostInstall=""
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires=""
Conflicts=""


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="2"
Sub-Packages=""
Namespaces=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=106
File 0="vi.lib/Levylab/Asylum AFM API/Asylum_API.lvproj"
File 1="vi.lib/Levylab/Asylum AFM API/Asylum_CloseRefnum.vi"
File 2="vi.lib/Levylab/Asylum AFM API/Asylum_OpenRefnum.vi"
File 3="vi.lib/Levylab/Asylum AFM API/Asylum_SendIgorCommand.vi"
File 4="vi.lib/Levylab/Asylum AFM API/Waves/Asylum_SetInWave.vi"
File 5="vi.lib/Levylab/Asylum AFM API/Waves/Asylum_SetInWavePair.vi"
File 6="vi.lib/Levylab/Asylum AFM API/Waves/Asylum_SetOutWave.vi"
File 7="vi.lib/Levylab/Asylum AFM API/Waves/Asylum_SetOutWavePair.vi"
File 8="vi.lib/Levylab/Asylum AFM API/Waves/Asylum_SetSTFC.vi"
File 9="vi.lib/Levylab/Asylum AFM API/Waves/Asylum_StopInWaveBank.vi"
File 10="vi.lib/Levylab/Asylum AFM API/Waves/Asylum_StopOutWaveBank.vi"
File 11="vi.lib/Levylab/Asylum AFM API/Waves/Asylum_StopSTFC.vi"
File 12="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestArraytoWave.vi"
File 13="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestAsylumMethods.vi"
File 14="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestBuildPISLoop.vi"
File 15="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestCaptureImage.vi"
File 16="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestControllerReset.vi"
File 17="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestDate.vi"
File 18="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestEnsureIgorStringFormat.vi"
File 19="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestGeneralSyntax.vi"
File 20="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestGetDevices.vi"
File 21="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestGetGroupLabels.vi"
File 22="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestGetGroupRanges.vi"
File 23="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestGetLabel.vi"
File 24="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestGetRange.vi"
File 25="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestNoParameterFunctions.vi"
File 26="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestReadGroup.vi"
File 27="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestReadString.vi"
File 28="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestReadValue.vi"
File 29="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestScanForDevices.vi"
File 30="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestSetInWave.vi"
File 31="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestSetInWavePair.vi"
File 32="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestSetOutWave.vi"
File 33="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestSetOutWavePair.vi"
File 34="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestShowVideovi.vi"
File 35="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestSoftReset.vi"
File 36="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestStop.vi"
File 37="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestStopInWaveBank.vi"
File 38="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestStopOutWaveBank.vi"
File 39="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestStopPISLoop.vi"
File 40="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestStopSTFC.vi"
File 41="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestStopThermal.vi"
File 42="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestusTimer.vi"
File 43="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestWriteGroup.vi"
File 44="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestWriteString.vi"
File 45="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestWriteValue.vi"
File 46="vi.lib/Levylab/Asylum AFM API/Tests/Tests/TestXopVersion.vi"
File 47="vi.lib/Levylab/Asylum AFM API/Tests/mock/DebugModeSingleton.vi"
File 48="vi.lib/Levylab/Asylum AFM API/Read Write Values/Asylum_GetLabel.vi"
File 49="vi.lib/Levylab/Asylum AFM API/Read Write Values/Asylum_GetRange.vi"
File 50="vi.lib/Levylab/Asylum AFM API/Read Write Values/Asylum_ReadString.vi"
File 51="vi.lib/Levylab/Asylum AFM API/Read Write Values/Asylum_ReadValue.vi"
File 52="vi.lib/Levylab/Asylum AFM API/Read Write Values/Asylum_WriteString.vi"
File 53="vi.lib/Levylab/Asylum AFM API/Read Write Values/Asylum_WriteValue.vi"
File 54="vi.lib/Levylab/Asylum AFM API/PISLoop/Asylum_SetPISLoop.vi"
File 55="vi.lib/Levylab/Asylum AFM API/PISLoop/Asylum_StopPISLoop.vi"
File 56="vi.lib/Levylab/Asylum AFM API/Igor Data/ArraytoIgorWave.vi"
File 57="vi.lib/Levylab/Asylum AFM API/Igor Data/Asylum_EnsureIgorStringFormat.vi"
File 58="vi.lib/Levylab/Asylum AFM API/Igor Data/LVArraytoIgorWave/NumericArraytoIgorWave.vi"
File 59="vi.lib/Levylab/Asylum AFM API/Igor Data/LVArraytoIgorWave/StringArraytoIgorWave.vi"
File 60="vi.lib/Levylab/Asylum AFM API/Group/Asylum_GetGroupLabels.vi"
File 61="vi.lib/Levylab/Asylum AFM API/Group/Asylum_GetGroupRanges.vi"
File 62="vi.lib/Levylab/Asylum AFM API/Group/Asylum_ReadGroup.vi"
File 63="vi.lib/Levylab/Asylum AFM API/Group/Asylum_WriteGroup.vi"
File 64="vi.lib/Levylab/Asylum AFM API/Controller/Asylum_CaptureImage.vi"
File 65="vi.lib/Levylab/Asylum AFM API/Controller/Asylum_ControllerReset.vi"
File 66="vi.lib/Levylab/Asylum AFM API/Controller/Asylum_Date.vi"
File 67="vi.lib/Levylab/Asylum AFM API/Controller/Asylum_GetDevices.vi"
File 68="vi.lib/Levylab/Asylum AFM API/Controller/Asylum_ScanForDevices.vi"
File 69="vi.lib/Levylab/Asylum AFM API/Controller/Asylum_ShowVideo.vi"
File 70="vi.lib/Levylab/Asylum AFM API/Controller/Asylum_SoftReset.vi"
File 71="vi.lib/Levylab/Asylum AFM API/Controller/Asylum_Stop.vi"
File 72="vi.lib/Levylab/Asylum AFM API/Controller/Asylum_StopThermal.vi"
File 73="vi.lib/Levylab/Asylum AFM API/Controller/Asylum_uSTimer.vi"
File 74="vi.lib/Levylab/Asylum AFM API/Controller/Asylum_XOPVersion.vi"
File 75="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_CaptureImage.vi"
File 76="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_ControllerReset.vi"
File 77="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_Date.vi"
File 78="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_GetDevices.vi"
File 79="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_GetGroupLabels.vi"
File 80="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_GetGroupRanges.vi"
File 81="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_GetLabel.vi"
File 82="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_GetRange.vi"
File 83="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_ReadGroup.vi"
File 84="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_ReadString.vi"
File 85="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_ReadValue.vi"
File 86="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_ScanForDevices.vi"
File 87="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SetInWave.vi"
File 88="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SetInWavePair.vi"
File 89="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SetOutWave.vi"
File 90="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SetOutWavePair.vi"
File 91="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SetPISLoop.vi"
File 92="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SetSTFC.vi"
File 93="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_ShowVideo.vi"
File 94="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_SoftReset.vi"
File 95="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_Stop.vi"
File 96="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_StopInWaveBank.vi"
File 97="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_StopOutWaveBank.vi"
File 98="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_StopPISLoop.vi"
File 99="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_StopSTFC.vi"
File 100="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_StopThermal.vi"
File 101="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_usTimer.vi"
File 102="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_WriteGroup.vi"
File 103="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_WriteString.vi"
File 104="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_WriteValue.vi"
File 105="vi.lib/Levylab/Asylum AFM API/BuildFunctions/Build_Asylum_XopVersion.vi"


[File Group 1]
Target Dir="<menus>/Categories"
Replace Mode="Always"
Num Files=12
File 0="_functions_levylab_lib_asylum_afm_api_1.mnu"
File 1="_functions_levylab_lib_asylum_afm_api_10.mnu"
File 2="_functions_levylab_lib_asylum_afm_api_11.mnu"
File 3="_functions_levylab_lib_asylum_afm_api_2.mnu"
File 4="_functions_levylab_lib_asylum_afm_api_3.mnu"
File 5="_functions_levylab_lib_asylum_afm_api_4.mnu"
File 6="_functions_levylab_lib_asylum_afm_api_5.mnu"
File 7="_functions_levylab_lib_asylum_afm_api_6.mnu"
File 8="_functions_levylab_lib_asylum_afm_api_7.mnu"
File 9="_functions_levylab_lib_asylum_afm_api_8.mnu"
File 10="_functions_levylab_lib_asylum_afm_api_9.mnu"
File 11="functions_Levylab_lib_Asylum_AFM_API.mnu"
