[Package]
Name="levylab_lib_levylab_instruments"
Version="1.14.4.23"
Release=""
ID=dca9db8b06d126260bbbb99637c2a888
File Format="vip"
Format Version="2017"
Display Name="Instrument Framework"


[Description]
Description="An object-oriented framework based on JKI SMOs, developed by the LevyLab at the University of Pittsburgh.\0D\0A\0D\0AAn Instrument developed using this framework will have the access to the following capabilities:\0D\0A\0D\0A- Framework for communicating with hardware (Hardware Abstraction Layer (HAL))\0D\0A- Periodically polls the instrument for its settings and logs them to a PGSQL database\0D\0A- Defines an API to allow external programs to control compiled instances of the application and remotely across a network (Either NI's Simple Messaging Library (STM) (deprecated in v1.9) or cross-platform protocol ZMQ (preferred beginning with v1.9))\0D\0A- Provide a user interface (optional but probably desirable).\0D\0A- Methods for reading and writing configuration from disk."
Summary=""
License="BSD-3"
Copyright="Copyright (c) 2025, LevyLab"
Distribution=""
Vendor="LevyLab"
URL="https://github.com/levylabpitt/Instrument-Framework"
Packager="Patrick Irvin"
Demo="FALSE"
Release Notes="[1.14.4]\0A- remove instrument types from package"
System Package="FALSE"
Sub Package="FALSE"
License Agreement="TRUE"


[LabVIEW]
close labview before install="FALSE"
restart labview after install="FALSE"
skip mass compile after install="FALSE"
install into global environment="FALSE"


[Platform]
Exclusive_LabVIEW_Version="LabVIEW>=19.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="ALL"


[Script VIs]
PreInstall=""
PostInstall="<OS User Documents>\\GitHub\\Instrument-Framework\\build support\\Post-Install Custom Action.vi"
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires="jdp_science_jsontext>=1.9.0.124,jdp_science_lib_common_utilities>=1.4.1.18,jdp_science_postgresql>=0.6.2.48,jki_lib_caraya>=1.4.3.147,jki_lib_state_machine>=2018.0.7.45,jki_statemachineobjects>=2.0.0.73,labview-zmq>=3.6.3.113,labview_open_source_lib_epoch_datetime>=1.2.0.6,levylab_lib_control_vi>=1.3.0.11,levylab_lib_fileutilities>=1.2.6.13,levylab_lib_graph_utilities>=2.1.11.4,levylab_lib_lvtdatpgsql>=3.9.1.6,levylab_lib_lvtoitx>=3.9.1.6,levylab_lib_xy_utilities>=1.5.5.5,mgi_lib_1d_array>=1.0.2.3,mgi_lib_application_control>=1.1.1.10,mgi_lib_numeric>=1.1.0.2,national_instruments_lib_guid_generator>=1.0.2.3,oglib_appcontrol>=4.1.0.7,oglib_array>=4.1.1.14,oglib_boolean>=4.0.0.7,oglib_dictionary>=4.0.0.4,oglib_error>=4.2.0.23,oglib_file>=4.0.1.22,oglib_lvdata>=5.0.0.27,oglib_numeric>=4.1.0.8,oglib_string>=5.0.0.25,oglib_time>=4.0.1.3,oglib_variantconfig>=4.0.0.5,prirvin_lib_json_rpc>=1.2.5.14,prirvin_lib_json_schema>=0.1.3.7"
Conflicts="levylab_lib_postgresql>=1.4.0.22"


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="3"
Sub-Packages=""
Namespaces=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=145
File 0="user.lib/Levylab/Instrument Framework/Instrument.lvlib"
File 1="user.lib/Levylab/Instrument Framework/subsystems/Help/Help.lvclass"
File 2="user.lib/Levylab/Instrument Framework/subsystems/Help/typedefs/Help--cluster.ctl"
File 3="user.lib/Levylab/Instrument Framework/subsystems/Help/private/Create Command Description.vi"
File 4="user.lib/Levylab/Instrument Framework/subsystems/Help/private/Create Request Description.vi"
File 5="user.lib/Levylab/Instrument Framework/subsystems/Help/private/Create Response Description.vi"
File 6="user.lib/Levylab/Instrument Framework/subsystems/Help/private/Minify jsonrpc id.vi"
File 7="user.lib/Levylab/Instrument Framework/subsystems/Help/API/Get JSON API Documentation.vi"
File 8="user.lib/Levylab/Instrument Framework/subsystems/Help/API/Get JSON Example.vi"
File 9="user.lib/Levylab/Instrument Framework/subsystems/Help/API/Get JSON Param Documentation (default).vi"
File 10="user.lib/Levylab/Instrument Framework/subsystems/Help/API/Get JSON Response Documentation (default).vi"
File 11="user.lib/Levylab/Instrument Framework/subsystems/HAL.TCP/HAL.TCP.lvclass"
File 12="user.lib/Levylab/Instrument Framework/subsystems/HAL.TCP/Methods/Close.vi"
File 13="user.lib/Levylab/Instrument Framework/subsystems/HAL.TCP/Methods/Open.vi"
File 14="user.lib/Levylab/Instrument Framework/subsystems/HAL.TCP/Methods/Read.vi"
File 15="user.lib/Levylab/Instrument Framework/subsystems/HAL.TCP/Methods/Write.vi"
File 16="user.lib/Levylab/Instrument Framework/subsystems/HAL.Serial/HAL.Serial.lvclass"
File 17="user.lib/Levylab/Instrument Framework/subsystems/HAL.Serial/typedefs/configuration--cluster.ctl"
File 18="user.lib/Levylab/Instrument Framework/subsystems/HAL.Serial/typedefs/configuration.serial--cluster.ctl"
File 19="user.lib/Levylab/Instrument Framework/subsystems/HAL.Serial/typedefs/Serial - ASCII Characters.ctl"
File 20="user.lib/Levylab/Instrument Framework/subsystems/HAL.Serial/Overrides/Close.vi"
File 21="user.lib/Levylab/Instrument Framework/subsystems/HAL.Serial/Overrides/Open.vi"
File 22="user.lib/Levylab/Instrument Framework/subsystems/HAL.Serial/Overrides/Read.vi"
File 23="user.lib/Levylab/Instrument Framework/subsystems/HAL.Serial/Overrides/Write.vi"
File 24="user.lib/Levylab/Instrument Framework/subsystems/HAL/HAL.lvclass"
File 25="user.lib/Levylab/Instrument Framework/subsystems/HAL/process.vi"
File 26="user.lib/Levylab/Instrument Framework/subsystems/HAL/Methods/Close.vi"
File 27="user.lib/Levylab/Instrument Framework/subsystems/HAL/Methods/Open.vi"
File 28="user.lib/Levylab/Instrument Framework/subsystems/HAL/Methods/Read.vi"
File 29="user.lib/Levylab/Instrument Framework/subsystems/HAL/Methods/Write.vi"
File 30="user.lib/Levylab/Instrument Framework/subsystems/API/API.lvclass"
File 31="user.lib/Levylab/Instrument Framework/Instrument-VIM/enum to string.vim"
File 32="user.lib/Levylab/Instrument Framework/Instrument-VIM/Instrument-VIM.lvlib"
File 33="user.lib/Levylab/Instrument Framework/Instrument-VIM/string to enum.vim"
File 34="user.lib/Levylab/Instrument Framework/Instrument-VIM/Test enum to string.vi"
File 35="user.lib/Levylab/Instrument Framework/Instrument UI/Create UI.vi"
File 36="user.lib/Levylab/Instrument Framework/Instrument UI/Instrument UI.lvclass"
File 37="user.lib/Levylab/Instrument Framework/Instrument UI/Instrument UI.TestLauncher.vi"
File 38="user.lib/Levylab/Instrument Framework/Instrument UI/Process.vi"
File 39="user.lib/Levylab/Instrument Framework/Instrument UI/Read Instrument.vi"
File 40="user.lib/Levylab/Instrument Framework/Instrument UI/State History.vi"
File 41="user.lib/Levylab/Instrument Framework/Instrument/Instrument.lvclass"
File 42="user.lib/Levylab/Instrument Framework/Instrument/Instrument.TestLauncher.vi"
File 43="user.lib/Levylab/Instrument Framework/Instrument/Process.vi"
File 44="user.lib/Levylab/Instrument Framework/Instrument/Typedefs/Client Type--Enum.ctl"
File 45="user.lib/Levylab/Instrument Framework/Instrument/Typedefs/Configuration--Cluster.ctl"
File 46="user.lib/Levylab/Instrument Framework/Instrument/Typedefs/Dependencies--Cluster.ctl"
File 47="user.lib/Levylab/Instrument Framework/Instrument/Typedefs/Dependencies--Enum.ctl"
File 48="user.lib/Levylab/Instrument Framework/Instrument/Typedefs/HW Configuration--Cluster.ctl"
File 49="user.lib/Levylab/Instrument Framework/Instrument/Typedefs/Instrument.Commands--Enum.ctl"
File 50="user.lib/Levylab/Instrument Framework/Instrument/Typedefs/Instrument.IDN--cluster.ctl"
File 51="user.lib/Levylab/Instrument Framework/Instrument/Typedefs/Instrument.ProtectedCommands--Enum.ctl"
File 52="user.lib/Levylab/Instrument Framework/Instrument/Typedefs/Instrument.SET--cluster.ctl"
File 53="user.lib/Levylab/Instrument Framework/Instrument/Typedefs/PrivateEvents--Cluster.ctl"
File 54="user.lib/Levylab/Instrument Framework/Instrument/Typedefs/PrivateEvents--Instrument.DataToLog.ctl"
File 55="user.lib/Levylab/Instrument Framework/Instrument/Typedefs/PrivateEvents--Instrument.MessageToProcess.ctl"
File 56="user.lib/Levylab/Instrument Framework/Instrument/Typedefs/PublicEvents--Cluster.ctl"
File 57="user.lib/Levylab/Instrument Framework/Instrument/Typedefs/PublicEvents--Instrument.MessageFromProcess.ctl"
File 58="user.lib/Levylab/Instrument Framework/Instrument/Typedefs/SMO Configuration--Cluster.ctl"
File 59="user.lib/Levylab/Instrument Framework/Instrument/Tests/Test Handle Help.vi"
File 60="user.lib/Levylab/Instrument Framework/Instrument/Tests/Test JSON config.vi"
File 61="user.lib/Levylab/Instrument Framework/Instrument/Protected/Close SMO.vi"
File 62="user.lib/Levylab/Instrument Framework/Instrument/Protected/Examine Configuration.vi"
File 63="user.lib/Levylab/Instrument Framework/Instrument/Protected/Handle GET.vi"
File 64="user.lib/Levylab/Instrument Framework/Instrument/Protected/Handle IDN.vi"
File 65="user.lib/Levylab/Instrument Framework/Instrument/Protected/Handle SET.vi"
File 66="user.lib/Levylab/Instrument Framework/Instrument/Protected/Initialize Configuration.vi"
File 67="user.lib/Levylab/Instrument Framework/Instrument/Protected/Initialize IDN.vi"
File 68="user.lib/Levylab/Instrument Framework/Instrument/Protected/Instrument.Public API.vi"
File 69="user.lib/Levylab/Instrument Framework/Instrument/Protected/Open SMO.vi"
File 70="user.lib/Levylab/Instrument Framework/Instrument/Protected/setAllData.vi"
File 71="user.lib/Levylab/Instrument Framework/Instrument/Protected/setConfiguration.vi"
File 72="user.lib/Levylab/Instrument Framework/Instrument/Protected/setIDN.vi"
File 73="user.lib/Levylab/Instrument Framework/Instrument/Protected/State History.vi"
File 74="user.lib/Levylab/Instrument Framework/Instrument/Protected/Validate API method.vi"
File 75="user.lib/Levylab/Instrument Framework/Instrument/Protected/Wait Logic.vi"
File 76="user.lib/Levylab/Instrument Framework/Instrument/Protected/Write Configuration Path.vi"
File 77="user.lib/Levylab/Instrument Framework/Instrument/Private/Counts Since Last Reset.vi"
File 78="user.lib/Levylab/Instrument Framework/Instrument/Private/Get Dependencies.vi"
File 79="user.lib/Levylab/Instrument Framework/Instrument/Private/Get RC Connection Status.vi"
File 80="user.lib/Levylab/Instrument Framework/Instrument/Private/Instrument.GetPrivateEvents.vi"
File 81="user.lib/Levylab/Instrument Framework/Instrument/Private/Instrument.MessageFromProcess.EventStructure.vi"
File 82="user.lib/Levylab/Instrument Framework/Instrument/Private/Instrument.sendMessageFromProcess.vi"
File 83="user.lib/Levylab/Instrument Framework/Instrument/Private/Rename Error SMO Private Events.vi"
File 84="user.lib/Levylab/Instrument Framework/Instrument/Private/Rename PGSQL SMO Private Events.vi"
File 85="user.lib/Levylab/Instrument Framework/Instrument/Private/Rename RC SMO Private Events.vi"
File 86="user.lib/Levylab/Instrument Framework/Instrument/Private/Set Dependencies.vi"
File 87="user.lib/Levylab/Instrument Framework/Instrument/Overrides/CreatePrivateEvents.vi"
File 88="user.lib/Levylab/Instrument Framework/Instrument/Overrides/CreatePublicEvents.vi"
File 89="user.lib/Levylab/Instrument Framework/Instrument/Overrides/DestroyPrivateEvents.vi"
File 90="user.lib/Levylab/Instrument Framework/Instrument/Overrides/DestroyPublicEvents.vi"
File 91="user.lib/Levylab/Instrument Framework/Instrument/Overrides/enumerateStaticDependencies.vi"
File 92="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/Client.vi"
File 93="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/SMO/Get SMO Address.vi"
File 94="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/SMO/Get SMO API Type.vi"
File 95="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/SMO/Get SMO Database Paths.vi"
File 96="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/SMO/Get SMO HAL Type.vi"
File 97="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/SMO/Get SMO HELP getAll.vi"
File 98="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/SMO/Get SMO HELP.vi"
File 99="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/SMO/Get SMO Name.vi"
File 100="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/SMO/Get SMO Port.vi"
File 101="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/SMO/Get SMO Public API.vi"
File 102="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/SMO/Get SMO RC Type.vi"
File 103="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/SMO/Get SMO Serial Number.vi"
File 104="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/SMO/Get SMO Vendor.vi"
File 105="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/hardware/Close Hardware.vi"
File 106="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/hardware/Open Hardware.vi"
File 107="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/hardware/Read Hardware.vi"
File 108="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/hardware/Write Hardware.vi"
File 109="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/configuration/Configuration Window.vi"
File 110="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/configuration/Read Configuration File.vi"
File 111="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/configuration/Write Configuration File.vi"
File 112="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/commands/Handle Command.vi"
File 113="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/commands/Handle getAll.vi"
File 114="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/commands/Handle Help.vi"
File 115="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/commands/Handle setAllData.vi"
File 116="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/commands/Handle setConfiguration.vi"
File 117="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/commands/Handle setIDN.vi"
File 118="user.lib/Levylab/Instrument Framework/Instrument/Framework (for override)/commands/Handle setLogData.vi"
File 119="user.lib/Levylab/Instrument Framework/Instrument/Deprecated/Get SMO PGSQL Log Paths.vi"
File 120="user.lib/Levylab/Instrument Framework/Instrument/Deprecated/Instrument.LogPGSQL.vi"
File 121="user.lib/Levylab/Instrument Framework/Instrument/Deprecated/Instrument.MessageFromProcess.vi"
File 122="user.lib/Levylab/Instrument Framework/Instrument/Deprecated/Instrument.MessageToProcess.vi"
File 123="user.lib/Levylab/Instrument Framework/Instrument/Deprecated/Read Debug Mode.vi"
File 124="user.lib/Levylab/Instrument Framework/Instrument/API/ACK.vi"
File 125="user.lib/Levylab/Instrument Framework/Instrument/API/Close.vi"
File 126="user.lib/Levylab/Instrument Framework/Instrument/API/Create Instrument SMO.vi"
File 127="user.lib/Levylab/Instrument Framework/Instrument/API/getAll.vi"
File 128="user.lib/Levylab/Instrument Framework/Instrument/API/HELP.vi"
File 129="user.lib/Levylab/Instrument Framework/Instrument/API/IDN.vi"
File 130="user.lib/Levylab/Instrument Framework/Instrument/API/Instrument.GetPublicEvents.vi"
File 131="user.lib/Levylab/Instrument Framework/Instrument/API/Instrument.logToDatabase.vi"
File 132="user.lib/Levylab/Instrument Framework/Instrument/API/Instrument.sendMessageToProcess (string).vi"
File 133="user.lib/Levylab/Instrument Framework/Instrument/API/Instrument.sendMessageToProcess (variant).vi"
File 134="user.lib/Levylab/Instrument Framework/Instrument/API/Instrument.sendMessageToProcess.vi"
File 135="user.lib/Levylab/Instrument Framework/Instrument/API/Local Client.vi"
File 136="user.lib/Levylab/Instrument Framework/Instrument/API/Open.vi"
File 137="user.lib/Levylab/Instrument Framework/Instrument/API/Read Configuration Class.vi"
File 138="user.lib/Levylab/Instrument Framework/Instrument/API/Read Hardware Address.vi"
File 139="user.lib/Levylab/Instrument Framework/Instrument/API/Read SMO Address.vi"
File 140="user.lib/Levylab/Instrument Framework/Instrument/API/Remote Client.vi"
File 141="user.lib/Levylab/Instrument Framework/Instrument/API/Send and Receive.vi"
File 142="user.lib/Levylab/Instrument Framework/Instrument/API/Write Client Type.vi"
File 143="user.lib/Levylab/Instrument Framework/Instrument/API/Write Hardware Address.vi"
File 144="user.lib/Levylab/Instrument Framework/Instrument/API/Write RC Type.vi"


[File Group 1]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="Always"
Num Files=16
File 0="_functions_levylab_lib_levylab_instruments_1.mnu"
File 1="_functions_levylab_lib_levylab_instruments_10.mnu"
File 2="_functions_levylab_lib_levylab_instruments_11.mnu"
File 3="_functions_levylab_lib_levylab_instruments_12.mnu"
File 4="_functions_levylab_lib_levylab_instruments_13.mnu"
File 5="_functions_levylab_lib_levylab_instruments_14.mnu"
File 6="_functions_levylab_lib_levylab_instruments_15.mnu"
File 7="_functions_levylab_lib_levylab_instruments_2.mnu"
File 8="_functions_levylab_lib_levylab_instruments_3.mnu"
File 9="_functions_levylab_lib_levylab_instruments_4.mnu"
File 10="_functions_levylab_lib_levylab_instruments_5.mnu"
File 11="_functions_levylab_lib_levylab_instruments_6.mnu"
File 12="_functions_levylab_lib_levylab_instruments_7.mnu"
File 13="_functions_levylab_lib_levylab_instruments_8.mnu"
File 14="_functions_levylab_lib_levylab_instruments_9.mnu"
File 15="functions_Levylab_lib_Levylab_Instruments.mnu"


[File Group 2]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="If Newer"
Num Files=1
File 0="dir.mnu"
