[Package]
Name="jki_lib_flat_controls"
Version="1.0.0.7"
Release=""
ID=729d8166a4f4892192516864ac352b3c
File Format="vip"
Format Version="2014"
Display Name="JKI Flat UI Controls"


[Description]
Description="JKI Flat UI Controls for LabVIEW provides a set of flat UI controls designed by JKI with a dark and light color theme."
Summary="Modern flat front panel element library for LabVIEW"
License="JKI Toolkit License"
Copyright="Copyright (c) 2017, JKI"
Distribution=""
Vendor="JKI"
URL="http://jki.net/tools#flatui"
Packager="Eric Welden"
Demo="FALSE"
Release Notes="Initial release."
System Package="FALSE"
Sub Package="FALSE"
License Agreement="TRUE"


[LabVIEW]
close labview before install="FALSE"
restart labview after install="FALSE"
skip mass compile after install="FALSE"


[Platform]
Exclusive_LabVIEW_Version="LabVIEW>=14.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="ALL"


[Script VIs]
PreInstall=""
PostInstall=""
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires=""
Conflicts=""


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="2"
Sub-Packages=""
Namespaces=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=120
File 0="vi.lib/JKI/JKI Flat UI Controls/Light/String & Path/Path-light.ctl"
File 1="vi.lib/JKI/JKI Flat UI Controls/Light/String & Path/String-light.ctl"
File 2="vi.lib/JKI/JKI Flat UI Controls/Light/Ring & Enum/ComboBox200x30-light.ctl"
File 3="vi.lib/JKI/JKI Flat UI Controls/Light/Ring & Enum/ComboBox200x50-light.ctl"
File 4="vi.lib/JKI/JKI Flat UI Controls/Light/Ring & Enum/Enum200x30-light.ctl"
File 5="vi.lib/JKI/JKI Flat UI Controls/Light/Ring & Enum/Enum200x50-light.ctl"
File 6="vi.lib/JKI/JKI Flat UI Controls/Light/Ring & Enum/Ring200x30-light.ctl"
File 7="vi.lib/JKI/JKI Flat UI Controls/Light/Ring & Enum/Ring200x50-light.ctl"
File 8="vi.lib/JKI/JKI Flat UI Controls/Light/Numeric/Numeric-light.ctl"
File 9="vi.lib/JKI/JKI Flat UI Controls/Light/Numeric/NumericIncrement-light.ctl"
File 10="vi.lib/JKI/JKI Flat UI Controls/Light/Numeric/SliderHorizontal-light.ctl"
File 11="vi.lib/JKI/JKI Flat UI Controls/Light/Numeric/SliderVertical-light.ctl"
File 12="vi.lib/JKI/JKI Flat UI Controls/Light/IO/DAQChannel-light.ctl"
File 13="vi.lib/JKI/JKI Flat UI Controls/Light/IO/VISAResource-light.ctl"
File 14="vi.lib/JKI/JKI Flat UI Controls/Light/Graph/IntensityGraph-light.ctl"
File 15="vi.lib/JKI/JKI Flat UI Controls/Light/Graph/WaveformChart-light.ctl"
File 16="vi.lib/JKI/JKI Flat UI Controls/Light/Graph/WaveformGraph-light.ctl"
File 17="vi.lib/JKI/JKI Flat UI Controls/Light/Graph/XYGraph-light.ctl"
File 18="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/RadioButtonCheckmark-light.ctl"
File 19="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/RadioButtonSquareBox-light.ctl"
File 20="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/RadioButtonWholeBox-light.ctl"
File 21="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/RadioButtonXBox-light.ctl"
File 22="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/RadioTabControl-light.ctl"
File 23="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/AbortBoolean-48x48-light.ctl"
File 24="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/AbortBoolean-light.ctl"
File 25="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/ArrowDownBoolean-light.ctl"
File 26="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/ArrowLeftBoolean-light.ctl"
File 27="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/ArrowRightBoolean-light.ctl"
File 28="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/ArrowUpBoolean-light.ctl"
File 29="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/BlankBoolean-light.ctl"
File 30="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/CheckboxBoolean-light.ctl"
File 31="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/ConfigBoolean-48x48-light.ctl"
File 32="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/ConfigBoolean-light.ctl"
File 33="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/FirstBoolean-48x48-light.ctl"
File 34="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/LastBoolean-48x48-light.ctl"
File 35="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/NewBoolean-48x48-light.ctl"
File 36="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/NewBoolean-light.ctl"
File 37="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/OpenBoolean-48x48-light.ctl"
File 38="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/OpenBoolean-light.ctl"
File 39="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/PauseBoolean-48x48-light.ctl"
File 40="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/PauseBoolean-light.ctl"
File 41="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/ResetBoolean-48x48-light.ctl"
File 42="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/ResetBoolean200x60-light.ctl"
File 43="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/SaveBoolean-48x48-light.ctl"
File 44="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/SaveBoolean-light.ctl"
File 45="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/StartBoolean-48x48-light.ctl"
File 46="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/StartBoolean-light.ctl"
File 47="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/StopBoolean-48x48-light.ctl"
File 48="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/StopBoolean-light.ctl"
File 49="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/Transparent/CloseXBoolean48x48-dark.ctl"
File 50="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/Transparent/ConfigBoolean-nav-48x48-dark.ctl"
File 51="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/Transparent/ExpandCollapseBoolean-dark.ctl"
File 52="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/Transparent/HelpBoolean-dark.ctl"
File 53="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/Transparent/InfoBoolean-dark.ctl"
File 54="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/Transparent/Menu-dark.ctl"
File 55="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/Transparent/Menu2-dark.ctl"
File 56="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/Transparent/MinimizeBoolean-dark.ctl"
File 57="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/Transparent/PowerBoolean-dark.ctl"
File 58="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/Transparent/SearchBoolean-dark.ctl"
File 59="vi.lib/JKI/JKI Flat UI Controls/Light/Boolean/Buttons/Transparent/UserBoolean-dark.ctl"
File 60="vi.lib/JKI/JKI Flat UI Controls/Dark/String & Path/Path-dark.ctl"
File 61="vi.lib/JKI/JKI Flat UI Controls/Dark/String & Path/String-dark.ctl"
File 62="vi.lib/JKI/JKI Flat UI Controls/Dark/Ring & Enum/ComboBox200x30-dark.ctl"
File 63="vi.lib/JKI/JKI Flat UI Controls/Dark/Ring & Enum/ComboBox200x50-dark.ctl"
File 64="vi.lib/JKI/JKI Flat UI Controls/Dark/Ring & Enum/Enum200x30-dark.ctl"
File 65="vi.lib/JKI/JKI Flat UI Controls/Dark/Ring & Enum/Enum200x50-dark.ctl"
File 66="vi.lib/JKI/JKI Flat UI Controls/Dark/Ring & Enum/Ring200x30-dark.ctl"
File 67="vi.lib/JKI/JKI Flat UI Controls/Dark/Ring & Enum/Ring200x50-dark.ctl"
File 68="vi.lib/JKI/JKI Flat UI Controls/Dark/Numeric/Numeric-dark.ctl"
File 69="vi.lib/JKI/JKI Flat UI Controls/Dark/Numeric/NumericIncrement-dark.ctl"
File 70="vi.lib/JKI/JKI Flat UI Controls/Dark/Numeric/SliderHorizontal-dark.ctl"
File 71="vi.lib/JKI/JKI Flat UI Controls/Dark/Numeric/SliderVertical-dark.ctl"
File 72="vi.lib/JKI/JKI Flat UI Controls/Dark/IO/DAQChannel-dark.ctl"
File 73="vi.lib/JKI/JKI Flat UI Controls/Dark/IO/VISAResource-dark.ctl"
File 74="vi.lib/JKI/JKI Flat UI Controls/Dark/Graph/IntensityGraph-dark.ctl"
File 75="vi.lib/JKI/JKI Flat UI Controls/Dark/Graph/WaveformChart-dark.ctl"
File 76="vi.lib/JKI/JKI Flat UI Controls/Dark/Graph/WaveformGraph-dark.ctl"
File 77="vi.lib/JKI/JKI Flat UI Controls/Dark/Graph/XYGraph-dark.ctl"
File 78="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/RadioButtonCheckmark-dark.ctl"
File 79="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/RadioButtonSquareBox-dark.ctl"
File 80="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/RadioButtonWholeBox-dark.ctl"
File 81="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/RadioButtonXBox-dark.ctl"
File 82="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/RadioTabControl-dark.ctl"
File 83="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/AbortBoolean-48x48-dark.ctl"
File 84="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/AbortBoolean-dark.ctl"
File 85="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/ArrowDownBoolean-dark.ctl"
File 86="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/ArrowLeftBoolean-dark.ctl"
File 87="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/ArrowRightBoolean-dark.ctl"
File 88="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/ArrowUpBoolean-dark.ctl"
File 89="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/BlankBoolean-dark.ctl"
File 90="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/CheckboxBoolean-dark.ctl"
File 91="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/ConfigBoolean-48x48-dark.ctl"
File 92="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/ConfigBoolean-dark.ctl"
File 93="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/FirstBoolean-48x48-dark.ctl"
File 94="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/LastBoolean-48x48-dark.ctl"
File 95="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/NewBoolean-48x48-dark.ctl"
File 96="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/NewBoolean-dark.ctl"
File 97="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/OpenBoolean-48x48-dark.ctl"
File 98="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/OpenBoolean-dark.ctl"
File 99="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/PauseBoolean-48x48-dark.ctl"
File 100="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/PauseBoolean-dark.ctl"
File 101="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/ResetBoolean-48x48-dark.ctl"
File 102="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/ResetBoolean200x60-dark.ctl"
File 103="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/SaveBoolean-48x48-dark.ctl"
File 104="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/SaveBoolean-dark.ctl"
File 105="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/StartBoolean-48x48-dark.ctl"
File 106="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/StartBoolean-dark.ctl"
File 107="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/StopBoolean-48x48-dark.ctl"
File 108="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/StopBoolean-dark.ctl"
File 109="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/Transparent/CloseXBoolean48x48-light.ctl"
File 110="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/Transparent/ConfigBoolean-nav-48x48-light.ctl"
File 111="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/Transparent/ExpandCollapseBoolean-light.ctl"
File 112="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/Transparent/HelpBoolean-light.ctl"
File 113="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/Transparent/InfoBoolean-light.ctl"
File 114="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/Transparent/Menu-light.ctl"
File 115="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/Transparent/Menu2-light.ctl"
File 116="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/Transparent/MinimizeBoolean-light.ctl"
File 117="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/Transparent/PowerBoolean-light.ctl"
File 118="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/Transparent/SearchBoolean-light.ctl"
File 119="vi.lib/JKI/JKI Flat UI Controls/Dark/Boolean/Buttons/Transparent/UserBoolean-light.ctl"


[File Group 1]
Target Dir="<menus>/Controls"
Replace Mode="Always"
Num Files=19
File 0="_controls_jki_lib_flat_controls_1.mnu"
File 1="_controls_jki_lib_flat_controls_10.mnu"
File 2="_controls_jki_lib_flat_controls_11.mnu"
File 3="_controls_jki_lib_flat_controls_12.mnu"
File 4="_controls_jki_lib_flat_controls_13.mnu"
File 5="_controls_jki_lib_flat_controls_14.mnu"
File 6="_controls_jki_lib_flat_controls_15.mnu"
File 7="_controls_jki_lib_flat_controls_16.mnu"
File 8="_controls_jki_lib_flat_controls_17.mnu"
File 9="_controls_jki_lib_flat_controls_18.mnu"
File 10="_controls_jki_lib_flat_controls_2.mnu"
File 11="_controls_jki_lib_flat_controls_3.mnu"
File 12="_controls_jki_lib_flat_controls_4.mnu"
File 13="_controls_jki_lib_flat_controls_5.mnu"
File 14="_controls_jki_lib_flat_controls_6.mnu"
File 15="_controls_jki_lib_flat_controls_7.mnu"
File 16="_controls_jki_lib_flat_controls_8.mnu"
File 17="_controls_jki_lib_flat_controls_9.mnu"
File 18="controls_jki_lib_flat_controls.mnu"
