[Package]
Name="levylab_lib_leiden_api"
Version="0.0.2.5"
Release=""
ID=326f64f92331cebb94d6ae60980a5e1e
File Format="vip"
Format Version="2017"
Display Name="LEIDEN API"


[Description]
Description="Tools used by LevyLab to interact with Leiden Cryostats \0A\0AFront Panel (FP) API:\0A- pushButton({Start, 3He, 4He, Normal, Recovery, Auto, Reset, LED Test})\0A- setMode({Auto Off, Start, Condense 3He, Condense 4He, Normal Circulation, Recovery})\0A- getMode()\0A\0ATemperature Control (TC) API:\0A- getTemperature()\0A- setTemperature()\0A- setHeater()\0A- getHeater()"
Summary=""
License="BSD-3"
Copyright="Copyright (c) 2026, LevyLab"
Distribution=""
Vendor="LevyLab"
URL=""
Packager="Patrick Irvin"
Demo="FALSE"
Release Notes="[0.0.2]\0A- build with pgsql/3.12.0.14 (with improved database connection management)"
System Package="FALSE"
Sub Package="FALSE"
License Agreement="TRUE"


[LabVIEW]
close labview before install="FALSE"
restart labview after install="FALSE"
skip mass compile after install="FALSE"
install into global environment="FALSE"


[Platform]
Exclusive_LabVIEW_Version="LabVIEW>=19.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="ALL"


[Script VIs]
PreInstall=""
PostInstall=""
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires="levylab_lib_levylab_instruments>=1.15.9.45"
Conflicts="levylab_lib_leiden_fp>=0.0.0.0,levylab_lib_leiden_mnk>=0.0.0.0,levylab_lib_leiden_tc>=0.0.0.0,levylab_lib_leiden_tools>=0.0.0.0"


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="3"
Sub-Packages=""
Namespaces=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=119
File 0="user.lib/LevyLab/Leiden API/Inst.TC.MNK/Get Temperature.vi"
File 1="user.lib/LevyLab/Leiden API/Inst.TC.MNK/getTemperature.vi"
File 2="user.lib/LevyLab/Leiden API/Inst.TC.MNK/Inst.TC.MNK.lvclass"
File 3="user.lib/LevyLab/Leiden API/Inst.TC.MNK/Private/Read_MNK_Temperature.vi"
File 4="user.lib/LevyLab/Leiden API/Inst.TC.CF/Get Temperature.vi"
File 5="user.lib/LevyLab/Leiden API/Inst.TC.CF/getTemperature.vi"
File 6="user.lib/LevyLab/Leiden API/Inst.TC.CF/Inst.TC.CF.lvclass"
File 7="user.lib/LevyLab/Leiden API/Inst.TC.CF/Private/Read_CF_Temperature.vi"
File 8="user.lib/LevyLab/Leiden API/Inst.TC/Documentation.vi"
File 9="user.lib/LevyLab/Leiden API/Inst.TC/Inst.TC.lvclass"
File 10="user.lib/LevyLab/Leiden API/Inst.TC/Process.vi"
File 11="user.lib/LevyLab/Leiden API/Inst.TC/test_configuration.vi"
File 12="user.lib/LevyLab/Leiden API/Inst.TC/Typedefs/Inst.TC.Commands--Enum.ctl"
File 13="user.lib/LevyLab/Leiden API/Inst.TC/Typedefs/Inst.TC.Configuration--Cluster.ctl"
File 14="user.lib/LevyLab/Leiden API/Inst.TC/Typedefs/Inst.TC.DefaultPGSQLPaths--Cluster.ctl"
File 15="user.lib/LevyLab/Leiden API/Inst.TC/Typedefs/Inst.TC.getAll--Cluster.ctl"
File 16="user.lib/LevyLab/Leiden API/Inst.TC/Typedefs/PrivateEvents--Cluster.ctl"
File 17="user.lib/LevyLab/Leiden API/Inst.TC/Typedefs/PrivateEvents--Inst.TC.MessageToProcess.ctl"
File 18="user.lib/LevyLab/Leiden API/Inst.TC/Typedefs/PublicEvents--Cluster.ctl"
File 19="user.lib/LevyLab/Leiden API/Inst.TC/Typedefs/PublicEvents--Inst.TC.MessageFromProcess.ctl"
File 20="user.lib/LevyLab/Leiden API/Inst.TC/Private/AVS Names to List.vi"
File 21="user.lib/LevyLab/Leiden API/Inst.TC/Private/Calibration to List.vi"
File 22="user.lib/LevyLab/Leiden API/Inst.TC/Private/Inst.TC.GetPrivateEvents.vi"
File 23="user.lib/LevyLab/Leiden API/Inst.TC/Overrides/Close Hardware.vi"
File 24="user.lib/LevyLab/Leiden API/Inst.TC/Overrides/Configuration Window.vi"
File 25="user.lib/LevyLab/Leiden API/Inst.TC/Overrides/CreatePrivateEvents.vi"
File 26="user.lib/LevyLab/Leiden API/Inst.TC/Overrides/CreatePublicEvents.vi"
File 27="user.lib/LevyLab/Leiden API/Inst.TC/Overrides/DestroyPrivateEvents.vi"
File 28="user.lib/LevyLab/Leiden API/Inst.TC/Overrides/DestroyPublicEvents.vi"
File 29="user.lib/LevyLab/Leiden API/Inst.TC/Overrides/Get SMO Database Paths.vi"
File 30="user.lib/LevyLab/Leiden API/Inst.TC/Overrides/Get SMO Name.vi"
File 31="user.lib/LevyLab/Leiden API/Inst.TC/Overrides/Get SMO Port.vi"
File 32="user.lib/LevyLab/Leiden API/Inst.TC/Overrides/Get SMO Public API.vi"
File 33="user.lib/LevyLab/Leiden API/Inst.TC/Overrides/Handle Command.vi"
File 34="user.lib/LevyLab/Leiden API/Inst.TC/Overrides/Handle getAll.vi"
File 35="user.lib/LevyLab/Leiden API/Inst.TC/Overrides/Handle setAllData.vi"
File 36="user.lib/LevyLab/Leiden API/Inst.TC/Overrides/Handle setConfiguration.vi"
File 37="user.lib/LevyLab/Leiden API/Inst.TC/Overrides/Open Hardware.vi"
File 38="user.lib/LevyLab/Leiden API/Inst.TC/Overrides/Read Configuration File.vi"
File 39="user.lib/LevyLab/Leiden API/Inst.TC/Overrides/Write Configuration File.vi"
File 40="user.lib/LevyLab/Leiden API/Inst.TC/API/Close.vi"
File 41="user.lib/LevyLab/Leiden API/Inst.TC/API/getHeater.vi"
File 42="user.lib/LevyLab/Leiden API/Inst.TC/API/Inst.TC.Create.vi"
File 43="user.lib/LevyLab/Leiden API/Inst.TC/API/Inst.TC.GetPublicEvents.vi"
File 44="user.lib/LevyLab/Leiden API/Inst.TC/API/Inst.TC.MessageToProcess.vi"
File 45="user.lib/LevyLab/Leiden API/Inst.TC/API/Open.vi"
File 46="user.lib/LevyLab/Leiden API/Inst.TC/API/Set Heater.vi"
File 47="user.lib/LevyLab/Leiden API/Inst.TC/API/setHeater.vi"
File 48="user.lib/LevyLab/Leiden API/Inst.TC/API/TC to PGSQL.vi"
File 49="user.lib/LevyLab/Leiden API/Inst.FP/Documentation.vi"
File 50="user.lib/LevyLab/Leiden API/Inst.FP/GHSButtons.vi"
File 51="user.lib/LevyLab/Leiden API/Inst.FP/Inst.FP.lvclass"
File 52="user.lib/LevyLab/Leiden API/Inst.FP/Inst.FP.TestLauncher.vi"
File 53="user.lib/LevyLab/Leiden API/Inst.FP/Process.vi"
File 54="user.lib/LevyLab/Leiden API/Inst.FP/Typedefs/Inst.FP.Buttons--Enum.ctl"
File 55="user.lib/LevyLab/Leiden API/Inst.FP/Typedefs/Inst.FP.Commands--Enum.ctl"
File 56="user.lib/LevyLab/Leiden API/Inst.FP/Typedefs/Inst.FP.Configuration--Cluster.ctl"
File 57="user.lib/LevyLab/Leiden API/Inst.FP/Typedefs/Inst.FP.DefaultPGSQLPaths--Cluster.ctl"
File 58="user.lib/LevyLab/Leiden API/Inst.FP/Typedefs/Inst.FP.getAll--Cluster.ctl"
File 59="user.lib/LevyLab/Leiden API/Inst.FP/Typedefs/Inst.FP.getMode--Cluster.ctl"
File 60="user.lib/LevyLab/Leiden API/Inst.FP/Typedefs/Inst.FP.Modes(set)--Enum.ctl"
File 61="user.lib/LevyLab/Leiden API/Inst.FP/Typedefs/Inst.FP.Modes--Enum.ctl"
File 62="user.lib/LevyLab/Leiden API/Inst.FP/Typedefs/Inst.FP.pushButton--Cluster.ctl"
File 63="user.lib/LevyLab/Leiden API/Inst.FP/Typedefs/Inst.FP.setMode--Cluster.ctl"
File 64="user.lib/LevyLab/Leiden API/Inst.FP/Typedefs/Inst.FP.Type--Enum.ctl"
File 65="user.lib/LevyLab/Leiden API/Inst.FP/Typedefs/PrivateEvents--Cluster.ctl"
File 66="user.lib/LevyLab/Leiden API/Inst.FP/Typedefs/PrivateEvents--Inst.FP.MessageToProcess.ctl"
File 67="user.lib/LevyLab/Leiden API/Inst.FP/Typedefs/PublicEvents--Cluster.ctl"
File 68="user.lib/LevyLab/Leiden API/Inst.FP/Typedefs/PublicEvents--Inst.FP.MessageFromProcess.ctl"
File 69="user.lib/LevyLab/Leiden API/Inst.FP/Private/Handle setMode.vi"
File 70="user.lib/LevyLab/Leiden API/Inst.FP/Private/Inst.FP.GetPrivateEvents.vi"
File 71="user.lib/LevyLab/Leiden API/Inst.FP/Private/Inst.FP.GHSmodeStringToEnum.vi"
File 72="user.lib/LevyLab/Leiden API/Inst.FP/Private/Inst.FP.MessageFromProcess.vi"
File 73="user.lib/LevyLab/Leiden API/Inst.FP/Private/Inst.FP.ParseGHSmode.vi"
File 74="user.lib/LevyLab/Leiden API/Inst.FP/Overrides/Configuration Window.vi"
File 75="user.lib/LevyLab/Leiden API/Inst.FP/Overrides/CreatePrivateEvents.vi"
File 76="user.lib/LevyLab/Leiden API/Inst.FP/Overrides/CreatePublicEvents.vi"
File 77="user.lib/LevyLab/Leiden API/Inst.FP/Overrides/DELETE Get SMO RC Type.vi"
File 78="user.lib/LevyLab/Leiden API/Inst.FP/Overrides/DestroyPrivateEvents.vi"
File 79="user.lib/LevyLab/Leiden API/Inst.FP/Overrides/DestroyPublicEvents.vi"
File 80="user.lib/LevyLab/Leiden API/Inst.FP/Overrides/Get SMO Address.vi"
File 81="user.lib/LevyLab/Leiden API/Inst.FP/Overrides/Get SMO Database Paths.vi"
File 82="user.lib/LevyLab/Leiden API/Inst.FP/Overrides/Get SMO HELP getAll.vi"
File 83="user.lib/LevyLab/Leiden API/Inst.FP/Overrides/Get SMO HELP.vi"
File 84="user.lib/LevyLab/Leiden API/Inst.FP/Overrides/Get SMO Name.vi"
File 85="user.lib/LevyLab/Leiden API/Inst.FP/Overrides/Get SMO Port.vi"
File 86="user.lib/LevyLab/Leiden API/Inst.FP/Overrides/Get SMO Public API.vi"
File 87="user.lib/LevyLab/Leiden API/Inst.FP/Overrides/Get SMO Serial Number.vi"
File 88="user.lib/LevyLab/Leiden API/Inst.FP/Overrides/Get SMO Vendor.vi"
File 89="user.lib/LevyLab/Leiden API/Inst.FP/Overrides/Handle Command.vi"
File 90="user.lib/LevyLab/Leiden API/Inst.FP/Overrides/Handle getAll.vi"
File 91="user.lib/LevyLab/Leiden API/Inst.FP/Overrides/Read Configuration File.vi"
File 92="user.lib/LevyLab/Leiden API/Inst.FP/Overrides/Write Configuration File.vi"
File 93="user.lib/LevyLab/Leiden API/Inst.FP/API/Close.vi"
File 94="user.lib/LevyLab/Leiden API/Inst.FP/API/FP to PGSQL.vi"
File 95="user.lib/LevyLab/Leiden API/Inst.FP/API/getMode.vi"
File 96="user.lib/LevyLab/Leiden API/Inst.FP/API/Inst.FP.Create.vi"
File 97="user.lib/LevyLab/Leiden API/Inst.FP/API/Inst.FP.GetPublicEvents.vi"
File 98="user.lib/LevyLab/Leiden API/Inst.FP/API/Inst.FP.MessageToProcess.vi"
File 99="user.lib/LevyLab/Leiden API/Inst.FP/API/Open.vi"
File 100="user.lib/LevyLab/Leiden API/Inst.FP/API/pushButton.vi"
File 101="user.lib/LevyLab/Leiden API/Inst.FP/API/setMode.vi"
File 102="user.lib/LevyLab/Leiden API/Inst.FP/API/Write FP Type.vi"
File 103="user.lib/LevyLab/Leiden API/FP-TC-Shared/FP-TC-Shared.lvclass"
File 104="user.lib/LevyLab/Leiden API/FP-TC-Shared/Get LC Type.vi"
File 105="user.lib/LevyLab/Leiden API/FP-TC-Shared/Get Paths.vi"
File 106="user.lib/LevyLab/Leiden API/FP-TC-Shared/Initialize.vi"
File 107="user.lib/LevyLab/Leiden API/FP-TC-Shared/Read Last Known State.vi"
File 108="user.lib/LevyLab/Leiden API/FP-TC-Shared/Read Path Section.vi"
File 109="user.lib/LevyLab/Leiden API/FP-TC-Shared/Write Last Known State.vi"
File 110="user.lib/LevyLab/Leiden API/FP-TC-Shared/Write Path Section.vi"
File 111="user.lib/LevyLab/Leiden API/FP-TC-Shared/typedefs/Application Type--Enum.ctl"
File 112="user.lib/LevyLab/Leiden API/FP-TC-Shared/typedefs/Configuration--Cluster.ctl"
File 113="user.lib/LevyLab/Leiden API/FP-TC-Shared/typedefs/Default Database Paths.ctl"
File 114="user.lib/LevyLab/Leiden API/FP-TC-Shared/typedefs/LC Type--Enum.ctl"
File 115="user.lib/LevyLab/Leiden API/FP-TC-Shared/Private/Application Configuration Path.vi"
File 116="user.lib/LevyLab/Leiden API/FP-TC-Shared/Private/Default Configuration Path.vi"
File 117="user.lib/LevyLab/Leiden API/FP-TC-Shared/Private/Initialize Configuration File.vi"
File 118="user.lib/LevyLab/Leiden API/FP-TC-Shared/Private/Read PGSQL Paths.vi"


[File Group 1]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="Always"
Num Files=3
File 0="_functions_levylab_lib_leiden_api_1.mnu"
File 1="_functions_levylab_lib_leiden_api_2.mnu"
File 2="functions_LevyLab_lib_Leiden_API.mnu"


[File Group 2]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="If Newer"
Num Files=1
File 0="dir.mnu"
