[Package]
Name="levylab_lib_ppms_instrument"
Version="1.9.1.21"
Release=""
ID=886ccd5bd942ec3fbb2fe70dce4446e7
File Format="vip"
Format Version="2017"
Display Name="PPMS Monitor and Control"


[Description]
Description="Monitor and Control application inheritng from Instrument Framework and SMO\0A- Log instrument status to the PGSQL database.\0A- UI and API for controlling magnet field, temperature, and rotator angle (PPMS2 only)"
Summary=""
License="BSD-3"
Copyright="Copyright (c) 2025, LevyLab"
Distribution=""
Vendor="LevyLab"
URL="https://github.com/levylabpitt/PPMS-Monitor-and-Control"
Packager="Patrick Irvin"
Demo="FALSE"
Release Notes="[1.9.1]\0A- #31: move unit tests and remove Caraya dependencies"
System Package="FALSE"
Sub Package="FALSE"
License Agreement="TRUE"


[LabVIEW]
close labview before install="FALSE"
restart labview after install="FALSE"
skip mass compile after install="FALSE"
install into global environment="FALSE"


[Platform]
Exclusive_LabVIEW_Version="LabVIEW x86>=19.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="ALL"


[Script VIs]
PreInstall=""
PostInstall=""
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires="jdp_science_jsontext>=1.9.1.125,jdp_science_lib_common_utilities>=1.4.2.19,jdp_science_postgresql>=0.6.2.48,jki_lib_state_machine>=2018.0.7.45,jki_statemachineobjects>=1.4.0.69,labview-zmq>=3.6.3.113,labview_open_source_lib_epoch_datetime>=1.3.0.8,levylab_lib_fileutilities>=1.2.6.13,levylab_lib_instrument_type>=1.1.0.7,levylab_lib_lvtdatpgsql>=3.10.0.8,levylab_lib_lvtoitx>=3.10.0.9,levylab_lib_xy_utilities>=1.6.0.6,lvh_toolbox>=2.0.0.35,mgi_lib_1d_array>=1.0.2.3,mgi_lib_application_control>=1.1.1.10,mgi_lib_numeric>=1.1.0.2,national_instruments_lib_guid_generator>=1.0.2.3,oglib_appcontrol>=4.1.0.7,oglib_array>=4.1.1.14,oglib_boolean>=4.0.0.7,oglib_dictionary>=4.0.0.4,oglib_error>=4.2.0.23,oglib_file>=4.0.1.22,oglib_lvdata>=5.0.0.27,oglib_numeric>=4.1.0.8,oglib_string>=5.0.0.25,oglib_time>=4.0.1.3,oglib_variantconfig>=4.0.0.5,prirvin_lib_json_rpc>=1.2.6.15,prirvin_lib_json_schema>=0.1.4.8"
Conflicts=""


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="3"
Sub-Packages=""
Namespaces=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=149
File 0="user.lib/LevyLab/PPMS Instrument/PPMS Monitor and Control.vi"
File 1="user.lib/LevyLab/PPMS Instrument/PPMS/Get PPMS Class.vi"
File 2="user.lib/LevyLab/PPMS Instrument/PPMS/PPMS.lvlib"
File 3="user.lib/LevyLab/PPMS Instrument/PPMS/Select PPMS Class.vi"
File 4="user.lib/LevyLab/PPMS Instrument/PPMS/Select PPMS--Enum.ctl"
File 5="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Get SMO Database Paths.vi"
File 6="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Get SMO Name.vi"
File 7="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Get SMO Port.vi"
File 8="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Get SMO Public API.vi"
File 9="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/getAllsubset.vi"
File 10="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/instrument.PPMS3.lvclass"
File 11="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Magnet Limits.vi"
File 12="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get SMO Database Paths.vi"
File 13="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get SMO Name.vi"
File 14="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get SMO Port.vi"
File 15="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get SMO Public API.vi"
File 16="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/getAllsubset.vi"
File 17="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/instrument.PPMS2.lvclass"
File 18="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Magnet Limits.vi"
File 19="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/PPMS.getAll.vi"
File 20="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/PPMS2 Current to Field (Oe).vi"
File 21="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/PPMS2 Field (Oe) to Current.vi"
File 22="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/PPMS2 Field (T) to Current.vi"
File 23="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Get SMO Database Paths.vi"
File 24="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Get SMO Name.vi"
File 25="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Get SMO Port.vi"
File 26="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Get SMO Public API.vi"
File 27="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/getAllsubset.vi"
File 28="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/instrument.PPMS1.lvclass"
File 29="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Magnet Limits.vi"
File 30="user.lib/LevyLab/PPMS Instrument/instrument.PPMS UI/Instrument UI.PPMS.lvclass"
File 31="user.lib/LevyLab/PPMS Instrument/instrument.PPMS UI/Process.vi"
File 32="user.lib/LevyLab/PPMS Instrument/instrument.PPMS UI/private/Convert Number to String.vi"
File 33="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Close Hardware.vi"
File 34="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Close.vi"
File 35="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Convert Oersted to Tesla.vi"
File 36="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Convert Tesla to Oersted.vi"
File 37="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/CreatePrivateEvents.vi"
File 38="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/DestroyPrivateEvents.vi"
File 39="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get SMO Database Paths.vi"
File 40="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get SMO HELP getAll.vi"
File 41="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get SMO HELP.vi"
File 42="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get SMO Name.vi"
File 43="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get SMO Port.vi"
File 44="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get SMO Public API.vi"
File 45="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get SMO Serial Number.vi"
File 46="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get SMO Vendor.vi"
File 47="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/getAllsubset.vi"
File 48="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/getAngle.vi"
File 49="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/getChamber.vi"
File 50="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/getLHeLevel.vi"
File 51="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/getMagnet.vi"
File 52="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/getTemperature.vi"
File 53="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Handle Command.vi"
File 54="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Handle getAll.vi"
File 55="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Handle setAllData.vi"
File 56="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/instrument.PPMS.lvclass"
File 57="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Magnet Limits.vi"
File 58="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Open Hardware.vi"
File 59="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Open.vi"
File 60="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Chamber Action to Ring.vi"
File 61="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Chamber Status Ring to String.vi"
File 62="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Close.vi"
File 63="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.getAll.vi"
File 64="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.getAngle.vi"
File 65="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.getChamber.vi"
File 66="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.getLHeLevel.vi"
File 67="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.getMagnet.vi"
File 68="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.GetPrivateEvents.vi"
File 69="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.getTemperature.vi"
File 70="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Magnet Status Ring to String.vi"
File 71="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Open.vi"
File 72="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.sendMessageToProcess.vi"
File 73="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.setAngle.vi"
File 74="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.setChamber.vi"
File 75="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.setMagnet.vi"
File 76="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.setTemperature.vi"
File 77="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Temperature Status Ring to String.vi"
File 78="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.TestLauncher.vi"
File 79="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Process.vi"
File 80="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Read getAll.vi"
File 81="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Read InstrumentType.vi"
File 82="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/setAngle.vi"
File 83="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/setChamber.vi"
File 84="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/setMagnet.vi"
File 85="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/setTemperature.vi"
File 86="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Simple Test.vi"
File 87="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Test Create Start Stop Destroy.vi"
File 88="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Test Open Close.vi"
File 89="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Wait Progress Bar.vi"
File 90="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Write getAll.vi"
File 91="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Write InstrumentType.vi"
File 92="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Chamber Command--enum.ctl"
File 93="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Chamber Status--ring.ctl"
File 94="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.getAll--cluster.ctl"
File 95="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Magnet Status--cluster.ctl"
File 96="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Magnet Status--ring.ctl"
File 97="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.setTemperature--cluster.ctl"
File 98="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Temperature Status--cluster.ctl"
File 99="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Temperature Status--ring.ctl"
File 100="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/Private Events--Cluster.ctl"
File 101="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/Private Events--MessageToProcess.ctl"
File 102="user.lib/LevyLab/PPMS Instrument/instrument.OptiCool/Get SMO Database Paths.vi"
File 103="user.lib/LevyLab/PPMS Instrument/instrument.OptiCool/Get SMO Name.vi"
File 104="user.lib/LevyLab/PPMS Instrument/instrument.OptiCool/Get SMO Port.vi"
File 105="user.lib/LevyLab/PPMS Instrument/instrument.OptiCool/Get SMO Public API.vi"
File 106="user.lib/LevyLab/PPMS Instrument/instrument.OptiCool/getAllsubset.vi"
File 107="user.lib/LevyLab/PPMS Instrument/instrument.OptiCool/instrument.OptiCool.lvclass"
File 108="user.lib/LevyLab/PPMS Instrument/instrument.OptiCool/Magnet Limits.vi"
File 109="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument.dll"
File 110="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument_Example.vi"
File 111="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument_Example_Simple.vi"
File 112="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument_Server.exe"
File 113="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/ReleaseNotes.txt"
File 114="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetChamber.vi"
File 115="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetField.vi"
File 116="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetHelium.vi"
File 117="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetPosition.vi"
File 118="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetTemperature.vi"
File 119="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/OpenQDInstrument.vi"
File 120="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/QDInstrumentExceptionHandler.vi"
File 121="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/SetChamber.vi"
File 122="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/SetField.vi"
File 123="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/SetPosition.vi"
File 124="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/SetTemperature.vi"
File 125="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/WaitFor.vi"
File 126="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/GetPPMSItem.vi"
File 127="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/GetPPMSItem_Example.vi"
File 128="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/SendPPMSCommand.vi"
File 129="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/SendPPMSCommand_Example.vi"
File 130="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/SendPPMSCommand_Rotator.vi"
File 131="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_Float_Example.vi"
File 132="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_Float_Write_Example.vi"
File 133="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_Write_QDInstrument/WriteSDO_FLT.vi"
File 134="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_Write_QDInstrument/WriteSDO_S16.vi"
File 135="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_Write_QDInstrument/WriteSDO_S32.vi"
File 136="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_Write_QDInstrument/WriteSDO_S8.vi"
File 137="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_Write_QDInstrument/WriteSDO_STR.vi"
File 138="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_Write_QDInstrument/WriteSDO_U16.vi"
File 139="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_Write_QDInstrument/WriteSDO_U32.vi"
File 140="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_Write_QDInstrument/WriteSDO_U8.vi"
File 141="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument/ReadSDO_FLT.vi"
File 142="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument/ReadSDO_S16.vi"
File 143="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument/ReadSDO_S32.vi"
File 144="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument/ReadSDO_S8.vi"
File 145="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument/ReadSDO_STR.vi"
File 146="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument/ReadSDO_U16.vi"
File 147="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument/ReadSDO_U32.vi"
File 148="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument/ReadSDO_U8.vi"


[File Group 1]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="Always"
Num Files=1
File 0="functions_levylab_lib_ppms_instrument.mnu"


[File Group 2]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="If Newer"
Num Files=1
File 0="dir.mnu"
