[Package]
Name="levylab_lib_ppms_instrument"
Version="1.7.0.45"
Release=""
ID=9002200c83377bfd6e60887990bf473a
File Format="vip"
Format Version="2017"
Display Name="PPMS Monitor and Control"


[Description]
Description="Program for logging PPMS status to the DSC. Provides a UI and API for controlling the magnet field, temperature, and rotator angle (for PPM2)"
Summary=""
License="BSD-3"
Copyright="Copyright (c) 2021, LevyLab"
Distribution=""
Vendor="LevyLab"
URL="https://github.com/levylabpitt/PPMS-Monitor-and-Control"
Packager="Patrick Irvin"
Demo="FALSE"
Release Notes="[1.7.0]\0D\0A- Add support for PPMS3 and simulated PPMS (Must install MultiVu Simulation Mode and QD Instrument Server)\0A- Major reorganization of project hierarchy\0A- Update to latest Instrument Framework (v1.8.1)"
System Package="FALSE"
Sub Package="FALSE"
License Agreement="TRUE"


[LabVIEW]
close labview before install="FALSE"
restart labview after install="FALSE"
skip mass compile after install="FALSE"


[Platform]
Exclusive_LabVIEW_Version="LabVIEW>=16.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="ALL"


[Script VIs]
PreInstall=""
PostInstall=""
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires="jdp_science_postgresql>=0.1.1.10,jki_lib_json_serialization>=1.1.10.37,jki_lib_serialization>=1.0.1.14,jki_lib_state_machine>=2018.0.7.45,jki_statemachineobjects>=1.3.0.56,labview-zmq>=3.5.1.109,lava_lib_ui_tools>=1.4.1.74,levylab_lib_fileutilities>=1.2.6.13,levylab_lib_graph_utilities>=2.1.2.4,levylab_lib_lvtoitx>=3.0.5.13,levylab_lib_postgresql>=1.2.3.16,levylab_lib_xy_utilities>=1.3.2.16,mgi_lib_1d_array>=1.0.2.3,mgi_lib_application_control>=1.1.1.10,mgi_lib_cluster>=1.1.0.1,mgi_lib_error_handling>=1.1.1.3,mgi_lib_error_reporter>=1.0.2.5,mgi_lib_file>=1.1.0.4,mgi_lib_numeric>=1.1.0.2,mgi_lib_picture_&_image>=1.0.2.1,mgi_lib_read_write_anything>=2.1.4.4,mgi_lib_string>=1.1.1.5,national_instruments_lib_guid_generator>=1.0.2.3,ni_lib_stm>=3.1.0.9,oglib_appcontrol>=4.1.0.7,oglib_array>=4.1.1.14,oglib_dictionary>=4.0.0.4,oglib_error>=4.2.0.23,oglib_file>=4.0.1.22,oglib_lvdata>=4.2.0.21,oglib_lvzip>=4.0.1,oglib_numeric>=4.1.0.8,oglib_string>=4.1.0.12,oglib_time>=4.0.1.3,oglib_variantconfig>=4.0.0.5,levylab_lib_levylab_instruments>=1.7.0.95"
Conflicts=""


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="3"
Sub-Packages=""
Namespaces=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=127
File 0="user.lib/LevyLab/PPMS Instrument/PPMS Monitor and Control.vi"
File 1="user.lib/LevyLab/PPMS Instrument/PPMS_inst.lvproj"
File 2="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Get Helium Level.vi"
File 3="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Get Magnet Field.vi"
File 4="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Get SMO Name.vi"
File 5="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Get SMO PGSQL Log Paths.vi"
File 6="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Get SMO Port.vi"
File 7="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Get SMO Public API.vi"
File 8="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Get Temperature.vi"
File 9="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/getAll.vi"
File 10="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/instrument.PPMS3.lvclass"
File 11="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/instrument.PPMS3.TestLauncher.vi"
File 12="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Magnet Limits.vi"
File 13="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/PPMS.Command Enum to String.vi"
File 14="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/PPMS3.Remote Client.vi"
File 15="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Process.vi"
File 16="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Set Magnet Field.vi"
File 17="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Set Temperature.vi"
File 18="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Typedefs/PPMS3.Commands-enum.ctl"
File 19="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get Angle.vi"
File 20="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get Helium Level.vi"
File 21="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get Magnet Field.vi"
File 22="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get SMO Name.vi"
File 23="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get SMO PGSQL Log Paths.vi"
File 24="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get SMO Port.vi"
File 25="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get SMO Public API.vi"
File 26="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get Temperature.vi"
File 27="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/getAll.vi"
File 28="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/instrument.PPMS2.lvclass"
File 29="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/instrument.PPMS2.TestLauncher.vi"
File 30="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Magnet Limits.vi"
File 31="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/PPMS2 Current to Field (Oe).vi"
File 32="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/PPMS2 Field (Oe) to Current.vi"
File 33="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/PPMS2 Field (T) to Current.vi"
File 34="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/PPMS2.Command Enum to String.vi"
File 35="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/PPMS2.Remote Client.vi"
File 36="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Process.vi"
File 37="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Set Angle.vi"
File 38="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Set Magnet Field.vi"
File 39="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Set Temperature.vi"
File 40="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Typedefs/PPMS2.Commands-enum.ctl"
File 41="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Get Helium Level.vi"
File 42="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Get Magnet Field.vi"
File 43="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Get SMO Name.vi"
File 44="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Get SMO PGSQL Log Paths.vi"
File 45="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Get SMO Port.vi"
File 46="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Get SMO Public API.vi"
File 47="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Get Temperature.vi"
File 48="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/getAll.vi"
File 49="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/instrument.PPMS1.lvclass"
File 50="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/instrument.PPMS1.TestLauncher.vi"
File 51="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Magnet Limits.vi"
File 52="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/PPMS1.Command Enum to String.vi"
File 53="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/PPMS1.Remote Client.vi"
File 54="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Process.vi"
File 55="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Set Magnet Field.vi"
File 56="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Set Temperature.vi"
File 57="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Typedefs/PPMS1.Commands-enum.ctl"
File 58="user.lib/LevyLab/PPMS Instrument/instrument.PPMS UI/Instrument UI.PPMS.lvclass"
File 59="user.lib/LevyLab/PPMS Instrument/instrument.PPMS UI/Process.vi"
File 60="user.lib/LevyLab/PPMS Instrument/instrument.PPMS UI/TEST.vi"
File 61="user.lib/LevyLab/PPMS Instrument/instrument.PPMS UI/private/Convert Number to String.vi"
File 62="user.lib/LevyLab/PPMS Instrument/instrument.PPMS UI/private/Elapsed Time String.vi"
File 63="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Close Instrument.vi"
File 64="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Convert Oersted to Tesla.vi"
File 65="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Convert Tesla to Oersted.vi"
File 66="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get PPMS Class.vi"
File 67="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get SMO PGSQL Log Paths.vi"
File 68="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/getAll.vi"
File 69="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Handle Command.vi"
File 70="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/instrument.PPMS.lvclass"
File 71="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/instrument.PPMS.TestLauncher.vi"
File 72="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Magnet Limits.vi"
File 73="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Open Instrument.vi"
File 74="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Get Angle.vi"
File 75="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Get Helium Level.vi"
File 76="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Get Magnet.vi"
File 77="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Get Temperature.vi"
File 78="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Set Angle.vi"
File 79="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Set Magnet.vi"
File 80="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Set Temperature.vi"
File 81="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Status Ring to String.vi"
File 82="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Process.vi"
File 83="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Select PPMS Class.vi"
File 84="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Test Create Start Stop Destroy.vi"
File 85="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Wait Progress Bar.vi"
File 86="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Commands-enum.ctl"
File 87="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.getAll--cluster.ctl"
File 88="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Magnet Field--cluster.ctl"
File 89="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Magnet Status--cluster.ctl"
File 90="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Magnet Status--ring.ctl"
File 91="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Temperature Status--cluster.ctl"
File 92="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Temperature Status--ring.ctl"
File 93="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Temperature--cluster.ctl"
File 94="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/Select PPMS--Enum.ctl"
File 95="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument.dll"
File 96="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument.llx"
File 97="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument_Example.vi"
File 98="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument_Example_Simple.vi"
File 99="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument_Server.exe"
File 100="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/ReleaseNotes.txt"
File 101="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetChamber.vi"
File 102="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetField.vi"
File 103="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetHelium.vi"
File 104="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetPosition.vi"
File 105="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetTemperature.vi"
File 106="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/OpenQDInstrument.vi"
File 107="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/QDInstrumentExceptionHandler.vi"
File 108="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/SetChamber.vi"
File 109="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/SetField.vi"
File 110="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/SetPosition.vi"
File 111="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/SetTemperature.vi"
File 112="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/WaitFor.vi"
File 113="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/GetPPMSItem.vi"
File 114="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/GetPPMSItem_Example.vi"
File 115="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/SendPPMSCommand.vi"
File 116="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/SendPPMSCommand_Example.vi"
File 117="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/SendPPMSCommand_Rotator.vi"
File 118="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_Float_Example.vi"
File 119="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_FLT.vi"
File 120="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_S16.vi"
File 121="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_S32.vi"
File 122="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_S8.vi"
File 123="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_STR.vi"
File 124="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_U16.vi"
File 125="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_U32.vi"
File 126="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_U8.vi"


[File Group 1]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="Always"
Num Files=11
File 0="_functions_levylab_lib_ppms_instrument_1.mnu"
File 1="_functions_levylab_lib_ppms_instrument_10.mnu"
File 2="_functions_levylab_lib_ppms_instrument_2.mnu"
File 3="_functions_levylab_lib_ppms_instrument_3.mnu"
File 4="_functions_levylab_lib_ppms_instrument_4.mnu"
File 5="_functions_levylab_lib_ppms_instrument_5.mnu"
File 6="_functions_levylab_lib_ppms_instrument_6.mnu"
File 7="_functions_levylab_lib_ppms_instrument_7.mnu"
File 8="_functions_levylab_lib_ppms_instrument_8.mnu"
File 9="_functions_levylab_lib_ppms_instrument_9.mnu"
File 10="functions_LevyLab_lib_PPMS_Instrument.mnu"


[File Group 2]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="If Newer"
Num Files=1
File 0="dir.mnu"
