[Package]
Name="levylab_lib_ppms_instrument"
Version="1.8.2.52"
Release=""
ID=46d757da10b372227cc674dd04f398b9
File Format="vip"
Format Version="2017"
Display Name="PPMS Monitor and Control"


[Description]
Description="Program for logging PPMS status to the PGSQL database. Provides a UI and API for controlling magnet field, temperature, and rotator angle (for PPM2)"
Summary=""
License="BSD-3"
Copyright="Copyright (c) 2021, LevyLab"
Distribution=""
Vendor="LevyLab"
URL="https://github.com/levylabpitt/PPMS-Monitor-and-Control"
Packager="Patrick Irvin"
Demo="FALSE"
Release Notes="[1.8.2]\0A- Update to Instrument Framework v1.10.3"
System Package="FALSE"
Sub Package="FALSE"
License Agreement="TRUE"


[LabVIEW]
close labview before install="FALSE"
restart labview after install="FALSE"
skip mass compile after install="FALSE"


[Platform]
Exclusive_LabVIEW_Version="LabVIEW>=19.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="ALL"


[Script VIs]
PreInstall=""
PostInstall=""
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires="jdp_science_jsontext>=1.6.5.105,jdp_science_lib_common_utilities>=1.3.0.14,jdp_science_postgresql>=0.3.5.23,jki_lib_caraya>=1.2.1.131,jki_lib_json_serialization>=1.1.10.37,jki_lib_serialization>=1.0.1.14,jki_lib_state_machine>=2018.0.7.45,jki_statemachineobjects>=1.4.0.63,labview-zmq>=3.6.1.111,labview_open_source_lib_epoch_datetime>=1.0.0.2,lava_lib_ui_tools>=1.4.1.74,levylab_lib_fileutilities>=1.2.6.13,levylab_lib_graph_utilities>=2.1.7.10,levylab_lib_lvtoitx>=3.2.0.3,levylab_lib_xy_utilities>=1.4.0.17,lvh_toolbox>=2.0.0.35,mgi_lib_1d_array>=1.0.2.3,mgi_lib_application_control>=1.1.1.10,mgi_lib_cluster>=1.1.0.1,mgi_lib_error_handling>=1.1.1.3,mgi_lib_error_reporter>=1.0.2.5,mgi_lib_file>=1.1.0.4,mgi_lib_numeric>=1.1.0.2,mgi_lib_picture_&_image>=1.0.2.1,mgi_lib_read_write_anything>=2.1.4.4,mgi_lib_string>=1.1.1.5,national_instruments_lib_guid_generator>=1.0.2.3,ni_lib_stm>=3.1.0.9,oglib_appcontrol>=4.1.0.7,oglib_array>=4.1.1.14,oglib_dictionary>=4.0.0.4,oglib_error>=4.2.0.23,oglib_file>=4.0.1.22,oglib_lvdata>=5.0.0.27,oglib_lvzip>=4.0.1,oglib_numeric>=4.1.0.8,oglib_string>=5.0.0.25,oglib_time>=4.0.1.3,oglib_variantconfig>=4.0.0.5,levylab_lib_levylab_instruments>=1.10.3.7"
Conflicts=""


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="3"
Sub-Packages=""
Namespaces=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=113
File 0="user.lib/LevyLab/PPMS Instrument/PPMS Monitor and Control.vi"
File 1="user.lib/LevyLab/PPMS Instrument/PPMS_inst.lvproj"
File 2="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Get SMO Name.vi"
File 3="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Get SMO PGSQL Log Paths.vi"
File 4="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Get SMO Port.vi"
File 5="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Get SMO Public API.vi"
File 6="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Handle getAll.vi"
File 7="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/instrument.PPMS3.lvclass"
File 8="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Magnet Limits.vi"
File 9="user.lib/LevyLab/PPMS Instrument/instrument.PPMS3/Typedefs/PPMS3.Commands-enum.ctl"
File 10="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get SMO Name.vi"
File 11="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get SMO PGSQL Log Paths.vi"
File 12="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get SMO Port.vi"
File 13="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get SMO Public API.vi"
File 14="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Handle getAll.vi"
File 15="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/instrument.PPMS2.lvclass"
File 16="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Magnet Limits.vi"
File 17="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/PPMS2 Current to Field (Oe).vi"
File 18="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/PPMS2 Field (Oe) to Current.vi"
File 19="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/PPMS2 Field (T) to Current.vi"
File 20="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Typedefs/PPMS2.Commands-enum.ctl"
File 21="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Get SMO Name.vi"
File 22="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Get SMO PGSQL Log Paths.vi"
File 23="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Get SMO Port.vi"
File 24="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Get SMO Public API.vi"
File 25="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Handle getAll.vi"
File 26="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/instrument.PPMS1.lvclass"
File 27="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Magnet Limits.vi"
File 28="user.lib/LevyLab/PPMS Instrument/instrument.PPMS1/Typedefs/PPMS1.Commands-enum.ctl"
File 29="user.lib/LevyLab/PPMS Instrument/instrument.PPMS UI/Instrument UI.PPMS.lvclass"
File 30="user.lib/LevyLab/PPMS Instrument/instrument.PPMS UI/Process.vi"
File 31="user.lib/LevyLab/PPMS Instrument/instrument.PPMS UI/TEST.vi"
File 32="user.lib/LevyLab/PPMS Instrument/instrument.PPMS UI/private/Convert Number to String.vi"
File 33="user.lib/LevyLab/PPMS Instrument/instrument.PPMS UI/private/Elapsed Time String.vi"
File 34="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Close Instrument.vi"
File 35="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Convert Oersted to Tesla.vi"
File 36="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Convert Tesla to Oersted.vi"
File 37="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get Angle.vi"
File 38="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get Helium Level.vi"
File 39="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get Magnet.vi"
File 40="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get PPMS Class.vi"
File 41="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get SMO Name.vi"
File 42="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get SMO PGSQL Log Paths.vi"
File 43="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get Temperature.vi"
File 44="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Handle Command.vi"
File 45="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Handle getAll.vi"
File 46="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/instrument.PPMS.lvclass"
File 47="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/instrument.PPMS.TestLauncher.vi"
File 48="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Magnet Limits.vi"
File 49="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Open Instrument.vi"
File 50="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Chamber Action to Ring.vi"
File 51="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Chamber Status Ring to String.vi"
File 52="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Get Angle.vi"
File 53="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Get Chamber.vi"
File 54="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Get Helium Level.vi"
File 55="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Get Magnet.vi"
File 56="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Get Temperature.vi"
File 57="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Magnet Status Ring to String.vi"
File 58="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Remote Client.vim"
File 59="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Set Angle.vi"
File 60="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Set Chamber.vi"
File 61="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Set Magnet.vi"
File 62="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Set Temperature.vi"
File 63="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Temperature Status Ring to String.vi"
File 64="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Process.vi"
File 65="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Select PPMS Class.vi"
File 66="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Set Angle.vi"
File 67="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Set Chamber.vi"
File 68="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Set Magnet.vi"
File 69="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Set Temperature.vi"
File 70="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Test Create Start Stop Destroy.vi"
File 71="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Wait Progress Bar.vi"
File 72="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Chamber Command--enum.ctl"
File 73="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Chamber Status--ring.ctl"
File 74="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Commands-enum.ctl"
File 75="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.getAll--cluster.ctl"
File 76="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Magnet Status--cluster.ctl"
File 77="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Magnet Status--ring.ctl"
File 78="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Temperature Status--cluster.ctl"
File 79="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Temperature Status--ring.ctl"
File 80="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/Select PPMS--Enum.ctl"
File 81="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument.dll"
File 82="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument_Example.vi"
File 83="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument_Example_Simple.vi"
File 84="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument_Server.exe"
File 85="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/ReleaseNotes.txt"
File 86="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetChamber.vi"
File 87="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetField.vi"
File 88="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetHelium.vi"
File 89="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetPosition.vi"
File 90="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetTemperature.vi"
File 91="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/OpenQDInstrument.vi"
File 92="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/QDInstrumentExceptionHandler.vi"
File 93="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/SetChamber.vi"
File 94="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/SetField.vi"
File 95="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/SetPosition.vi"
File 96="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/SetTemperature.vi"
File 97="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/WaitFor.vi"
File 98="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/GetPPMSItem.vi"
File 99="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/GetPPMSItem_Example.vi"
File 100="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/SendPPMSCommand.vi"
File 101="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/SendPPMSCommand_Example.vi"
File 102="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/SendPPMSCommand_Rotator.vi"
File 103="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_Float_Example.vi"
File 104="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_FLT.vi"
File 105="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_S16.vi"
File 106="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_S32.vi"
File 107="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_S8.vi"
File 108="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_STR.vi"
File 109="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_U16.vi"
File 110="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_U32.vi"
File 111="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_U8.vi"
File 112="user.lib/LevyLab/_PPMS Instrument_internal_deps/QDInstrument.dll"


[File Group 1]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="Always"
Num Files=2
File 0="_functions_levylab_lib_ppms_instrument_1.mnu"
File 1="functions_LevyLab_lib_PPMS_Instrument.mnu"


[File Group 2]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="If Newer"
Num Files=1
File 0="dir.mnu"
