[Package]
Name="levylab_lib_ppms_instrument"
Version="1.6.0.44"
Release=""
ID=884e72b12899bf9de0201df219e9d53d
File Format="vip"
Format Version="2017"
Display Name="PPMS Monitor and Control"


[Description]
Description="Program for logging PPMS status to the DSC. Provides a UI and API for controlling the magnet field, temperature, and rotator angle (for PPM2)"
Summary=""
License="BSD-3"
Copyright="Copyright (c) 2020, LevyLab"
Distribution=""
Vendor="LevyLab"
URL="https://github.com/levylabpitt/PPMS-Monitor-and-Control"
Packager="Patrick Irvin"
Demo="FALSE"
Release Notes="[1.6.0]\0A- Enable control of PPMS\0A- Update to latest Instrument Framework (v1.7.0)"
System Package="FALSE"
Sub Package="FALSE"
License Agreement="TRUE"


[LabVIEW]
close labview before install="FALSE"
restart labview after install="FALSE"
skip mass compile after install="FALSE"


[Platform]
Exclusive_LabVIEW_Version="LabVIEW>=16.0"
Exclusive_LabVIEW_System="ALL"
Exclusive_OS="ALL"


[Script VIs]
PreInstall=""
PostInstall=""
PreUninstall=""
PostUninstall=""
Verify=""
PreBuild=""
PostBuild=""


[Dependencies]
AutoReqProv=FALSE
Requires="levylab_lib_levylab_instruments>=1.7.0.95"
Conflicts=""


[Activation]
License File=""
Licensed Library=""


[Files]
Num File Groups="3"
Sub-Packages=""
Namespaces=""


[File Group 0]
Target Dir="<application>"
Replace Mode="Always"
Num Files=144
File 0="user.lib/LevyLab/PPMS Instrument/PPMS Monitor and Control.vi"
File 1="user.lib/LevyLab/PPMS Instrument/PPMS_inst.lvproj"
File 2="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2 UI/Instrument.PPMS2 UI.lvclass"
File 3="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2 UI/Launch PPMS2 UI.vi"
File 4="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2 UI/Process.vi"
File 5="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Close Instrument.vi"
File 6="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Configure Instrument.vi"
File 7="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get Angle.vi"
File 8="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get Helium Level.vi"
File 9="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get Magnet Field.vi"
File 10="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get SMO Name.vi"
File 11="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get SMO PGSQL Log Paths.vi"
File 12="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get SMO Port.vi"
File 13="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get SMO Public API.vi"
File 14="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Get Temperature.vi"
File 15="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/getAll.vi"
File 16="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Handle Command.vi"
File 17="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Instrument.PPMS2.Configuration Window.vi"
File 18="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/instrument.PPMS2.lvclass"
File 19="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Instrument.PPMS2.Read Configuration File.vi"
File 20="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/instrument.PPMS2.TestLauncher.vi"
File 21="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Instrument.PPMS2.Write Configuration File.vi"
File 22="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Open Instrument.vi"
File 23="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/PPMS2 Client.vi"
File 24="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/PPMS2 Current to Field (Oe).vi"
File 25="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/PPMS2 Field (Oe) to Current.vi"
File 26="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/PPMS2 Field (T) to Current.vi"
File 27="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/PPMS2 Type.vi"
File 28="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/PPMS2.Command Enum to String.vi"
File 29="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/PPMS2.Status Ring to String.vi"
File 30="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Process.vi"
File 31="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Set Angle.vi"
File 32="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Set Magnet Field.vi"
File 33="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Set Temperature.vi"
File 34="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Typedefs/PPMS2.Commands-enum.ctl"
File 35="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Typedefs/PPMS2.getAll--cluster.ctl"
File 36="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Typedefs/PPMS2.Magnet Field--cluster.ctl"
File 37="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Typedefs/PPMS2.Magnet Status--cluster.ctl"
File 38="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Typedefs/PPMS2.Magnet Status--ring.ctl"
File 39="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Typedefs/PPMS2.Temperature Status--cluster.ctl"
File 40="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Typedefs/PPMS2.Temperature Status--ring.ctl"
File 41="user.lib/LevyLab/PPMS Instrument/instrument.PPMS2/Typedefs/PPMS2.Temperature--cluster.ctl"
File 42="user.lib/LevyLab/PPMS Instrument/instrument.PPMS UI/Convert Number to String.vi"
File 43="user.lib/LevyLab/PPMS Instrument/instrument.PPMS UI/Elapsed Time String.vi"
File 44="user.lib/LevyLab/PPMS Instrument/instrument.PPMS UI/Instrument.PPMS UI.lvclass"
File 45="user.lib/LevyLab/PPMS Instrument/instrument.PPMS UI/Launch PPMS UI.vi"
File 46="user.lib/LevyLab/PPMS Instrument/instrument.PPMS UI/Process.vi"
File 47="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Close Instrument.vi"
File 48="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get Helium Level.vi"
File 49="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get Magnet Field.vi"
File 50="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get SMO Name.vi"
File 51="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get SMO PGSQL Log Paths.vi"
File 52="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get SMO Port.vi"
File 53="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get SMO Public API.vi"
File 54="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Get Temperature.vi"
File 55="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/getAll.vi"
File 56="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Handle Command.vi"
File 57="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/instrument.PPMS.lvclass"
File 58="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/instrument.PPMS.TestLauncher.vi"
File 59="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Open Instrument.vi"
File 60="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS Client.vi"
File 61="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Command Enum to String.vi"
File 62="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/PPMS.Status Ring to String.vi"
File 63="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Process.vi"
File 64="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Set Magnet Field.vi"
File 65="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Set Temperature.vi"
File 66="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Commands-enum.ctl"
File 67="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.getAll--cluster.ctl"
File 68="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Magnet Field--cluster.ctl"
File 69="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Magnet Status--cluster.ctl"
File 70="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Magnet Status--ring.ctl"
File 71="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Temperature Status--cluster.ctl"
File 72="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Temperature Status--ring.ctl"
File 73="user.lib/LevyLab/PPMS Instrument/instrument.PPMS/Typedefs/PPMS.Temperature--cluster.ctl"
File 74="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument.dll"
File 75="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument.llx"
File 76="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument_Example.vi"
File 77="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument_Server.exe"
File 78="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/ReleaseNotes.txt"
File 79="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetChamber.vi"
File 80="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetField.vi"
File 81="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetHelium.vi"
File 82="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetPosition.vi"
File 83="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/GetTemperature.vi"
File 84="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/OpenQDInstrument.vi"
File 85="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/QDInstrumentExceptionHandler.vi"
File 86="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/SetChamber.vi"
File 87="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/SetField.vi"
File 88="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/SetPosition.vi"
File 89="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/SetTemperature.vi"
File 90="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/QDInstrument/WaitFor.vi"
File 91="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/GetPPMSItem.vi"
File 92="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/GetPPMSItem_Example.vi"
File 93="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/SendPPMSCommand.vi"
File 94="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/SendPPMSCommand_Example.vi"
File 95="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/PPMS/SendPPMSCommand_Rotator.vi"
File 96="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_Float_Example.vi"
File 97="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_FLT.vi"
File 98="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_S16.vi"
File 99="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_S32.vi"
File 100="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_S8.vi"
File 101="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_STR.vi"
File 102="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_U16.vi"
File 103="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_U32.vi"
File 104="user.lib/LevyLab/PPMS Instrument/drivers/QDInstrument_LabView/CAN/CAN_QDInstrument.llb/ReadSDO_U8.vi"
File 105="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4-10V Manual Rev 3.1.pdf"
File 106="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4-10V Spec Sheet.pdf"
File 107="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/LOG.TXT"
File 108="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/README.TXT"
File 109="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4DEMO.LLB/CS-4 Device.vi"
File 110="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4DEMO.LLB/CS-4 Operate.vi"
File 111="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4DEMO.LLB/CS-4 Setup Dialog.vi"
File 112="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Close.vi"
File 113="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Config.vi"
File 114="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Error Message.vi"
File 115="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Error Status.vi"
File 116="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Get Limits.vi"
File 117="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Get Operational Mode.vi"
File 118="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Get Ranges.vi"
File 119="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Get Rates.vi"
File 120="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Get Stb.vi"
File 121="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Get Sweep Mode.vi"
File 122="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Get Switch Heater.vi"
File 123="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Get Units.vi"
File 124="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Initialize.vi"
File 125="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Read Current.vi"
File 126="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Read Mag Current.vi"
File 127="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Read Mag Volts.vi"
File 128="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Read Volts.vi"
File 129="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Recall.vi"
File 130="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Reset.vi"
File 131="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Revision Query.vi"
File 132="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Self-Test.vi"
File 133="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Set Limits.vi"
File 134="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Set Ranges.vi"
File 135="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Set Rates.vi"
File 136="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Set Sweep Mode.vi"
File 137="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Set Switch Heater.vi"
File 138="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Set Units.vi"
File 139="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Status.vi"
File 140="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Utility Clean Up Initialize.vi"
File 141="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Utility Default Instrument Setup.vi"
File 142="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/CS-4 Write.vi"
File 143="user.lib/LevyLab/PPMS Instrument/drivers/CS4LV6_1/CS4.llb/sweep.ctl"


[File Group 1]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="Always"
Num Files=3
File 0="_functions_levylab_lib_ppms_instrument_1.mnu"
File 1="_functions_levylab_lib_ppms_instrument_2.mnu"
File 2="functions_LevyLab_lib_PPMS_Instrument.mnu"


[File Group 2]
Target Dir="<menus>/Categories/LevyLab"
Replace Mode="If Newer"
Num Files=1
File 0="dir.mnu"
